import type { GoalOption, IndustryData, IndustryKey } from "@/lib/demoTypes";

const spark = {
  up: [24, 30, 28, 42, 48, 58],
  down: [58, 51, 46, 43, 38, 34],
  neutral: [42, 44, 43, 45, 44, 46],
};

function lead(
  id: string,
  name: string,
  company: string,
  source: string,
  status: IndustryData["leads"][number]["status"],
  aiScore: number,
  assigned: string,
  value: string,
  numericValue: number,
  need: string,
  lastContact = "2 days ago",
): IndustryData["leads"][number] {
  const priority = aiScore > 85 ? "High" : aiScore > 65 ? "Medium" : "Low";

  return {
    id,
    name,
    company,
    source,
    status,
    aiScore,
    assigned,
    value,
    numericValue,
    lastContact,
    need,
    phone: "+91 98765 43210",
    email: `${name.toLowerCase().replace(/[^a-z]/g, ".")}@example.com`,
    daysInStage: Math.max(1, Math.round((100 - aiScore) / 9)),
    priority,
    scoreReasons: [
      aiScore > 85 ? "Responded within 1 hour" : "Recent engagement captured",
      numericValue > 1000000 ? `High potential value ${value}` : `Clear requirement worth ${value}`,
      source === "Referral" ? "Referral source converts better" : `${source} source has active intent`,
    ],
    recommendedAction:
      aiScore > 85
        ? "Call now. This lead is most likely to convert if contacted today."
        : aiScore > 65
          ? "Send a focused WhatsApp follow-up and schedule the next step."
          : "Add to nurture workflow and ask one qualifying question.",
    timeline: [
      `${source} inquiry captured automatically`,
      `Assigned to ${assigned}`,
      `AI score updated to ${aiScore}`,
      `${need} requirement added to record`,
      `Next follow-up due ${lastContact === "Today" ? "today" : "this week"}`,
    ],
    tags: [need, status, source],
  };
}

function deal(id: string, leadId: string, name: string, value: string, numericValue: number, assigned: string, daysInStage: number, priority: "High" | "Medium" | "Low") {
  return { id, leadId, name, value, numericValue, assigned, daysInStage, priority };
}

function build(data: Omit<IndustryData, "customers"> & { customers?: IndustryData["customers"] }): IndustryData {
  return {
    ...data,
    customers: data.customers ?? data.leads.slice(0, 6),
  };
}

export const goalOptions: GoalOption[] = [
  { key: "leads", label: "Manage and track leads", tab: "leads" },
  { key: "followups", label: "Automate follow-ups", tab: "tasks" },
  { key: "team", label: "Track my sales team", tab: "roles" },
  { key: "tickets", label: "Handle support tickets", tab: "tickets" },
  { key: "whatsapp", label: "WhatsApp automation", tab: "workflows" },
  { key: "revenue", label: "Revenue dashboard", tab: "reports" },
  { key: "ai-scoring", label: "AI lead scoring", tab: "ai" },
  { key: "workflows", label: "Custom workflows", tab: "workflows" },
];

export const defaultIndustryKey: IndustryKey = "real-estate";

export const industryData: Record<IndustryKey, IndustryData> = {
  "general-business": build({
    key: "general-business",
    name: "General Business CRM",
    tagline: "For agencies, consultants, and growing service teams",
    description: "For agencies, consultants, and growing service teams",
    icon: "business",
    welcomeMessage: "Here's your General Business CRM - one system for leads, proposals, projects, tasks, and revenue.",
    kpis: [
      { label: "Active Projects", value: "14", change: "+18%", trend: "up", sparkline: spark.up },
      { label: "Proposals Sent", value: "8", change: "+3", trend: "up", sparkline: spark.up },
      { label: "Revenue This Month", value: "Rs. 6.2L", change: "+21%", trend: "up", sparkline: spark.up },
      { label: "Overdue Invoices", value: "3", change: "-2", trend: "down", sparkline: spark.down },
      { label: "Client Satisfaction", value: "4.7/5", change: "+0.2", trend: "up", sparkline: spark.up },
      { label: "Conversion Rate", value: "41%", change: "+5%", trend: "up", sparkline: spark.up },
      { label: "Pending Approvals", value: "5", change: "-1", trend: "down", sparkline: spark.down },
      { label: "Team Members", value: "9", change: "Live", trend: "neutral", sparkline: spark.neutral },
    ],
    leads: [
      lead("gb-1", "Amit Sharma", "Novakos Healthcare", "Website", "Hot", 91, "Priya", "Rs. 2.5L", 250000, "Custom operations CRM", "Today"),
      lead("gb-2", "Riya Kapoor", "Elite Events", "Instagram", "Warm", 73, "Rahul", "Rs. 1.8L", 180000, "Proposal workflow"),
      lead("gb-3", "Vikram Mehta", "Urban Estates", "Referral", "Hot", 86, "Sneha", "Rs. 3.2L", 320000, "Sales CRM"),
      lead("gb-4", "Ananya Rao", "Bright Legal", "LinkedIn", "Warm", 69, "Priya", "Rs. 1.1L", 110000, "Client portal"),
      lead("gb-5", "Manish Jain", "StudioWorks", "WhatsApp", "New", 58, "Aman", "Rs. 90K", 90000, "Task tracking"),
      lead("gb-6", "Nisha Batra", "ScaleUp Advisors", "Website", "Hot", 82, "Sneha", "Rs. 2.1L", 210000, "Lead pipeline"),
      lead("gb-7", "Kunal Arora", "OpsCraft", "IndiaMART", "Cold", 39, "Unassigned", "Rs. 75K", 75000, "Basic CRM"),
      lead("gb-8", "Meera Sethi", "Northstar Agency", "Referral", "Warm", 76, "Rahul", "Rs. 1.6L", 160000, "Revenue dashboard"),
    ],
    pipelineStages: ["Brief Received", "Proposal Sent", "Review", "Negotiation", "Project Won"],
    pipelineDeals: {
      "Brief Received": [deal("gbd-1", "gb-5", "StudioWorks CRM", "Rs. 90K", 90000, "Aman", 2, "Medium")],
      "Proposal Sent": [deal("gbd-2", "gb-1", "Novakos CRM", "Rs. 2.5L", 250000, "Priya", 3, "High"), deal("gbd-3", "gb-8", "Northstar Dashboard", "Rs. 1.6L", 160000, "Rahul", 1, "Medium")],
      Review: [deal("gbd-4", "gb-4", "Bright Legal Portal", "Rs. 1.1L", 110000, "Priya", 5, "Medium")],
      Negotiation: [deal("gbd-5", "gb-3", "Urban Estates Sales CRM", "Rs. 3.2L", 320000, "Sneha", 6, "High")],
      "Project Won": [deal("gbd-6", "gb-6", "ScaleUp CRM", "Rs. 2.1L", 210000, "Sneha", 1, "High")],
    },
    tasks: [
      { id: "gbt-1", title: "Send revised proposal to Novakos", related: "Amit Sharma", priority: "High", assigned: "Priya", due: "Today", bucket: "Due Today", type: "follow-up" },
      { id: "gbt-2", title: "Call Urban Estates for final approval", related: "Vikram Mehta", priority: "High", assigned: "Sneha", due: "Today", bucket: "Due Today", type: "follow-up" },
      { id: "gbt-3", title: "Collect process notes from Bright Legal", related: "Ananya Rao", priority: "Medium", assigned: "Priya", due: "Tomorrow", bucket: "Due This Week", type: "document" },
      { id: "gbt-4", title: "Follow up unpaid invoice", related: "ScaleUp Advisors", priority: "Medium", assigned: "Accounts", due: "Yesterday", bucket: "Overdue", type: "payment" },
      { id: "gbt-5", title: "Prepare demo for Northstar Agency", related: "Meera Sethi", priority: "Low", assigned: "Rahul", due: "Friday", bucket: "Due This Week", type: "internal" },
      { id: "gbt-6", title: "Nurture low-fit IndiaMART lead", related: "Kunal Arora", priority: "Low", assigned: "Aman", due: "Next week", bucket: "Upcoming", type: "follow-up" },
    ],
    tickets: [
      { id: "#1042", subject: "Need weekly report export", customer: "Elite Events", status: "Open", priority: "Medium", assigned: "Support", timeOpen: "3h" },
      { id: "#1048", subject: "Dashboard filter request", customer: "Urban Estates", status: "In Progress", priority: "Low", assigned: "Ankit", timeOpen: "1d" },
      { id: "#1051", subject: "WhatsApp template approval", customer: "Novakos Healthcare", status: "Escalated", priority: "High", assigned: "Riya", timeOpen: "8h" },
      { id: "#1056", subject: "Client portal login issue", customer: "Bright Legal", status: "Resolved", priority: "Medium", assigned: "Support", timeOpen: "2d" },
    ],
    workflows: [
      { id: "gbw-1", name: "High-value lead assignment", active: true, trigger: "New lead is created", condition: "Value above Rs. 2L", action: "Assign senior owner and notify manager", runCount: 38 },
      { id: "gbw-2", name: "Proposal follow-up", active: true, trigger: "Proposal sent", condition: "No reply in 48 hours", action: "Send WhatsApp reminder and create task", runCount: 47 },
      { id: "gbw-3", name: "Invoice recovery", active: false, trigger: "Invoice overdue", condition: "Due date crossed", action: "Notify owner and accounts team", runCount: 12 },
    ],
    activityFeed: [
      { id: "gba-1", text: "Priya sent proposal to Novakos Healthcare", timestamp: "8 min ago", initials: "PS" },
      { id: "gba-2", text: "AI scored Urban Estates as Hot", timestamp: "22 min ago", initials: "AI" },
      { id: "gba-3", text: "Rahul moved Northstar to Proposal Sent", timestamp: "1h ago", initials: "RK" },
      { id: "gba-4", text: "Invoice reminder sent to ScaleUp Advisors", timestamp: "2h ago", initials: "AR" },
      { id: "gba-5", text: "New WhatsApp lead captured from StudioWorks", timestamp: "3h ago", initials: "WA" },
      { id: "gba-6", text: "Manager approved Urban Estates discount", timestamp: "Yesterday", initials: "MG" },
    ],
    aiInsights: [
      "Referral leads are converting 1.8x better than paid ads",
      "Two proposal-stage deals need action within 24 hours",
      "Overdue invoices are blocking Rs. 2.4L in cash flow",
      "Priya has the fastest first-response time this week",
    ],
    aiChatQA: [
      { question: "Which deals should I focus on today?", answer: "Focus on Urban Estates and Novakos Healthcare. Both have clear budgets, active decision makers, and next steps due today.", followUps: ["Show proposal risks", "Draft follow-up"] },
      { question: "What is my current pipeline worth?", answer: "Your active pipeline is Rs. 11.5L across five active stages. Negotiation has the highest value concentration.", followUps: ["Open pipeline", "Show stale deals"] },
      { question: "Which team member is overloaded?", answer: "Priya has the most high-priority items today. Move one lower-value follow-up to Aman to protect the Novakos proposal.", followUps: ["Show tasks", "Switch role"] },
      { question: "Which source gives best leads?", answer: "Referrals are strongest by conversion, while Website produces the highest volume. Keep both but automate faster website assignment.", followUps: ["Filter referrals", "Run workflow"] },
      { question: "What automation should I add next?", answer: "Add an invoice recovery workflow tied to overdue payment age. It can recover revenue without extra manual reminders.", followUps: ["Build workflow", "Calculate ROI"] },
    ],
    reportsData: {
      leadSources: [
        { label: "Website", value: 30, color: "#2563eb" },
        { label: "WhatsApp", value: 18, color: "#16a34a" },
        { label: "Instagram", value: 14, color: "#4f46e5" },
        { label: "Referral", value: 24, color: "#f59e0b" },
        { label: "IndiaMART", value: 8, color: "#64748b" },
        { label: "LinkedIn", value: 6, color: "#0ea5e9" },
      ],
      funnel: [
        { stage: "Brief", count: 42, dropoff: 0 },
        { stage: "Proposal", count: 28, dropoff: 33 },
        { stage: "Review", count: 18, dropoff: 36 },
        { stage: "Negotiation", count: 11, dropoff: 39 },
        { stage: "Won", count: 7, dropoff: 36 },
      ],
      team: [
        { name: "Priya", assigned: 28, closed: 9 },
        { name: "Rahul", assigned: 23, closed: 6 },
        { name: "Sneha", assigned: 21, closed: 8 },
        { name: "Aman", assigned: 17, closed: 4 },
      ],
      revenue: [
        { month: "Nov", value: 380000 },
        { month: "Dec", value: 420000 },
        { month: "Jan", value: 510000 },
        { month: "Feb", value: 490000 },
        { month: "Mar", value: 570000 },
        { month: "Apr", value: 620000 },
      ],
    },
    roiDefaults: { teamSize: 9, leadsPerMonth: 240, avgDealValue: 160000, manualHours: 9, lostDeals: 5 },
    blueprintSummary: {
      modules: ["Lead capture", "Proposal pipeline", "Client records", "Task automation", "Invoice follow-up", "Revenue dashboard"],
      automations: ["Auto-assign high-value leads", "Proposal follow-up after 48 hours", "Invoice recovery alerts"],
      roles: ["Business Owner", "Admin", "Manager", "Sales User", "Operations User"],
      timeline: "3-4 weeks",
      onboarding: "4 days",
    },
    notifications: [
      { id: "gbn-1", text: "AI scored 2 new hot leads" },
      { id: "gbn-2", text: "3 proposal follow-ups due today" },
      { id: "gbn-3", text: "One invoice recovery workflow is paused" },
    ],
    whatsappTemplate: "Hi {{name}}, following up on your CRM enquiry. I can share a workflow-specific demo and proposal today. Would a quick call work?",
    testimonial: {
      quote: "HNX replaced our spreadsheets with a CRM that follows our exact client workflow.",
      author: "Neha",
      company: "Northstar Agency",
    },
  }),

  education: build({
    key: "education",
    name: "Education CRM",
    tagline: "For schools, coaching institutes, admission teams",
    description: "For schools, coaching institutes, admission teams",
    icon: "education",
    welcomeMessage: "Here's your Education CRM - tracking every enquiry, counselling call, form, fee reminder, and enrollment.",
    kpis: [
      { label: "New Enquiries", value: "312", change: "+22%", trend: "up", sparkline: spark.up },
      { label: "Counsellings Done", value: "86", change: "+14%", trend: "up", sparkline: spark.up },
      { label: "Admissions", value: "47", change: "+9", trend: "up", sparkline: spark.up },
      { label: "Fee Collected", value: "Rs. 38.4L", change: "+18%", trend: "up", sparkline: spark.up },
      { label: "Pending Follow-ups", value: "29", change: "-7%", trend: "down", sparkline: spark.down },
      { label: "Conversion Rate", value: "18%", change: "+3%", trend: "up", sparkline: spark.up },
      { label: "Batch Fill", value: "74%", change: "+6%", trend: "up", sparkline: spark.up },
      { label: "Counsellors", value: "5", change: "Live", trend: "neutral", sparkline: spark.neutral },
    ],
    leads: [
      lead("ed-1", "Aarav Mehta", "MBA Applicant", "Website", "Hot", 89, "Sunita", "Rs. 2.4L", 240000, "MBA admission", "Today"),
      lead("ed-2", "Riya Sharma", "BBA Applicant", "Facebook", "Warm", 71, "Raj", "Rs. 1.8L", 180000, "BBA counselling"),
      lead("ed-3", "Arnav Patel", "Engineering Applicant", "Referral", "Hot", 85, "Sunita", "Rs. 3.2L", 320000, "Engineering admission"),
      lead("ed-4", "Kavya Singh", "Medical Applicant", "Walk-in", "Cold", 42, "Priya", "Rs. 4.5L", 450000, "Medical coaching"),
      lead("ed-5", "Ishaan Gupta", "Law Applicant", "WhatsApp", "Warm", 68, "Raj", "Rs. 1.6L", 160000, "Law program"),
      lead("ed-6", "Meera Nair", "JEE Applicant", "Instagram", "Hot", 91, "Priya", "Rs. 1.2L", 120000, "JEE batch", "Today"),
      lead("ed-7", "Dev Malhotra", "Parent Inquiry", "Website", "New", 57, "Unassigned", "Rs. 90K", 90000, "Grade 8 admission"),
      lead("ed-8", "Tanya Khanna", "MBA Applicant", "Referral", "Warm", 77, "Sunita", "Rs. 2.4L", 240000, "MBA weekend batch"),
    ],
    pipelineStages: ["New Enquiry", "Counselling Scheduled", "Counselling Done", "Form Submitted", "Enrolled"],
    pipelineDeals: {
      "New Enquiry": [deal("edd-1", "ed-7", "Dev Malhotra", "Rs. 90K", 90000, "Unassigned", 1, "Low")],
      "Counselling Scheduled": [deal("edd-2", "ed-1", "Aarav Mehta", "Rs. 2.4L", 240000, "Sunita", 2, "High"), deal("edd-3", "ed-5", "Ishaan Gupta", "Rs. 1.6L", 160000, "Raj", 1, "Medium")],
      "Counselling Done": [deal("edd-4", "ed-2", "Riya Sharma", "Rs. 1.8L", 180000, "Raj", 4, "Medium")],
      "Form Submitted": [deal("edd-5", "ed-3", "Arnav Patel", "Rs. 3.2L", 320000, "Sunita", 5, "High"), deal("edd-6", "ed-8", "Tanya Khanna", "Rs. 2.4L", 240000, "Sunita", 2, "Medium")],
      Enrolled: [deal("edd-7", "ed-6", "Meera Nair", "Rs. 1.2L", 120000, "Priya", 1, "High")],
    },
    tasks: [
      { id: "edt-1", title: "Schedule counselling for Aarav Mehta", related: "Aarav Mehta", priority: "High", assigned: "Sunita", due: "Today", bucket: "Due Today", type: "follow-up" },
      { id: "edt-2", title: "Send course details to Riya", related: "Riya Sharma", priority: "Medium", assigned: "Raj", due: "Today", bucket: "Due Today", type: "document" },
      { id: "edt-3", title: "Follow up - no response from Kavya", related: "Kavya Singh", priority: "Medium", assigned: "Priya", due: "Yesterday", bucket: "Overdue", type: "follow-up" },
      { id: "edt-4", title: "Remind Arnav about admission deadline", related: "Arnav Patel", priority: "High", assigned: "Sunita", due: "Tomorrow", bucket: "Due This Week", type: "follow-up" },
      { id: "edt-5", title: "Fee payment follow-up - 8 students", related: "Admissions Batch", priority: "High", assigned: "Finance", due: "Friday", bucket: "Due This Week", type: "payment" },
      { id: "edt-6", title: "Upload counselling notes for Tanya", related: "Tanya Khanna", priority: "Low", assigned: "Sunita", due: "Next week", bucket: "Upcoming", type: "document" },
    ],
    tickets: [
      { id: "#2041", subject: "Parent needs scholarship details", customer: "Aarav Mehta", status: "Open", priority: "Medium", assigned: "Front Desk", timeOpen: "2h" },
      { id: "#2046", subject: "Document upload issue", customer: "Arnav Patel", status: "In Progress", priority: "High", assigned: "Admin", timeOpen: "7h" },
      { id: "#2050", subject: "Fee receipt not visible", customer: "Meera Nair", status: "Resolved", priority: "Low", assigned: "Finance", timeOpen: "1d" },
      { id: "#2054", subject: "Counselling slot reschedule", customer: "Ishaan Gupta", status: "Open", priority: "Medium", assigned: "Raj", timeOpen: "4h" },
    ],
    workflows: [
      { id: "edw-1", name: "New web enquiry assignment", active: true, trigger: "New web enquiry", condition: "Course selected", action: "Assign counsellor and send course brochure on WhatsApp", runCount: 62 },
      { id: "edw-2", name: "Counselling reminder", active: true, trigger: "Counselling done", condition: "No form in 72 hours", action: "Send reminder and schedule callback", runCount: 31 },
      { id: "edw-3", name: "Fee due reminder", active: true, trigger: "Fee due in 3 days", condition: "Payment not received", action: "Send SMS and WhatsApp reminder", runCount: 44 },
    ],
    activityFeed: [
      { id: "eda-1", text: "Sunita scheduled MBA counselling for Aarav", timestamp: "10 min ago", initials: "SS" },
      { id: "eda-2", text: "AI flagged Meera as very hot for JEE batch", timestamp: "29 min ago", initials: "AI" },
      { id: "eda-3", text: "Course brochure sent to 5 new enquiries", timestamp: "1h ago", initials: "WA" },
      { id: "eda-4", text: "Raj moved Riya to Counselling Done", timestamp: "2h ago", initials: "RJ" },
      { id: "eda-5", text: "Finance reminder sent to 8 applicants", timestamp: "3h ago", initials: "FN" },
      { id: "eda-6", text: "Arnav submitted admission form", timestamp: "Yesterday", initials: "AP" },
    ],
    aiInsights: [
      "MBA enquiries are converting at 28%, highest across courses",
      "14 students have counselling done but have not submitted forms",
      "Tuesday is your best counselling day with 34% same-day conversion",
      "Fee reminders can recover Rs. 6.8L this month",
    ],
    aiChatQA: [
      { question: "Which students are likely to enroll?", answer: "Aarav Mehta, Meera Nair, and Arnav Patel are highest priority. Aarav needs counselling confirmation, Meera is already enrolled-ready, and Arnav has submitted his form.", followUps: ["Create reminders", "Show form pending"] },
      { question: "Which course converts best?", answer: "MBA converts best at 28%. Engineering leads are high value but need faster document follow-up.", followUps: ["Open reports", "Filter MBA"] },
      { question: "What fee follow-ups are pending?", answer: "Eight applicants need fee reminders. Prioritize Arnav and Tanya because they are closest to enrollment.", followUps: ["Send WhatsApp", "Assign finance"] },
      { question: "Which counsellor is performing best?", answer: "Sunita has the highest conversion and owns the strongest MBA pipeline. Raj needs help with two delayed follow-ups.", followUps: ["Switch role", "Show tasks"] },
      { question: "Write a parent follow-up", answer: "Hi, your counselling session is confirmed. Please keep marksheets ready so we can complete eligibility and next steps quickly.", followUps: ["Send to lead", "Edit message"] },
    ],
    reportsData: {
      leadSources: [
        { label: "Website", value: 32, color: "#2563eb" },
        { label: "WhatsApp", value: 18, color: "#16a34a" },
        { label: "Facebook", value: 22, color: "#4f46e5" },
        { label: "Referral", value: 17, color: "#f59e0b" },
        { label: "Walk-in", value: 9, color: "#64748b" },
        { label: "Instagram", value: 2, color: "#ec4899" },
      ],
      funnel: [
        { stage: "Enquiry", count: 312, dropoff: 0 },
        { stage: "Counselling", count: 148, dropoff: 53 },
        { stage: "Done", count: 86, dropoff: 42 },
        { stage: "Form", count: 58, dropoff: 33 },
        { stage: "Enrolled", count: 47, dropoff: 19 },
      ],
      team: [
        { name: "Sunita", assigned: 82, closed: 21 },
        { name: "Raj", assigned: 66, closed: 11 },
        { name: "Priya", assigned: 58, closed: 10 },
        { name: "Finance", assigned: 34, closed: 5 },
      ],
      revenue: [
        { month: "Nov", value: 2400000 },
        { month: "Dec", value: 2700000 },
        { month: "Jan", value: 3100000 },
        { month: "Feb", value: 2900000 },
        { month: "Mar", value: 3500000 },
        { month: "Apr", value: 3840000 },
      ],
    },
    roiDefaults: { teamSize: 5, leadsPerMonth: 320, avgDealValue: 180000, manualHours: 8, lostDeals: 12 },
    blueprintSummary: {
      modules: ["Inquiry capture", "Admission pipeline", "Counsellor dashboard", "Document checklist", "Fee reminders", "Parent communication"],
      automations: ["Auto-assign by course", "Counselling no-response reminders", "Fee due WhatsApp alerts"],
      roles: ["Business Owner", "Admin", "Manager", "Sales User", "Operations User"],
      timeline: "3-5 weeks",
      onboarding: "5 days",
    },
    notifications: [
      { id: "edn-1", text: "14 counselling-done students need form follow-up" },
      { id: "edn-2", text: "MBA enquiries are up 22% this week" },
      { id: "edn-3", text: "Fee reminders recovered Rs. 2.1L today" },
    ],
    whatsappTemplate: "Hi {{name}}, your counselling session is confirmed. Please keep your marksheets ready. We will guide you through eligibility and next steps.",
    testimonial: {
      quote: "Our admission team now tracks every inquiry, parent call, document, and fee reminder in one CRM.",
      author: "Sunita",
      company: "ABC Institute",
    },
  }),

  healthcare: build({
    key: "healthcare",
    name: "Healthcare CRM",
    tagline: "For clinics, hospitals, and medical service teams",
    description: "For clinics, hospitals, and medical service teams",
    icon: "healthcare",
    welcomeMessage: "Here's your Healthcare CRM - managing appointment requests, patient follow-ups, doctor queues, and feedback.",
    kpis: [
      { label: "Appointments Today", value: "34", change: "+12%", trend: "up", sparkline: spark.up },
      { label: "New Patients", value: "18", change: "+6", trend: "up", sparkline: spark.up },
      { label: "Follow-ups Due", value: "12", change: "-4", trend: "down", sparkline: spark.down },
      { label: "No-show Rate", value: "9%", change: "-3%", trend: "down", sparkline: spark.down },
      { label: "Revenue Today", value: "Rs. 42K", change: "+15%", trend: "up", sparkline: spark.up },
      { label: "Bed Occupancy", value: "67%", change: "+4%", trend: "up", sparkline: spark.up },
      { label: "Avg Wait", value: "18 min", change: "-5", trend: "down", sparkline: spark.down },
      { label: "Active Doctors", value: "6", change: "Live", trend: "neutral", sparkline: spark.neutral },
    ],
    leads: [
      lead("hc-1", "Priya Nair", "Ortho", "Website", "New", 88, "Dr. Sharma", "Rs. 2,500", 2500, "Knee pain appointment", "Today"),
      lead("hc-2", "Ramesh Gupta", "Cardio", "Referral", "Warm", 76, "Dr. Mehta", "Rs. 5,000", 5000, "Cardiology consultation"),
      lead("hc-3", "Sunita Patel", "Dental", "Walk-in", "Converted", 64, "Dr. Joshi", "Rs. 8,500", 8500, "Dental treatment"),
      lead("hc-4", "Arun Kumar", "ENT", "WhatsApp", "New", 84, "Dr. Sharma", "Rs. 1,800", 1800, "ENT appointment", "Today"),
      lead("hc-5", "Naveen Shah", "Dermatology", "Website", "Warm", 67, "Dr. Rao", "Rs. 3,000", 3000, "Skin treatment"),
      lead("hc-6", "Megha Soni", "Paediatrics", "Referral", "Hot", 90, "Dr. Mehta", "Rs. 2,200", 2200, "Child fever follow-up"),
      lead("hc-7", "Harish Jain", "Physio", "JustDial", "Cold", 38, "Unassigned", "Rs. 1,200", 1200, "Physiotherapy query"),
      lead("hc-8", "Asha Verma", "Gynaecology", "WhatsApp", "Warm", 72, "Dr. Rao", "Rs. 4,500", 4500, "Follow-up visit"),
    ],
    pipelineStages: ["Appointment Request", "Confirmed", "Visited", "Treatment Ongoing", "Follow-up Scheduled"],
    pipelineDeals: {
      "Appointment Request": [deal("hcd-1", "hc-1", "Priya Nair", "Rs. 2,500", 2500, "Dr. Sharma", 1, "High"), deal("hcd-2", "hc-4", "Arun Kumar", "Rs. 1,800", 1800, "Dr. Sharma", 1, "High")],
      Confirmed: [deal("hcd-3", "hc-2", "Ramesh Gupta", "Rs. 5,000", 5000, "Dr. Mehta", 2, "Medium")],
      Visited: [deal("hcd-4", "hc-3", "Sunita Patel", "Rs. 8,500", 8500, "Dr. Joshi", 1, "Low")],
      "Treatment Ongoing": [deal("hcd-5", "hc-5", "Naveen Shah", "Rs. 3,000", 3000, "Dr. Rao", 4, "Medium")],
      "Follow-up Scheduled": [deal("hcd-6", "hc-8", "Asha Verma", "Rs. 4,500", 4500, "Dr. Rao", 3, "Medium")],
    },
    tasks: [
      { id: "hct-1", title: "Confirm appointment for Priya Nair", related: "Priya Nair", priority: "High", assigned: "Front Desk", due: "Today", bucket: "Due Today", type: "follow-up" },
      { id: "hct-2", title: "Send directions to Arun Kumar", related: "Arun Kumar", priority: "Medium", assigned: "Front Desk", due: "Today", bucket: "Due Today", type: "follow-up" },
      { id: "hct-3", title: "Follow-up call after dental visit", related: "Sunita Patel", priority: "Low", assigned: "Care Team", due: "Tomorrow", bucket: "Due This Week", type: "follow-up" },
      { id: "hct-4", title: "Collect patient feedback", related: "Ramesh Gupta", priority: "Medium", assigned: "Care Team", due: "Yesterday", bucket: "Overdue", type: "support" },
      { id: "hct-5", title: "Update treatment plan", related: "Naveen Shah", priority: "Medium", assigned: "Dr. Rao", due: "Friday", bucket: "Due This Week", type: "document" },
      { id: "hct-6", title: "Schedule next gynaecology follow-up", related: "Asha Verma", priority: "High", assigned: "Front Desk", due: "Next week", bucket: "Upcoming", type: "follow-up" },
    ],
    tickets: [
      { id: "#3042", subject: "Patient wants to reschedule", customer: "Asha Verma", status: "Open", priority: "Medium", assigned: "Front Desk", timeOpen: "1h" },
      { id: "#3048", subject: "Prescription copy requested", customer: "Sunita Patel", status: "In Progress", priority: "Low", assigned: "Care Team", timeOpen: "5h" },
      { id: "#3051", subject: "Long wait time complaint", customer: "Ramesh Gupta", status: "Escalated", priority: "High", assigned: "Clinic Admin", timeOpen: "2h" },
      { id: "#3056", subject: "Directions message failed", customer: "Arun Kumar", status: "Resolved", priority: "Medium", assigned: "Front Desk", timeOpen: "1d" },
    ],
    workflows: [
      { id: "hcw-1", name: "Appointment confirmation", active: true, trigger: "New appointment request", condition: "Slot available", action: "Confirm slot and send WhatsApp with directions", runCount: 53 },
      { id: "hcw-2", name: "One-hour reminder", active: true, trigger: "Appointment in 1 hour", condition: "Patient not checked in", action: "Send reminder WhatsApp", runCount: 87 },
      { id: "hcw-3", name: "Visit feedback", active: true, trigger: "Visit completed", condition: "No feedback submitted", action: "Send feedback form and schedule follow-up if required", runCount: 44 },
    ],
    activityFeed: [
      { id: "hca-1", text: "Appointment confirmed for Priya Nair", timestamp: "6 min ago", initials: "FD" },
      { id: "hca-2", text: "AI flagged Megha as urgent paediatrics follow-up", timestamp: "18 min ago", initials: "AI" },
      { id: "hca-3", text: "WhatsApp reminder sent to Arun Kumar", timestamp: "34 min ago", initials: "WA" },
      { id: "hca-4", text: "Sunita Patel moved to Treatment Ongoing", timestamp: "1h ago", initials: "DJ" },
      { id: "hca-5", text: "Clinic admin reviewed wait-time alert", timestamp: "2h ago", initials: "CA" },
      { id: "hca-6", text: "Feedback form sent to 7 patients", timestamp: "Yesterday", initials: "CF" },
    ],
    aiInsights: [
      "WhatsApp reminders reduced no-shows by 3% this week",
      "Cardio appointments have the highest revenue per visit",
      "Two high-priority patients need confirmation in the next hour",
      "Average wait time can improve by shifting one slot from Ortho to ENT",
    ],
    aiChatQA: [
      { question: "Which appointments need action now?", answer: "Priya Nair and Arun Kumar need confirmation first. Both are new high-priority requests and have open slots available today.", followUps: ["Send WhatsApp", "Show tasks"] },
      { question: "How many follow-ups are due?", answer: "You have 12 follow-ups due. The most urgent are Asha Verma and Sunita Patel because both are linked to ongoing treatment.", followUps: ["Create tasks", "Open pipeline"] },
      { question: "What is today's revenue?", answer: "Today's recorded revenue is Rs. 42,000, with Cardio and Dental contributing the highest share.", followUps: ["Open reports", "Show doctors"] },
      { question: "Which doctor is busiest?", answer: "Dr. Sharma has the highest appointment load today. Shift one non-urgent ENT request to tomorrow to keep wait time under 20 minutes.", followUps: ["Switch role", "Show queue"] },
      { question: "Write an appointment confirmation", answer: "Hi, your appointment is confirmed for today. Please arrive 10 minutes early and use the map link shared here.", followUps: ["Send message", "Edit template"] },
    ],
    reportsData: {
      leadSources: [
        { label: "Website", value: 28, color: "#2563eb" },
        { label: "WhatsApp", value: 26, color: "#16a34a" },
        { label: "Referral", value: 24, color: "#f59e0b" },
        { label: "Walk-in", value: 14, color: "#64748b" },
        { label: "JustDial", value: 6, color: "#0ea5e9" },
        { label: "Facebook", value: 2, color: "#4f46e5" },
      ],
      funnel: [
        { stage: "Request", count: 78, dropoff: 0 },
        { stage: "Confirmed", count: 62, dropoff: 21 },
        { stage: "Visited", count: 52, dropoff: 16 },
        { stage: "Treatment", count: 24, dropoff: 54 },
        { stage: "Follow-up", count: 18, dropoff: 25 },
      ],
      team: [
        { name: "Dr. Sharma", assigned: 24, closed: 16 },
        { name: "Dr. Mehta", assigned: 18, closed: 13 },
        { name: "Dr. Rao", assigned: 15, closed: 9 },
        { name: "Front Desk", assigned: 34, closed: 28 },
      ],
      revenue: [
        { month: "Nov", value: 760000 },
        { month: "Dec", value: 810000 },
        { month: "Jan", value: 790000 },
        { month: "Feb", value: 860000 },
        { month: "Mar", value: 910000 },
        { month: "Apr", value: 980000 },
      ],
    },
    roiDefaults: { teamSize: 6, leadsPerMonth: 420, avgDealValue: 3200, manualHours: 7, lostDeals: 18 },
    blueprintSummary: {
      modules: ["Appointment requests", "Patient records", "Doctor calendar", "Follow-up tasks", "Feedback forms", "Revenue reports"],
      automations: ["Slot confirmation WhatsApp", "One-hour appointment reminder", "Post-visit feedback and follow-up"],
      roles: ["Business Owner", "Admin", "Manager", "Sales User", "Operations User"],
      timeline: "3-4 weeks",
      onboarding: "3 days",
    },
    notifications: [
      { id: "hcn-1", text: "2 high-priority appointment requests need confirmation" },
      { id: "hcn-2", text: "No-show rate improved by 3%" },
      { id: "hcn-3", text: "One wait-time complaint needs admin review" },
    ],
    whatsappTemplate: "Hi {{name}}, your appointment is confirmed. Please arrive 10 minutes early. We have also shared directions for your visit.",
    testimonial: {
      quote: "Our clinic front desk now confirms appointments and follow-ups without scattered phone notes.",
      author: "Dr. Mehta",
      company: "CityCare Clinic",
    },
  }),

  "real-estate": build({
    key: "real-estate",
    name: "Real Estate CRM",
    tagline: "For builders, agents, and property consultants",
    description: "For builders, agents, and property consultants",
    icon: "realEstate",
    welcomeMessage: "Here's your Real Estate CRM - tracking every site visit, follow-up, and booking.",
    kpis: [
      { label: "Active Enquiries", value: "142", change: "+18%", trend: "up", sparkline: spark.up },
      { label: "Site Visits Booked", value: "38", change: "+9%", trend: "up", sparkline: spark.up },
      { label: "Revenue Pipeline", value: "Rs. 4.8 Cr", change: "+22%", trend: "up", sparkline: spark.up },
      { label: "Follow-ups Pending", value: "24", change: "-6%", trend: "down", sparkline: spark.down },
      { label: "Deals Closed", value: "11", change: "+4", trend: "up", sparkline: spark.up },
      { label: "Conversion Rate", value: "31%", change: "+3%", trend: "up", sparkline: spark.up },
      { label: "Automations Active", value: "9", change: "+2", trend: "up", sparkline: spark.up },
      { label: "Team Members", value: "8", change: "Live", trend: "neutral", sparkline: spark.neutral },
    ],
    leads: [
      lead("re-1", "Rajesh Sharma", "2BHK Tower B", "Website", "Hot", 92, "Priya", "Rs. 85L", 8500000, "2BHK apartment", "Today"),
      lead("re-2", "Anita Patel", "Premium Villa", "Facebook", "Warm", 74, "Rohan", "Rs. 1.2 Cr", 12000000, "Villa enquiry"),
      lead("re-3", "Suresh Kumar", "Budget Flat", "Walk-in", "Cold", 41, "Priya", "Rs. 45L", 4500000, "1BHK apartment"),
      lead("re-4", "Meena Joshi", "Luxury Floor", "Referral", "Hot", 88, "Amit", "Rs. 2.1 Cr", 21000000, "Luxury floor"),
      lead("re-5", "Vikas Malhotra", "3BHK Tower A", "WhatsApp", "Warm", 67, "Rohan", "Rs. 72L", 7200000, "3BHK apartment"),
      lead("re-6", "Deepa Singh", "2BHK Tower C", "JustDial", "New", 55, "Unassigned", "Rs. 60L", 6000000, "2BHK apartment"),
      lead("re-7", "Karan Verma", "Penthouse", "Instagram", "Hot", 79, "Amit", "Rs. 1.5 Cr", 15000000, "Penthouse"),
      lead("re-8", "Pooja Nair", "Garden Flat", "Referral", "Warm", 71, "Priya", "Rs. 95L", 9500000, "Garden-facing flat"),
    ],
    pipelineStages: ["New Enquiry", "Site Visit Scheduled", "Site Visit Done", "Negotiation", "Booking Confirmed"],
    pipelineDeals: {
      "New Enquiry": [deal("red-1", "re-6", "Deepa Singh", "Rs. 60L", 6000000, "Unassigned", 1, "Medium")],
      "Site Visit Scheduled": [deal("red-2", "re-1", "Rajesh Sharma", "Rs. 85L", 8500000, "Priya", 2, "High"), deal("red-3", "re-5", "Vikas Malhotra", "Rs. 72L", 7200000, "Rohan", 4, "Medium")],
      "Site Visit Done": [deal("red-4", "re-8", "Pooja Nair", "Rs. 95L", 9500000, "Priya", 3, "Medium"), deal("red-5", "re-3", "Suresh Kumar", "Rs. 45L", 4500000, "Priya", 7, "Low")],
      Negotiation: [deal("red-6", "re-2", "Anita Patel", "Rs. 1.2 Cr", 12000000, "Rohan", 5, "Medium"), deal("red-7", "re-4", "Meena Joshi", "Rs. 2.1 Cr", 21000000, "Amit", 2, "High")],
      "Booking Confirmed": [deal("red-8", "re-7", "Karan Verma", "Rs. 1.5 Cr", 15000000, "Amit", 1, "High")],
    },
    tasks: [
      { id: "ret-1", title: "Call Rajesh Sharma - site visit follow-up", related: "Rajesh Sharma", priority: "High", assigned: "Priya", due: "Today", bucket: "Due Today", type: "follow-up" },
      { id: "ret-2", title: "Send floor plan brochure to Anita Patel", related: "Anita Patel", priority: "Medium", assigned: "Rohan", due: "Today", bucket: "Due Today", type: "document" },
      { id: "ret-3", title: "Schedule negotiation meeting", related: "Meena Joshi", priority: "High", assigned: "Amit", due: "Tomorrow", bucket: "Due This Week", type: "follow-up" },
      { id: "ret-4", title: "Update payment plan for Karan Verma", related: "Karan Verma", priority: "Medium", assigned: "Amit", due: "2 days", bucket: "Due This Week", type: "payment" },
      { id: "ret-5", title: "WhatsApp check-in", related: "Vikas Malhotra", priority: "Low", assigned: "Rohan", due: "Today", bucket: "Due Today", type: "follow-up" },
      { id: "ret-6", title: "Manager alert: Suresh follow-up overdue", related: "Suresh Kumar", priority: "High", assigned: "Priya", due: "3 days overdue", bucket: "Overdue", type: "follow-up" },
    ],
    tickets: [
      { id: "#4042", subject: "Requested revised payment plan", customer: "Karan Verma", status: "Open", priority: "Medium", assigned: "Amit", timeOpen: "2h" },
      { id: "#4049", subject: "Site visit reschedule", customer: "Rajesh Sharma", status: "In Progress", priority: "High", assigned: "Priya", timeOpen: "1h" },
      { id: "#4050", subject: "Brochure download issue", customer: "Anita Patel", status: "Resolved", priority: "Low", assigned: "Rohan", timeOpen: "1d" },
      { id: "#4055", subject: "Delayed follow-up complaint", customer: "Suresh Kumar", status: "Escalated", priority: "High", assigned: "Manager", timeOpen: "3d" },
    ],
    workflows: [
      { id: "rew-1", name: "New web enquiry", active: true, trigger: "New web enquiry", condition: "Agent available", action: "Auto-assign and send WhatsApp welcome plus brochure", runCount: 47 },
      { id: "rew-2", name: "Site visit no follow-up", active: true, trigger: "Site visit done", condition: "No follow-up in 48 hours", action: "Alert manager and remind agent", runCount: 18 },
      { id: "rew-3", name: "Booking confirmation", active: true, trigger: "Deal moves to Booking", condition: "Payment plan selected", action: "Generate payment schedule and send confirmation", runCount: 11 },
    ],
    activityFeed: [
      { id: "rea-1", text: "Priya booked a site visit for Rajesh Sharma - 2BHK Tower B", timestamp: "5 min ago", initials: "PS" },
      { id: "rea-2", text: "AI scored Meena Joshi as Hot (Rs. 2.1 Cr deal)", timestamp: "18 min ago", initials: "AI" },
      { id: "rea-3", text: "Rohan moved Anita Patel to Negotiation stage", timestamp: "41 min ago", initials: "RK" },
      { id: "rea-4", text: "WhatsApp brochure auto-sent to 3 new enquiries", timestamp: "1h ago", initials: "WA" },
      { id: "rea-5", text: "Karan Verma deal moved to Booking Confirmed", timestamp: "2h ago", initials: "AV" },
      { id: "rea-6", text: "Manager alert: Suresh Kumar follow-up overdue by 3 days", timestamp: "Today", initials: "MG" },
    ],
    aiInsights: [
      "Referral leads are converting 2.3x better than Facebook leads",
      "4 deals in Negotiation stage need follow-up in the next 24 hours",
      "Site visit to booking conversion rate dropped 8% this month - review pricing",
      "Tuesday and Thursday are your best days for site visits",
    ],
    aiChatQA: [
      { question: "Which leads should I contact today?", answer: "Rajesh Sharma and Meena Joshi are your highest priority. Both are hot, high-value leads and have not been contacted in 2+ days.", followUps: ["Call Rajesh", "Open hot leads"] },
      { question: "What's my pipeline worth?", answer: "Your current pipeline is valued at Rs. 4.8 Crore across 38 active deals. 11 deals are in final stages.", followUps: ["Open pipeline", "Show final stages"] },
      { question: "Which source gives best leads?", answer: "Referrals are your best channel at 31% conversion, compared with 12% from Facebook Ads.", followUps: ["Filter referrals", "Show report"] },
      { question: "What automations are running?", answer: "9 automations are active. WhatsApp brochure sender has fired 47 times this month.", followUps: ["Run simulation", "Open workflows"] },
      { question: "Which agent is performing best?", answer: "Priya has the highest conversion rate at 38%. Rohan has the most follow-ups pending.", followUps: ["Switch role", "Show tasks"] },
    ],
    reportsData: {
      leadSources: [
        { label: "Website", value: 24, color: "#2563eb" },
        { label: "WhatsApp", value: 18, color: "#16a34a" },
        { label: "Facebook", value: 20, color: "#4f46e5" },
        { label: "Referral", value: 22, color: "#f59e0b" },
        { label: "Walk-in", value: 8, color: "#64748b" },
        { label: "JustDial", value: 8, color: "#0ea5e9" },
      ],
      funnel: [
        { stage: "Enquiry", count: 142, dropoff: 0 },
        { stage: "Visit Scheduled", count: 62, dropoff: 56 },
        { stage: "Visit Done", count: 38, dropoff: 39 },
        { stage: "Negotiation", count: 19, dropoff: 50 },
        { stage: "Booking", count: 11, dropoff: 42 },
      ],
      team: [
        { name: "Priya", assigned: 42, closed: 16 },
        { name: "Rohan", assigned: 37, closed: 9 },
        { name: "Amit", assigned: 29, closed: 11 },
        { name: "Neha", assigned: 18, closed: 4 },
      ],
      revenue: [
        { month: "Nov", value: 26000000 },
        { month: "Dec", value: 31000000 },
        { month: "Jan", value: 34000000 },
        { month: "Feb", value: 29000000 },
        { month: "Mar", value: 41000000 },
        { month: "Apr", value: 48000000 },
      ],
    },
    roiDefaults: { teamSize: 8, leadsPerMonth: 160, avgDealValue: 8500000, manualHours: 10, lostDeals: 4 },
    blueprintSummary: {
      modules: ["Enquiry capture", "Site visit calendar", "Sales pipeline", "Payment plan tracking", "WhatsApp brochure automation", "Agent performance"],
      automations: ["New enquiry auto-assignment", "48-hour site visit follow-up alert", "Booking payment schedule generation"],
      roles: ["Business Owner", "Admin", "Manager", "Sales User", "Operations User"],
      timeline: "4-6 weeks",
      onboarding: "5 days",
    },
    notifications: [
      { id: "ren-1", text: "AI scored 2 new hot property leads" },
      { id: "ren-2", text: "4 negotiation deals need follow-up today" },
      { id: "ren-3", text: "Suresh Kumar follow-up is overdue by 3 days" },
    ],
    whatsappTemplate: "Hi {{name}}! Following up on your enquiry. Would you be available for a site visit this Saturday? Reply YES to confirm.",
    testimonial: {
      quote: "HNX built our Real Estate CRM in 3 weeks. We track every site visit and follow-up without spreadsheets.",
      author: "Suresh",
      company: "XYZ Realty, Ludhiana",
    },
  }),

  pharma: build({
    key: "pharma",
    name: "Pharma / Inventory CRM",
    tagline: "For distributors, wholesalers, billing teams",
    description: "For distributors, wholesalers, billing teams",
    icon: "pharma",
    welcomeMessage: "Here's your Pharma CRM - joining stock, orders, billing, follow-ups, and distributor performance.",
    kpis: [
      { label: "Active Orders", value: "96", change: "+14%", trend: "up", sparkline: spark.up },
      { label: "Low Stock Items", value: "18", change: "-5", trend: "down", sparkline: spark.down },
      { label: "Monthly Billing", value: "Rs. 72L", change: "+16%", trend: "up", sparkline: spark.up },
      { label: "Pending Collections", value: "Rs. 9.8L", change: "-8%", trend: "down", sparkline: spark.down },
      { label: "Distributor Leads", value: "42", change: "+7", trend: "up", sparkline: spark.up },
      { label: "Order Conversion", value: "36%", change: "+4%", trend: "up", sparkline: spark.up },
      { label: "Automations Active", value: "7", change: "+1", trend: "up", sparkline: spark.up },
      { label: "Billing Users", value: "12", change: "Live", trend: "neutral", sparkline: spark.neutral },
    ],
    leads: [
      lead("ph-1", "Medico Traders", "Distributor", "IndiaMART", "Hot", 90, "Rakesh", "Rs. 8.2L", 820000, "Monthly supply order", "Today"),
      lead("ph-2", "CarePlus Pharmacy", "Retail Chain", "WhatsApp", "Warm", 73, "Neha", "Rs. 3.6L", 360000, "Cardio stock order"),
      lead("ph-3", "City Hospital Store", "Hospital", "Referral", "Hot", 86, "Rakesh", "Rs. 12L", 1200000, "Bulk hospital supplies"),
      lead("ph-4", "Wellness Depot", "Wholesaler", "Website", "Warm", 66, "Imran", "Rs. 4.4L", 440000, "OTC medicines"),
      lead("ph-5", "Apollo Lane", "Retailer", "Walk-in", "Cold", 40, "Neha", "Rs. 1.1L", 110000, "Seasonal stock"),
      lead("ph-6", "NorthMed", "Distributor", "Referral", "Hot", 82, "Imran", "Rs. 7.5L", 750000, "Expansion stock"),
      lead("ph-7", "HealthKart Local", "Retailer", "Website", "New", 54, "Unassigned", "Rs. 95K", 95000, "Trial order"),
      lead("ph-8", "Prime Surgical", "Supplier", "WhatsApp", "Warm", 70, "Rakesh", "Rs. 5.8L", 580000, "Surgical inventory"),
    ],
    pipelineStages: ["New Inquiry", "Stock Check", "Quotation Sent", "Order Confirmed", "Billed"],
    pipelineDeals: {
      "New Inquiry": [deal("phd-1", "ph-7", "HealthKart Local", "Rs. 95K", 95000, "Unassigned", 1, "Low")],
      "Stock Check": [deal("phd-2", "ph-2", "CarePlus Pharmacy", "Rs. 3.6L", 360000, "Neha", 3, "Medium")],
      "Quotation Sent": [deal("phd-3", "ph-4", "Wellness Depot", "Rs. 4.4L", 440000, "Imran", 4, "Medium"), deal("phd-4", "ph-8", "Prime Surgical", "Rs. 5.8L", 580000, "Rakesh", 2, "Medium")],
      "Order Confirmed": [deal("phd-5", "ph-1", "Medico Traders", "Rs. 8.2L", 820000, "Rakesh", 1, "High"), deal("phd-6", "ph-3", "City Hospital Store", "Rs. 12L", 1200000, "Rakesh", 2, "High")],
      Billed: [deal("phd-7", "ph-6", "NorthMed", "Rs. 7.5L", 750000, "Imran", 1, "High")],
    },
    tasks: [
      { id: "pht-1", title: "Confirm stock for Medico Traders", related: "Medico Traders", priority: "High", assigned: "Rakesh", due: "Today", bucket: "Due Today", type: "follow-up" },
      { id: "pht-2", title: "Send revised quotation to Prime Surgical", related: "Prime Surgical", priority: "Medium", assigned: "Rakesh", due: "Today", bucket: "Due Today", type: "document" },
      { id: "pht-3", title: "Collection follow-up for NorthMed", related: "NorthMed", priority: "High", assigned: "Accounts", due: "Yesterday", bucket: "Overdue", type: "payment" },
      { id: "pht-4", title: "Reorder low-stock cardiac items", related: "Inventory", priority: "High", assigned: "Inventory", due: "Tomorrow", bucket: "Due This Week", type: "internal" },
      { id: "pht-5", title: "Verify hospital GST details", related: "City Hospital Store", priority: "Medium", assigned: "Billing", due: "Friday", bucket: "Due This Week", type: "document" },
      { id: "pht-6", title: "Nurture trial order lead", related: "HealthKart Local", priority: "Low", assigned: "Neha", due: "Next week", bucket: "Upcoming", type: "follow-up" },
    ],
    tickets: [
      { id: "#5042", subject: "Invoice mismatch", customer: "NorthMed", status: "Open", priority: "High", assigned: "Billing", timeOpen: "4h" },
      { id: "#5048", subject: "Batch expiry clarification", customer: "CarePlus Pharmacy", status: "In Progress", priority: "Medium", assigned: "Inventory", timeOpen: "7h" },
      { id: "#5051", subject: "Delayed dispatch", customer: "Medico Traders", status: "Escalated", priority: "High", assigned: "Dispatch", timeOpen: "1d" },
      { id: "#5055", subject: "Credit note requested", customer: "Prime Surgical", status: "Resolved", priority: "Low", assigned: "Accounts", timeOpen: "2d" },
    ],
    workflows: [
      { id: "phw-1", name: "Low stock alert", active: true, trigger: "Stock below threshold", condition: "Fast-moving SKU", action: "Notify purchase and sales owner", runCount: 76 },
      { id: "phw-2", name: "Order billing sync", active: true, trigger: "Order confirmed", condition: "GST and stock verified", action: "Create bill and reduce inventory", runCount: 55 },
      { id: "phw-3", name: "Collection reminder", active: true, trigger: "Payment due", condition: "Invoice open after 7 days", action: "Send WhatsApp and alert accounts", runCount: 33 },
    ],
    activityFeed: [
      { id: "pha-1", text: "Medico Traders order confirmed", timestamp: "8 min ago", initials: "RT" },
      { id: "pha-2", text: "AI flagged 18 low-stock items", timestamp: "23 min ago", initials: "AI" },
      { id: "pha-3", text: "Billing synced City Hospital order", timestamp: "1h ago", initials: "BL" },
      { id: "pha-4", text: "Collection reminder sent to NorthMed", timestamp: "2h ago", initials: "AC" },
      { id: "pha-5", text: "Prime Surgical quotation updated", timestamp: "3h ago", initials: "RT" },
      { id: "pha-6", text: "Inventory threshold changed for cardio SKUs", timestamp: "Yesterday", initials: "IN" },
    ],
    aiInsights: [
      "Cardio SKUs will hit low stock in 5 days at current order speed",
      "Collections workflow can recover Rs. 4.2L this week",
      "Hospital orders have higher value but slower billing verification",
      "Rakesh owns 62% of high-value distributor deals",
    ],
    aiChatQA: [
      { question: "Which orders need billing today?", answer: "Medico Traders and City Hospital Store are ready for billing after stock verification. NorthMed needs collection follow-up first.", followUps: ["Open tasks", "Run billing workflow"] },
      { question: "Which items are low stock?", answer: "18 items are below threshold, with cardiac and surgical SKUs most urgent. Create purchase tasks today.", followUps: ["Create task", "Show inventory"] },
      { question: "What is pending collection?", answer: "Pending collection is Rs. 9.8L. NorthMed is the highest-priority account because invoice age crossed 7 days.", followUps: ["Send WhatsApp", "Open tickets"] },
      { question: "Which distributor is highest value?", answer: "City Hospital Store has the largest active order at Rs. 12L, followed by Medico Traders at Rs. 8.2L.", followUps: ["Open pipeline", "Show report"] },
      { question: "What automation should run next?", answer: "Run Order Billing Sync after GST and stock verification. It will create the bill and update inventory automatically.", followUps: ["Run simulation", "Show workflow"] },
    ],
    reportsData: {
      leadSources: [
        { label: "IndiaMART", value: 30, color: "#2563eb" },
        { label: "WhatsApp", value: 20, color: "#16a34a" },
        { label: "Referral", value: 22, color: "#f59e0b" },
        { label: "Website", value: 16, color: "#4f46e5" },
        { label: "Walk-in", value: 8, color: "#64748b" },
        { label: "Distributor", value: 4, color: "#0ea5e9" },
      ],
      funnel: [
        { stage: "Inquiry", count: 96, dropoff: 0 },
        { stage: "Stock Check", count: 70, dropoff: 27 },
        { stage: "Quote", count: 51, dropoff: 27 },
        { stage: "Order", count: 34, dropoff: 33 },
        { stage: "Billed", count: 27, dropoff: 21 },
      ],
      team: [
        { name: "Rakesh", assigned: 34, closed: 15 },
        { name: "Neha", assigned: 26, closed: 8 },
        { name: "Imran", assigned: 24, closed: 9 },
        { name: "Billing", assigned: 18, closed: 13 },
      ],
      revenue: [
        { month: "Nov", value: 5200000 },
        { month: "Dec", value: 5900000 },
        { month: "Jan", value: 6100000 },
        { month: "Feb", value: 6400000 },
        { month: "Mar", value: 6900000 },
        { month: "Apr", value: 7200000 },
      ],
    },
    roiDefaults: { teamSize: 12, leadsPerMonth: 260, avgDealValue: 420000, manualHours: 11, lostDeals: 6 },
    blueprintSummary: {
      modules: ["Distributor leads", "Order pipeline", "Inventory threshold alerts", "Billing sync", "Collection reminders", "Dispatch tracking"],
      automations: ["Low-stock alert", "Order-to-bill inventory update", "Payment collection reminders"],
      roles: ["Business Owner", "Admin", "Manager", "Sales User", "Operations User"],
      timeline: "5-7 weeks",
      onboarding: "6 days",
    },
    notifications: [
      { id: "phn-1", text: "18 low-stock SKUs need action" },
      { id: "phn-2", text: "Two high-value orders are ready for billing" },
      { id: "phn-3", text: "Collection reminder workflow ran 6 times today" },
    ],
    whatsappTemplate: "Hi {{name}}, your stock quotation is ready. Please confirm quantities so we can reserve stock and generate the bill.",
    testimonial: {
      quote: "Our billing team can see stock, orders, and collections without switching between sheets.",
      author: "Rakesh",
      company: "Medico Traders",
    },
  }),

  events: build({
    key: "events",
    name: "Events & Ticketing CRM",
    tagline: "For venues, organizers, entertainment companies",
    description: "For venues, organizers, entertainment companies",
    icon: "events",
    welcomeMessage: "Here's your Events CRM - connecting event inquiries, ticket sales, vendors, guests, and support.",
    kpis: [
      { label: "Upcoming Events", value: "12", change: "+4", trend: "up", sparkline: spark.up },
      { label: "Tickets Sold", value: "4,820", change: "+19%", trend: "up", sparkline: spark.up },
      { label: "Revenue Pipeline", value: "Rs. 18.9L", change: "+24%", trend: "up", sparkline: spark.up },
      { label: "Vendor Tasks", value: "31", change: "-8%", trend: "down", sparkline: spark.down },
      { label: "Open Guest Issues", value: "17", change: "-5", trend: "down", sparkline: spark.down },
      { label: "Occupancy", value: "74%", change: "+7%", trend: "up", sparkline: spark.up },
      { label: "Automations Active", value: "8", change: "+2", trend: "up", sparkline: spark.up },
      { label: "Team Members", value: "14", change: "Live", trend: "neutral", sparkline: spark.neutral },
    ],
    leads: [
      lead("ev-1", "Jazz Night", "Venue Event", "Website", "Hot", 91, "Tara", "Rs. 5.2L", 520000, "Concert booking", "Today"),
      lead("ev-2", "Indie Friday", "Ticketed Show", "Instagram", "Warm", 72, "Kabir", "Rs. 3.1L", 310000, "Ticket sales campaign"),
      lead("ev-3", "Corporate Gig", "Brand Event", "Referral", "Hot", 86, "Tara", "Rs. 4.0L", 400000, "Corporate event"),
      lead("ev-4", "Comedy Evening", "Venue Show", "District", "Warm", 68, "Aman", "Rs. 2.2L", 220000, "Comedy event"),
      lead("ev-5", "Food Fest", "Outdoor Event", "Facebook", "New", 59, "Kabir", "Rs. 6.5L", 650000, "Festival booking"),
      lead("ev-6", "DJ Saturday", "Nightlife", "WhatsApp", "Hot", 83, "Tara", "Rs. 2.8L", 280000, "Club event"),
      lead("ev-7", "Art Walk", "Community Event", "Walk-in", "Cold", 40, "Unassigned", "Rs. 90K", 90000, "Gallery event"),
      lead("ev-8", "Startup Mixer", "Networking", "LinkedIn", "Warm", 76, "Aman", "Rs. 1.7L", 170000, "Networking event"),
    ],
    pipelineStages: ["Inquiry", "Proposal", "Vendor Planning", "Ticket Live", "Event Completed"],
    pipelineDeals: {
      Inquiry: [deal("evd-1", "ev-7", "Art Walk", "Rs. 90K", 90000, "Unassigned", 1, "Low")],
      Proposal: [deal("evd-2", "ev-5", "Food Fest", "Rs. 6.5L", 650000, "Kabir", 2, "Medium"), deal("evd-3", "ev-8", "Startup Mixer", "Rs. 1.7L", 170000, "Aman", 2, "Medium")],
      "Vendor Planning": [deal("evd-4", "ev-3", "Corporate Gig", "Rs. 4.0L", 400000, "Tara", 4, "High")],
      "Ticket Live": [deal("evd-5", "ev-1", "Jazz Night", "Rs. 5.2L", 520000, "Tara", 3, "High"), deal("evd-6", "ev-2", "Indie Friday", "Rs. 3.1L", 310000, "Kabir", 6, "Medium")],
      "Event Completed": [deal("evd-7", "ev-6", "DJ Saturday", "Rs. 2.8L", 280000, "Tara", 1, "High")],
    },
    tasks: [
      { id: "evt-1", title: "Push final ticket campaign for Indie Friday", related: "Indie Friday", priority: "High", assigned: "Kabir", due: "Today", bucket: "Due Today", type: "follow-up" },
      { id: "evt-2", title: "Confirm vendor checklist for Corporate Gig", related: "Corporate Gig", priority: "High", assigned: "Aman", due: "Today", bucket: "Due Today", type: "internal" },
      { id: "evt-3", title: "Send sponsor proposal for Food Fest", related: "Food Fest", priority: "Medium", assigned: "Kabir", due: "Tomorrow", bucket: "Due This Week", type: "document" },
      { id: "evt-4", title: "Resolve guest refund issue", related: "Jazz Night", priority: "Medium", assigned: "Support", due: "Yesterday", bucket: "Overdue", type: "support" },
      { id: "evt-5", title: "Prepare event summary for DJ Saturday", related: "DJ Saturday", priority: "Low", assigned: "Finance", due: "Friday", bucket: "Due This Week", type: "document" },
      { id: "evt-6", title: "Nurture Art Walk enquiry", related: "Art Walk", priority: "Low", assigned: "Aman", due: "Next week", bucket: "Upcoming", type: "follow-up" },
    ],
    tickets: [
      { id: "#6042", subject: "Refund request", customer: "Jazz Night Guest", status: "Open", priority: "Medium", assigned: "Support", timeOpen: "2h" },
      { id: "#6048", subject: "Ticket QR not working", customer: "Indie Friday Guest", status: "In Progress", priority: "High", assigned: "Ticketing", timeOpen: "1h" },
      { id: "#6051", subject: "Vendor arrival delayed", customer: "Corporate Gig", status: "Escalated", priority: "High", assigned: "Aman", timeOpen: "4h" },
      { id: "#6056", subject: "Guest list update", customer: "DJ Saturday", status: "Resolved", priority: "Low", assigned: "Tara", timeOpen: "1d" },
    ],
    workflows: [
      { id: "evw-1", name: "Ticket platform sync", active: true, trigger: "Ticket sale on platform", condition: "Event is live", action: "Update CRM ticket count and revenue", runCount: 138 },
      { id: "evw-2", name: "Event reminder broadcast", active: true, trigger: "Event starts in 24 hours", condition: "Ticket holder opted in", action: "Send WhatsApp reminder with venue details", runCount: 91 },
      { id: "evw-3", name: "Vendor task escalation", active: false, trigger: "Vendor task overdue", condition: "Event starts within 48 hours", action: "Alert event manager and owner", runCount: 16 },
    ],
    activityFeed: [
      { id: "eva-1", text: "Ticket sync added 126 Jazz Night sales", timestamp: "9 min ago", initials: "TK" },
      { id: "eva-2", text: "AI flagged Indie Friday for marketing push", timestamp: "25 min ago", initials: "AI" },
      { id: "eva-3", text: "Vendor checklist updated for Corporate Gig", timestamp: "1h ago", initials: "AM" },
      { id: "eva-4", text: "WhatsApp reminder sent to 900 ticket holders", timestamp: "2h ago", initials: "WA" },
      { id: "eva-5", text: "Support resolved DJ Saturday guest list update", timestamp: "3h ago", initials: "SP" },
      { id: "eva-6", text: "Food Fest moved to Proposal stage", timestamp: "Yesterday", initials: "KB" },
    ],
    aiInsights: [
      "Indie Friday needs a final 48-hour marketing push",
      "Skillbox is the top-performing ticket source this month",
      "Vendor delays could affect Corporate Gig setup",
      "Jazz Night can hit 90% occupancy with one WhatsApp broadcast",
    ],
    aiChatQA: [
      { question: "Which event needs marketing push?", answer: "Indie Friday needs the strongest push because occupancy is below target and the event is close. Use Instagram retargeting plus WhatsApp broadcast.", followUps: ["Create campaign", "Open reports"] },
      { question: "Which platform sold most tickets?", answer: "Skillbox leads ticket revenue for Jazz Night, while District is stronger for comedy and premium ticket categories.", followUps: ["Filter source", "Show chart"] },
      { question: "Summarize ticket revenue", answer: "Ticket revenue is Rs. 18.9L across active events. Jazz Night is ahead of target; Indie Friday needs action.", followUps: ["Open reports", "Show pipeline"] },
      { question: "Which vendor tasks are risky?", answer: "Corporate Gig has the highest vendor risk because setup starts within 48 hours and two checklist tasks are delayed.", followUps: ["Open tasks", "Run escalation"] },
      { question: "Write promotion message", answer: "Indie Friday is almost here. Limited seats remain for a live music night. Book now before the final release closes.", followUps: ["Send WhatsApp", "Edit copy"] },
    ],
    reportsData: {
      leadSources: [
        { label: "Website", value: 20, color: "#2563eb" },
        { label: "WhatsApp", value: 16, color: "#16a34a" },
        { label: "Instagram", value: 24, color: "#4f46e5" },
        { label: "Referral", value: 18, color: "#f59e0b" },
        { label: "Walk-in", value: 4, color: "#64748b" },
        { label: "District", value: 18, color: "#0ea5e9" },
      ],
      funnel: [
        { stage: "Inquiry", count: 68, dropoff: 0 },
        { stage: "Proposal", count: 41, dropoff: 40 },
        { stage: "Planning", count: 29, dropoff: 29 },
        { stage: "Ticket Live", count: 18, dropoff: 38 },
        { stage: "Completed", count: 12, dropoff: 33 },
      ],
      team: [
        { name: "Tara", assigned: 28, closed: 12 },
        { name: "Kabir", assigned: 31, closed: 8 },
        { name: "Aman", assigned: 22, closed: 6 },
        { name: "Support", assigned: 17, closed: 11 },
      ],
      revenue: [
        { month: "Nov", value: 950000 },
        { month: "Dec", value: 1120000 },
        { month: "Jan", value: 1280000 },
        { month: "Feb", value: 1190000 },
        { month: "Mar", value: 1560000 },
        { month: "Apr", value: 1890000 },
      ],
    },
    roiDefaults: { teamSize: 14, leadsPerMonth: 180, avgDealValue: 280000, manualHours: 9, lostDeals: 7 },
    blueprintSummary: {
      modules: ["Event pipeline", "Ticket platform sync", "Vendor tasks", "Guest support", "Sponsor tracking", "Event revenue reports"],
      automations: ["Ticket sale sync", "24-hour attendee reminder", "Vendor delay escalation"],
      roles: ["Business Owner", "Admin", "Manager", "Sales User", "Operations User"],
      timeline: "4-6 weeks",
      onboarding: "5 days",
    },
    notifications: [
      { id: "evn-1", text: "Indie Friday occupancy is behind target" },
      { id: "evn-2", text: "126 ticket sales synced from platforms" },
      { id: "evn-3", text: "One vendor task is near escalation" },
    ],
    whatsappTemplate: "Hi {{name}}, your event update is ready. Tickets and venue details are live. Reply YES if you want the final plan shared.",
    testimonial: {
      quote: "Our venue CRM connects ticket sales, vendors, guests, and post-event reports in one place.",
      author: "Tara",
      company: "LiveHouse Events",
    },
  }),

  "it-saas": build({
    key: "it-saas",
    name: "IT & SaaS CRM",
    tagline: "For software companies, product teams, SaaS startups",
    description: "For software companies, product teams, SaaS startups",
    icon: "saas",
    welcomeMessage: "Here's your IT & SaaS CRM - tracking trials, demos, proposals, onboarding, support, and MRR.",
    kpis: [
      { label: "MRR", value: "Rs. 3.8L", change: "+16%", trend: "up", sparkline: spark.up },
      { label: "Active Trials", value: "24", change: "+6", trend: "up", sparkline: spark.up },
      { label: "Demos This Week", value: "11", change: "+3", trend: "up", sparkline: spark.up },
      { label: "Churn Rate", value: "3.2%", change: "-0.8%", trend: "down", sparkline: spark.down },
      { label: "Deals in Pipeline", value: "18", change: "+4", trend: "up", sparkline: spark.up },
      { label: "Avg Deal Size", value: "Rs. 42K", change: "+9%", trend: "up", sparkline: spark.up },
      { label: "Win Rate", value: "34%", change: "+4%", trend: "up", sparkline: spark.up },
      { label: "Team", value: "6", change: "Live", trend: "neutral", sparkline: spark.neutral },
    ],
    leads: [
      lead("sa-1", "Novakos Pvt Ltd", "Vikram Shah", "Inbound", "Hot", 91, "Rahul", "Rs. 1.2L", 120000, "Enterprise plan", "Today"),
      lead("sa-2", "SaaSWorks", "Priya M", "LinkedIn", "Hot", 88, "Ankit", "Rs. 84K", 84000, "Pro plan"),
      lead("sa-3", "TechBridge", "Suresh K", "Trial", "Warm", 62, "Rahul", "Rs. 28K", 28000, "Starter plan"),
      lead("sa-4", "Elite Events", "Kavya J", "Referral", "Hot", 79, "Ankit", "Rs. 52K", 52000, "Pro plan"),
      lead("sa-5", "CloudKart", "Aman D", "Website", "Warm", 70, "Rahul", "Rs. 42K", 42000, "Team plan"),
      lead("sa-6", "EduStack", "Riya S", "LinkedIn", "Hot", 86, "Nisha", "Rs. 1.6L", 160000, "Enterprise onboarding"),
      lead("sa-7", "RetailOS", "Manav P", "Trial", "Cold", 44, "Nisha", "Rs. 18K", 18000, "Starter trial"),
      lead("sa-8", "FinEdge", "Meera K", "Referral", "Warm", 74, "Ankit", "Rs. 68K", 68000, "Compliance workflow"),
    ],
    pipelineStages: ["Trial Signup", "Demo Scheduled", "Demo Done", "Proposal Sent", "Closed Won"],
    pipelineDeals: {
      "Trial Signup": [deal("sad-1", "sa-3", "TechBridge", "Rs. 28K", 28000, "Rahul", 3, "Medium"), deal("sad-2", "sa-7", "RetailOS", "Rs. 18K", 18000, "Nisha", 6, "Low")],
      "Demo Scheduled": [deal("sad-3", "sa-1", "Novakos Pvt Ltd", "Rs. 1.2L", 120000, "Rahul", 1, "High"), deal("sad-4", "sa-5", "CloudKart", "Rs. 42K", 42000, "Rahul", 2, "Medium")],
      "Demo Done": [deal("sad-5", "sa-2", "SaaSWorks", "Rs. 84K", 84000, "Ankit", 3, "High")],
      "Proposal Sent": [deal("sad-6", "sa-6", "EduStack", "Rs. 1.6L", 160000, "Nisha", 5, "High"), deal("sad-7", "sa-8", "FinEdge", "Rs. 68K", 68000, "Ankit", 4, "Medium")],
      "Closed Won": [deal("sad-8", "sa-4", "Elite Events", "Rs. 52K", 52000, "Ankit", 1, "High")],
    },
    tasks: [
      { id: "sat-1", title: "Prepare enterprise demo for Novakos", related: "Novakos Pvt Ltd", priority: "High", assigned: "Rahul", due: "Today", bucket: "Due Today", type: "internal" },
      { id: "sat-2", title: "Send onboarding proposal to EduStack", related: "EduStack", priority: "High", assigned: "Nisha", due: "Today", bucket: "Due Today", type: "document" },
      { id: "sat-3", title: "Follow up inactive trial", related: "RetailOS", priority: "Medium", assigned: "Nisha", due: "Yesterday", bucket: "Overdue", type: "follow-up" },
      { id: "sat-4", title: "Share API docs with FinEdge", related: "FinEdge", priority: "Medium", assigned: "Ankit", due: "Tomorrow", bucket: "Due This Week", type: "document" },
      { id: "sat-5", title: "Check CloudKart role permissions", related: "CloudKart", priority: "Low", assigned: "Rahul", due: "Friday", bucket: "Due This Week", type: "support" },
      { id: "sat-6", title: "Nurture TechBridge starter trial", related: "TechBridge", priority: "Low", assigned: "Rahul", due: "Next week", bucket: "Upcoming", type: "follow-up" },
    ],
    tickets: [
      { id: "#7042", subject: "Trial login issue", customer: "TechBridge", status: "Open", priority: "High", assigned: "Support", timeOpen: "1h" },
      { id: "#7048", subject: "API docs requested", customer: "FinEdge", status: "In Progress", priority: "Medium", assigned: "Product", timeOpen: "5h" },
      { id: "#7051", subject: "Billing plan clarification", customer: "Elite Events", status: "Resolved", priority: "Low", assigned: "Finance", timeOpen: "1d" },
      { id: "#7055", subject: "Demo recording requested", customer: "SaaSWorks", status: "Open", priority: "Medium", assigned: "Ankit", timeOpen: "3h" },
    ],
    workflows: [
      { id: "saw-1", name: "Demo request assignment", active: true, trigger: "Demo request created", condition: "Company size above 20 users", action: "Assign AE and create discovery task", runCount: 42 },
      { id: "saw-2", name: "Trial activation reminder", active: true, trigger: "Trial user inactive", condition: "No key action for 3 days", action: "Send activation reminder and notify owner", runCount: 35 },
      { id: "saw-3", name: "Renewal follow-up", active: true, trigger: "Renewal approaching", condition: "15 days before renewal", action: "Create renewal follow-up for success team", runCount: 19 },
    ],
    activityFeed: [
      { id: "saa-1", text: "Rahul scheduled enterprise demo for Novakos", timestamp: "12 min ago", initials: "RS" },
      { id: "saa-2", text: "AI scored SaaSWorks as very hot", timestamp: "21 min ago", initials: "AI" },
      { id: "saa-3", text: "Trial activation reminder sent to RetailOS", timestamp: "1h ago", initials: "WA" },
      { id: "saa-4", text: "EduStack proposal moved to final review", timestamp: "2h ago", initials: "NS" },
      { id: "saa-5", text: "CloudKart requested role-based dashboard", timestamp: "3h ago", initials: "CK" },
      { id: "saa-6", text: "FinEdge API documentation task created", timestamp: "Yesterday", initials: "AK" },
    ],
    aiInsights: [
      "Enterprise plan leads are converting 2x faster after technical demos",
      "Inactive trials older than 3 days are your biggest churn risk",
      "Referral-sourced SaaS deals have the highest win rate",
      "EduStack can add Rs. 1.6L MRR if proposal closes this week",
    ],
    aiChatQA: [
      { question: "Which trials are likely to convert?", answer: "Novakos, SaaSWorks, and EduStack are strongest. All have high scores, active stakeholders, and clear expansion needs.", followUps: ["Open leads", "Create tasks"] },
      { question: "Which accounts are churn risk?", answer: "RetailOS is the top churn risk because trial activity dropped and support is open. Send a product activation message today.", followUps: ["Send WhatsApp", "Open tickets"] },
      { question: "Summarize MRR pipeline", answer: "MRR pipeline is Rs. 3.8L with 18 active deals. Proposal Sent holds the highest potential value.", followUps: ["Open reports", "Show pipeline"] },
      { question: "Which source converts best?", answer: "Referral leads have the best win rate, while LinkedIn contributes high-value SaaS founder conversations.", followUps: ["Filter referral", "Show chart"] },
      { question: "Write onboarding message", answer: "Hi, your trial workspace is ready. We have prepared an onboarding checklist so your team can test roles, dashboards, and workflows this week.", followUps: ["Send message", "Edit template"] },
    ],
    reportsData: {
      leadSources: [
        { label: "Inbound", value: 22, color: "#2563eb" },
        { label: "Trial", value: 24, color: "#16a34a" },
        { label: "LinkedIn", value: 23, color: "#4f46e5" },
        { label: "Referral", value: 19, color: "#f59e0b" },
        { label: "Website", value: 8, color: "#64748b" },
        { label: "Partner", value: 4, color: "#0ea5e9" },
      ],
      funnel: [
        { stage: "Trial", count: 58, dropoff: 0 },
        { stage: "Demo", count: 34, dropoff: 41 },
        { stage: "Done", count: 24, dropoff: 29 },
        { stage: "Proposal", count: 18, dropoff: 25 },
        { stage: "Won", count: 9, dropoff: 50 },
      ],
      team: [
        { name: "Rahul", assigned: 24, closed: 8 },
        { name: "Ankit", assigned: 21, closed: 9 },
        { name: "Nisha", assigned: 18, closed: 6 },
        { name: "Support", assigned: 13, closed: 10 },
      ],
      revenue: [
        { month: "Nov", value: 240000 },
        { month: "Dec", value: 270000 },
        { month: "Jan", value: 310000 },
        { month: "Feb", value: 330000 },
        { month: "Mar", value: 350000 },
        { month: "Apr", value: 380000 },
      ],
    },
    roiDefaults: { teamSize: 6, leadsPerMonth: 180, avgDealValue: 42000, manualHours: 8, lostDeals: 5 },
    blueprintSummary: {
      modules: ["Trial signups", "Demo pipeline", "Proposal tracking", "Onboarding checklist", "Support tickets", "MRR dashboard"],
      automations: ["Demo request assignment", "Inactive trial reminders", "Renewal follow-up tasks"],
      roles: ["Business Owner", "Admin", "Manager", "Sales User", "Operations User"],
      timeline: "4-5 weeks",
      onboarding: "4 days",
    },
    notifications: [
      { id: "san-1", text: "RetailOS trial is inactive for 3 days" },
      { id: "san-2", text: "EduStack proposal is ready for founder review" },
      { id: "san-3", text: "Two demos are scheduled today" },
    ],
    whatsappTemplate: "Hi {{name}}, your SaaS demo workspace is ready. We can walk you through roles, dashboards, and workflows this week.",
    testimonial: {
      quote: "HNX gave our sales and success teams one CRM for trials, demos, onboarding, and renewals.",
      author: "Ankit",
      company: "SaaSWorks",
    },
  }),

  "local-services": build({
    key: "local-services",
    name: "Local Services CRM",
    tagline: "For salons, repair services, fitness studios",
    description: "For salons, repair services, fitness studios",
    icon: "local",
    welcomeMessage: "Here's your Local Services CRM - tracking bookings, staff tasks, payments, feedback, and repeat customers.",
    kpis: [
      { label: "Bookings Today", value: "24", change: "+9%", trend: "up", sparkline: spark.up },
      { label: "Pending Calls", value: "8", change: "-3", trend: "down", sparkline: spark.down },
      { label: "Revenue Today", value: "Rs. 18.4K", change: "+12%", trend: "up", sparkline: spark.up },
      { label: "Repeat Clients", value: "67%", change: "+6%", trend: "up", sparkline: spark.up },
      { label: "Avg Rating", value: "4.8", change: "+0.1", trend: "up", sparkline: spark.up },
      { label: "No-shows", value: "2", change: "-1", trend: "down", sparkline: spark.down },
      { label: "Active Staff", value: "6", change: "Live", trend: "neutral", sparkline: spark.neutral },
      { label: "Automations", value: "4", change: "+1", trend: "up", sparkline: spark.up },
    ],
    leads: [
      lead("ls-1", "Anjali Gupta", "AC Repair", "WhatsApp", "Hot", 88, "Rohit", "Rs. 2,400", 2400, "AC service booking", "Today"),
      lead("ls-2", "Manav Singh", "Salon Package", "Instagram", "Warm", 70, "Neha", "Rs. 5,500", 5500, "Weekend grooming package"),
      lead("ls-3", "Priyanka Jain", "Home Cleaning", "Website", "Hot", 84, "CleanPro", "Rs. 8,000", 8000, "Deep cleaning"),
      lead("ls-4", "Arjun Sethi", "Gym Membership", "Walk-in", "Hot", 91, "Aman", "Rs. 24K", 24000, "Personal training"),
      lead("ls-5", "Ritu Bansal", "Spa Booking", "Referral", "Warm", 73, "Neha", "Rs. 3,200", 3200, "Spa appointment"),
      lead("ls-6", "Dev Kapoor", "Laptop Repair", "JustDial", "New", 55, "Rohit", "Rs. 4,500", 4500, "Laptop repair"),
      lead("ls-7", "Kavita Rao", "Fitness Trial", "Facebook", "Cold", 39, "Unassigned", "Rs. 12K", 12000, "Gym trial"),
      lead("ls-8", "Sahil Nanda", "Car Wash", "WhatsApp", "Warm", 68, "Operations", "Rs. 1,800", 1800, "Monthly car wash"),
    ],
    pipelineStages: ["Inquiry", "Appointment", "Service Done", "Follow-up", "Repeat Booking"],
    pipelineDeals: {
      Inquiry: [deal("lsd-1", "ls-7", "Kavita Rao", "Rs. 12K", 12000, "Unassigned", 2, "Low"), deal("lsd-2", "ls-6", "Dev Kapoor", "Rs. 4,500", 4500, "Rohit", 1, "Medium")],
      Appointment: [deal("lsd-3", "ls-1", "Anjali Gupta", "Rs. 2,400", 2400, "Rohit", 1, "High"), deal("lsd-4", "ls-4", "Arjun Sethi", "Rs. 24K", 24000, "Aman", 1, "High")],
      "Service Done": [deal("lsd-5", "ls-3", "Priyanka Jain", "Rs. 8,000", 8000, "CleanPro", 2, "High")],
      "Follow-up": [deal("lsd-6", "ls-2", "Manav Singh", "Rs. 5,500", 5500, "Neha", 4, "Medium"), deal("lsd-7", "ls-8", "Sahil Nanda", "Rs. 1,800", 1800, "Operations", 3, "Medium")],
      "Repeat Booking": [deal("lsd-8", "ls-5", "Ritu Bansal", "Rs. 3,200", 3200, "Neha", 1, "Medium")],
    },
    tasks: [
      { id: "lst-1", title: "Confirm AC repair visit", related: "Anjali Gupta", priority: "High", assigned: "Reception", due: "Today", bucket: "Due Today", type: "follow-up" },
      { id: "lst-2", title: "Send payment reminder", related: "Priyanka Jain", priority: "High", assigned: "Accounts", due: "Today", bucket: "Due Today", type: "payment" },
      { id: "lst-3", title: "Follow up salon package", related: "Manav Singh", priority: "Medium", assigned: "Neha", due: "Tomorrow", bucket: "Due This Week", type: "follow-up" },
      { id: "lst-4", title: "Prepare trial session", related: "Arjun Sethi", priority: "Medium", assigned: "Aman", due: "Friday", bucket: "Due This Week", type: "internal" },
      { id: "lst-5", title: "Resolve delayed technician complaint", related: "Anjali Gupta", priority: "High", assigned: "Support", due: "Yesterday", bucket: "Overdue", type: "support" },
      { id: "lst-6", title: "Send repeat booking offer", related: "Ritu Bansal", priority: "Low", assigned: "Neha", due: "Next week", bucket: "Upcoming", type: "follow-up" },
    ],
    tickets: [
      { id: "#8042", subject: "Technician running late", customer: "Anjali Gupta", status: "Open", priority: "Medium", assigned: "Support", timeOpen: "1h" },
      { id: "#8048", subject: "Payment link not received", customer: "Priyanka Jain", status: "In Progress", priority: "High", assigned: "Accounts", timeOpen: "3h" },
      { id: "#8051", subject: "Need weekend salon slot", customer: "Manav Singh", status: "Resolved", priority: "Low", assigned: "Reception", timeOpen: "1d" },
      { id: "#8056", subject: "Trial trainer unavailable", customer: "Arjun Sethi", status: "Escalated", priority: "High", assigned: "Branch Manager", timeOpen: "2h" },
    ],
    workflows: [
      { id: "lsw-1", name: "Booking confirmation", active: true, trigger: "Customer books a service", condition: "Slot and staff available", action: "Assign staff and send confirmation", runCount: 58 },
      { id: "lsw-2", name: "Feedback and repeat follow-up", active: true, trigger: "Service completed", condition: "No open issue", action: "Request feedback and create repeat follow-up", runCount: 42 },
      { id: "lsw-3", name: "Payment reminder", active: true, trigger: "Payment pending", condition: "Payment link generated", action: "Send payment reminder to customer", runCount: 27 },
    ],
    activityFeed: [
      { id: "lsa-1", text: "Rohit assigned to AC repair visit", timestamp: "7 min ago", initials: "RO" },
      { id: "lsa-2", text: "AI flagged Priyanka payment pending", timestamp: "16 min ago", initials: "AI" },
      { id: "lsa-3", text: "Reception confirmed salon slot", timestamp: "45 min ago", initials: "RC" },
      { id: "lsa-4", text: "Feedback request sent after completed service", timestamp: "1h ago", initials: "WA" },
      { id: "lsa-5", text: "Arjun Sethi trial session moved to Appointment", timestamp: "2h ago", initials: "AM" },
      { id: "lsa-6", text: "Repeat booking offer sent to 12 customers", timestamp: "Yesterday", initials: "OF" },
    ],
    aiInsights: [
      "Payment reminders can recover Rs. 2.4L this month",
      "48 bookings need smooth staff assignment this week",
      "Repeat follow-ups can lift next week's bookings by 18%",
      "No-shows dropped after same-day WhatsApp confirmations",
    ],
    aiChatQA: [
      { question: "Which bookings need confirmation?", answer: "Anjali Gupta's AC repair and Arjun Sethi's gym trial need confirmation first. Both are due today and have high value or service priority.", followUps: ["Send WhatsApp", "Open tasks"] },
      { question: "Which payments are pending?", answer: "Priyanka Jain is highest priority because service is complete and the payment link was not received.", followUps: ["Send reminder", "Open tickets"] },
      { question: "Which customers may repeat?", answer: "Ritu Bansal and Manav Singh are strong repeat candidates based on prior engagement and package interest.", followUps: ["Create offer", "Open customers"] },
      { question: "How is staff workload?", answer: "Rohit and Neha have the busiest day. Move one low-priority follow-up to Operations to protect today's bookings.", followUps: ["Switch role", "Show tasks"] },
      { question: "Write service reminder", answer: "Hi, your service booking is confirmed for today. Our team member has been assigned and will update you before arrival.", followUps: ["Send message", "Edit template"] },
    ],
    reportsData: {
      leadSources: [
        { label: "WhatsApp", value: 31, color: "#16a34a" },
        { label: "Website", value: 18, color: "#2563eb" },
        { label: "Instagram", value: 20, color: "#4f46e5" },
        { label: "Referral", value: 15, color: "#f59e0b" },
        { label: "Walk-in", value: 9, color: "#64748b" },
        { label: "JustDial", value: 7, color: "#0ea5e9" },
      ],
      funnel: [
        { stage: "Inquiry", count: 104, dropoff: 0 },
        { stage: "Appointment", count: 72, dropoff: 31 },
        { stage: "Done", count: 61, dropoff: 15 },
        { stage: "Follow-up", count: 38, dropoff: 38 },
        { stage: "Repeat", count: 22, dropoff: 42 },
      ],
      team: [
        { name: "Rohit", assigned: 28, closed: 20 },
        { name: "Neha", assigned: 24, closed: 17 },
        { name: "Aman", assigned: 18, closed: 11 },
        { name: "Support", assigned: 14, closed: 10 },
      ],
      revenue: [
        { month: "Nov", value: 320000 },
        { month: "Dec", value: 350000 },
        { month: "Jan", value: 390000 },
        { month: "Feb", value: 370000 },
        { month: "Mar", value: 420000 },
        { month: "Apr", value: 460000 },
      ],
    },
    roiDefaults: { teamSize: 6, leadsPerMonth: 260, avgDealValue: 5500, manualHours: 7, lostDeals: 18 },
    blueprintSummary: {
      modules: ["Customer requests", "Booking calendar", "Staff assignment", "Payment tracking", "Feedback", "Repeat follow-ups"],
      automations: ["Booking confirmation", "Payment reminder", "Feedback and repeat booking workflow"],
      roles: ["Business Owner", "Admin", "Manager", "Sales User", "Operations User"],
      timeline: "3-4 weeks",
      onboarding: "3 days",
    },
    notifications: [
      { id: "lsn-1", text: "2 bookings need confirmation before noon" },
      { id: "lsn-2", text: "Payment reminder can recover Rs. 8,000 today" },
      { id: "lsn-3", text: "One staff delay ticket is escalated" },
    ],
    whatsappTemplate: "Hi {{name}}, your service booking is confirmed. Our team member has been assigned and will update you before arrival.",
    testimonial: {
      quote: "Our branch now sees bookings, staff work, payments, and repeat reminders in one dashboard.",
      author: "Neha",
      company: "UrbanCare Services",
    },
  }),
};

export const industryOptions = Object.values(industryData).map(({ key, name, tagline, description, icon }) => ({
  key,
  name,
  tagline,
  description,
  icon,
}));

export const guideTips: Partial<Record<string, string>> = {
  overview:
    "This dashboard changes based on your selected industry. Every KPI, chart, and data point is specific to your business type.",
  leads: "Click the AI Score button on any lead to see how HNX identifies your hottest prospects automatically.",
  pipeline: "Your pipeline stages are fully customisable. Try moving a deal to the next stage.",
  tasks: "Follow-up tasks can be auto-created by workflows. Try checking off a task to see how it works.",
  workflows: "This is where your business logic lives. Click Run simulation to see a workflow execute in real time.",
  ai: "Ask anything about your CRM data. Click a suggestion to see how the AI responds.",
  reports: "All charts update based on your selected industry. In your real CRM, these reflect your live data.",
  roi: "Adjust the sliders to match your business numbers and see how much you could save with HNX.",
  build: "Ready to get this built for your business? Fill the form and we'll send your custom CRM blueprint within 24 hours.",
};
