import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertTriangle,
  BarChart3,
  Bell,
  Bot,
  Boxes,
  Braces,
  Building2,
  CalendarCheck,
  CheckCircle2,
  Cloud,
  Code2,
  Component,
  CreditCard,
  Database,
  FileCheck2,
  FileSearch,
  Gauge,
  GitBranch,
  Globe2,
  KeyRound,
  LayoutDashboard,
  Layers3,
  LineChart,
  Link2,
  LockKeyhole,
  Mail,
  Map,
  Megaphone,
  MessageCircle,
  MonitorCheck,
  MousePointerClick,
  Network,
  Palette,
  PenTool,
  PlugZap,
  Rocket,
  Search,
  ServerCog,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Tags,
  Target,
  Timer,
  Type as TypeIcon,
  UsersRound,
  Waypoints,
  Workflow,
  Zap,
} from "lucide-react";
import type { ServiceItem } from "@/data/services";

export type ServiceDetailCard = {
  title: string;
  description: string;
  icon: LucideIcon;
};

export type ServicePageDetails = {
  problemTitle: string;
  problemDescription: string;
  problemNote: string;
  deliverableTitle: string;
  deliverableDescription: string;
  deliverableNote: string;
  processTitle: string;
  processDescription: string;
  useCaseTitle: string;
  useCaseDescription: string;
  bestForNote: string;
  problems: ServiceDetailCard[];
  deliverables: ServiceDetailCard[];
  process: ServiceDetailCard[];
  useCases: ServiceDetailCard[];
};

const servicePageDetails: Record<string, ServicePageDetails> = {
  "web-development": {
    problemTitle: "Remove the website issues that quietly cost trust and leads.",
    problemDescription: "We focus on the moments where visitors hesitate, pages feel slow, content is unclear, or enquiry paths are buried.",
    problemNote: "Built around speed, SEO, responsive quality, and conversion clarity.",
    deliverableTitle: "A complete web presence your team can launch and grow.",
    deliverableDescription: "Every deliverable is shaped to improve credibility, search visibility, lead capture, and day-to-day maintainability.",
    deliverableNote: "Designed for measurable launches, not just polished screens.",
    processTitle: "A fast, structured website delivery process.",
    processDescription: "Messaging, UX, performance, SEO, QA, and launch support move together so the website feels premium from first click.",
    useCaseTitle: "Website builds for businesses that need trust before contact.",
    useCaseDescription: "Ideal when the website has to explain the offer quickly, support paid or organic traffic, and convert qualified enquiries.",
    bestForNote: "Best when your website must become a reliable sales and trust asset.",
    problems: [
      { title: "Slow pages losing impatient visitors", description: "We optimize structure, assets, and frontend behavior so key pages feel fast on mobile and desktop.", icon: Gauge },
      { title: "Weak first impression", description: "We rebuild visual hierarchy, copy flow, and credibility signals so the brand feels trustworthy within seconds.", icon: Sparkles },
      { title: "Poor lead capture paths", description: "We add clear CTAs, forms, tracking, and follow-up handoff points around the visitor journey.", icon: Target },
      { title: "Unclear SEO foundation", description: "We structure metadata, headings, schema, internal links, and page content for stronger discoverability.", icon: Search },
    ],
    deliverables: [
      { title: "Conversion-focused page system", description: "Home, service, landing, contact, and trust sections arranged around enquiry flow.", icon: Globe2 },
      { title: "Responsive UI implementation", description: "Mobile, tablet, and desktop layouts with consistent spacing and polished interactions.", icon: MonitorCheck },
      { title: "SEO-ready content structure", description: "Metadata, headings, content hierarchy, schema basics, and clean URLs prepared for search.", icon: FileSearch },
      { title: "Lead forms and tracking", description: "Contact forms, conversion events, analytics setup, and CRM-ready lead capture.", icon: Waypoints },
      { title: "Performance cleanup", description: "Asset, animation, and layout tuning aimed at better Core Web Vitals.", icon: Zap },
      { title: "Launch support", description: "Domain, deployment, testing, and handoff support so the site can go live cleanly.", icon: Rocket },
    ],
    process: [
      { title: "Offer and audience map", description: "Clarify who the site serves, what they need to understand, and which actions matter most.", icon: Target },
      { title: "Sitemap and content flow", description: "Plan sections, page order, CTAs, and SEO structure before design polish begins.", icon: Layers3 },
      { title: "Premium UI build", description: "Create responsive sections, interactions, cards, forms, and brand-consistent layouts.", icon: Code2 },
      { title: "Speed and SEO pass", description: "Tune performance, metadata, schema basics, accessibility, and technical details.", icon: Gauge },
      { title: "QA and launch", description: "Test forms, responsiveness, links, analytics, deployment, and post-launch handoff.", icon: CheckCircle2 },
    ],
    useCases: [
      { title: "Service business website", description: "Explain services, show proof, capture enquiries, and make the business feel credible.", icon: Building2 },
      { title: "SEO landing pages", description: "Create focused pages for locations, services, or industries with clear conversion paths.", icon: Search },
      { title: "Portfolio or agency site", description: "Present work, process, testimonials, and contact paths in a premium experience.", icon: Palette },
      { title: "Campaign-ready microsite", description: "Launch a fast, trackable page for ads, events, offers, or new product announcements.", icon: Megaphone },
    ],
  },
  "saas-development": {
    problemTitle: "Turn scattered product ideas into a SaaS system people can use.",
    problemDescription: "We define the MVP, revenue flows, roles, dashboards, and operational controls before the build becomes expensive.",
    problemNote: "Built for subscriptions, teams, product analytics, and future scale.",
    deliverableTitle: "A SaaS foundation with product, admin, billing, and analytics layers.",
    deliverableDescription: "The build is planned around real product usage, not only screens. Users, plans, roles, data, and reporting are part of the architecture.",
    deliverableNote: "A launchable platform your team can improve after release.",
    processTitle: "A product delivery path from MVP scope to live SaaS.",
    processDescription: "Discovery, architecture, UX, development, billing, QA, deployment, and iteration are handled as one product system.",
    useCaseTitle: "SaaS builds for founders and teams moving beyond spreadsheets.",
    useCaseDescription: "Useful when a recurring product, portal, dashboard, or internal platform needs secure access and measurable usage.",
    bestForNote: "Best when the product needs roles, dashboards, billing, and admin visibility.",
    problems: [
      { title: "MVP scope keeps expanding", description: "We separate validation features from later product depth so the first release stays realistic.", icon: Boxes },
      { title: "Billing and access are unclear", description: "Plans, payment states, permissions, trials, and upgrades are mapped before implementation.", icon: CreditCard },
      { title: "No admin operating view", description: "We create dashboards and controls for managing users, records, plans, and support workflows.", icon: LayoutDashboard },
      { title: "Architecture cannot scale", description: "Data models, APIs, auth, and deployment choices are planned for maintainable growth.", icon: ServerCog },
    ],
    deliverables: [
      { title: "SaaS MVP architecture", description: "Core product modules, data models, auth flow, and release priorities.", icon: Boxes },
      { title: "Role-based user system", description: "Owners, admins, team members, and customers with appropriate permissions.", icon: UsersRound },
      { title: "Subscription and billing flow", description: "Plans, checkout, payment states, invoices, and upgrade paths.", icon: CreditCard },
      { title: "Product dashboards", description: "User-facing dashboards with usage, activity, metrics, and workflow context.", icon: BarChart3 },
      { title: "Admin control room", description: "Internal tools to manage users, data, subscriptions, and support actions.", icon: LayoutDashboard },
      { title: "Cloud deployment setup", description: "Production hosting, environment configuration, database setup, and release checks.", icon: Cloud },
    ],
    process: [
      { title: "Product blueprint", description: "Clarify users, jobs-to-be-done, pricing model, and first release boundaries.", icon: Target },
      { title: "Data and role architecture", description: "Design entities, permissions, billing states, and workflow rules.", icon: Database },
      { title: "UX and dashboard design", description: "Shape onboarding, core actions, admin screens, and reporting views.", icon: LayoutDashboard },
      { title: "Build and integrations", description: "Implement frontend, backend, auth, billing, analytics, and notifications.", icon: Code2 },
      { title: "Launch and iterate", description: "QA, production deploy, onboarding support, and improvement roadmap.", icon: Rocket },
    ],
    useCases: [
      { title: "Subscription platform", description: "Paid plans, gated features, customer accounts, and recurring revenue workflows.", icon: CreditCard },
      { title: "B2B dashboard SaaS", description: "Customer dashboards with analytics, team access, and admin reporting.", icon: BarChart3 },
      { title: "Client or vendor portal", description: "Secure portals for uploads, tasks, communication, approvals, and status visibility.", icon: KeyRound },
      { title: "Internal product platform", description: "Replace operational spreadsheets with a role-based product workspace.", icon: Workflow },
    ],
  },
  "mobile-app-development": {
    problemTitle: "Fix the mobile gaps that make users drop off.",
    problemDescription: "We focus on app UX, secure backend connections, notifications, payments, maps, and release readiness from the start.",
    problemNote: "Built for iOS, Android, APIs, and real customer usage.",
    deliverableTitle: "A mobile app experience connected to business operations.",
    deliverableDescription: "The app is planned with onboarding, core actions, backend sync, notifications, payments, admin workflows, and store release support.",
    deliverableNote: "Designed so the app feels smooth and your team can operate it.",
    processTitle: "A mobile-first delivery path from flows to store-ready build.",
    processDescription: "User journeys, UI states, API contracts, testing, store assets, and release support move together.",
    useCaseTitle: "Mobile apps for customer actions, bookings, payments, and loyalty.",
    useCaseDescription: "Useful when users need a faster, more direct way to interact with your service from their phone.",
    bestForNote: "Best when mobile engagement, notifications, and secure backend workflows matter.",
    problems: [
      { title: "App idea lacks usable flows", description: "We convert the concept into onboarding, primary journeys, empty states, and edge cases.", icon: Smartphone },
      { title: "Backend is not app-ready", description: "APIs, auth, records, media, payments, and admin actions are planned for mobile usage.", icon: ServerCog },
      { title: "Users forget to return", description: "Push notifications, reminders, and status updates are designed around meaningful triggers.", icon: Bell },
      { title: "Store launch feels risky", description: "We prepare release checks, store assets, privacy requirements, and QA passes earlier.", icon: Rocket },
    ],
    deliverables: [
      { title: "Mobile UX and screen system", description: "Onboarding, navigation, dashboard, forms, list views, and account flows.", icon: Smartphone },
      { title: "Secure API integration", description: "Auth, profile data, business records, uploads, and realtime status sync.", icon: PlugZap },
      { title: "Push notification flows", description: "Reminders, confirmations, updates, and engagement triggers.", icon: Bell },
      { title: "Payment and booking modules", description: "Checkout, booking, order, subscription, or wallet flows as needed.", icon: CreditCard },
      { title: "Admin-connected workflow", description: "Admin panels or CRM links to manage app users and business actions.", icon: LayoutDashboard },
      { title: "Store release support", description: "Build preparation, store assets, QA, and launch guidance.", icon: Rocket },
    ],
    process: [
      { title: "Journey mapping", description: "Define app users, actions, navigation, and the shortest useful path to value.", icon: Map },
      { title: "UX and prototype", description: "Design mobile flows, screens, states, and interactions before deep development.", icon: MousePointerClick },
      { title: "API and backend setup", description: "Connect auth, data, payments, notifications, and admin workflows.", icon: ServerCog },
      { title: "App build and QA", description: "Develop screens, validate behavior, test devices, and tune performance.", icon: Smartphone },
      { title: "Store readiness", description: "Prepare release builds, listings, privacy notes, and launch support.", icon: Rocket },
    ],
    useCases: [
      { title: "Booking app", description: "Allow customers to book, pay, reschedule, and receive reminders from one app.", icon: CalendarCheck },
      { title: "Service marketplace", description: "Connect users, providers, listings, payments, reviews, and admin workflows.", icon: UsersRound },
      { title: "Customer loyalty app", description: "Keep customers returning with rewards, push campaigns, and account history.", icon: Sparkles },
      { title: "Field team app", description: "Give teams task lists, customer records, map context, and status updates on mobile.", icon: Map },
    ],
  },
  "custom-crm-systems": {
    problemTitle: "Replace scattered sales operations with one owned CRM workflow.",
    problemDescription: "We map your real lead flow, follow-ups, roles, reports, and automation before building a custom CRM around it.",
    problemNote: "Built for pipelines, ownership, dashboards, automation, and team control.",
    deliverableTitle: "A CRM system shaped around your actual business process.",
    deliverableDescription: "The system can include lead capture, customer profiles, pipeline boards, tasks, reminders, dashboards, reports, roles, and AI insights.",
    deliverableNote: "Your process becomes software your team owns.",
    processTitle: "A CRM delivery process built around operational clarity.",
    processDescription: "We start with your sales and service workflow, then turn it into modules, permissions, dashboards, and automations.",
    useCaseTitle: "CRM systems for teams that need visibility and follow-through.",
    useCaseDescription: "Useful when spreadsheet tracking or generic CRMs do not match the way your team actually sells and supports customers.",
    bestForNote: "Best when leads, follow-ups, roles, and reporting need one source of truth.",
    problems: [
      { title: "Leads disappear across channels", description: "We centralize website, WhatsApp, campaign, and manual leads into one tracked pipeline.", icon: Target },
      { title: "Follow-ups depend on memory", description: "Tasks, reminders, ownership, and escalation rules reduce missed actions.", icon: Bell },
      { title: "Managers lack live visibility", description: "Dashboards show pipeline stages, activity, conversions, and team performance.", icon: BarChart3 },
      { title: "Generic CRM does not fit", description: "Modules, roles, fields, and workflows are shaped around your business instead of a template.", icon: Workflow },
    ],
    deliverables: [
      { title: "Lead and customer modules", description: "Capture, assign, qualify, update, and track customers through clear lifecycle states.", icon: UsersRound },
      { title: "Pipeline board", description: "Visual stage tracking for sales, admissions, support, or service workflows.", icon: LayoutDashboard },
      { title: "Task and follow-up system", description: "Reminders, assignments, due dates, notes, and escalation triggers.", icon: Bell },
      { title: "Role and permission control", description: "Admin, manager, agent, and viewer access configured by responsibility.", icon: LockKeyhole },
      { title: "Reports and dashboards", description: "Conversion, team activity, source performance, and customer insights.", icon: BarChart3 },
      { title: "Automation and AI layer", description: "Lead scoring, next actions, auto alerts, templates, and workflow triggers.", icon: Bot },
    ],
    process: [
      { title: "Workflow audit", description: "Map lead sources, stages, roles, follow-ups, reporting needs, and bottlenecks.", icon: FileSearch },
      { title: "Module planning", description: "Define CRM entities, fields, statuses, permissions, automations, and dashboards.", icon: Boxes },
      { title: "UX and data model", description: "Design practical screens and a data structure your team can operate daily.", icon: Database },
      { title: "Build and automate", description: "Implement CRM modules, dashboards, reminders, reports, and integrations.", icon: Workflow },
      { title: "Training and rollout", description: "Test real scenarios, migrate starter data, train the team, and refine adoption.", icon: CheckCircle2 },
    ],
    useCases: [
      { title: "Real estate CRM", description: "Manage property enquiries, site visits, follow-ups, brokers, and booking stages.", icon: Building2 },
      { title: "Education admissions CRM", description: "Track enquiries, counsellor tasks, application stages, calls, and conversion reports.", icon: UsersRound },
      { title: "Healthcare CRM", description: "Organize patient enquiries, appointment requests, follow-ups, and support activity.", icon: CalendarCheck },
      { title: "Sales team CRM", description: "Give managers live pipeline visibility and reps a cleaner daily action list.", icon: Target },
    ],
  },
  "ai-automation": {
    problemTitle: "Use AI where it removes real operational drag.",
    problemDescription: "We apply AI to lead handling, support replies, documents, CRM insights, and repeat decisions with practical guardrails.",
    problemNote: "Built for controlled AI workflows, not vague chatbot experiments.",
    deliverableTitle: "AI workflows connected to your data, teams, and tools.",
    deliverableDescription: "The goal is useful automation: summaries, scores, drafts, triggers, insights, and human review where it matters.",
    deliverableNote: "AI is designed as an assistant layer your business can trust.",
    processTitle: "An AI delivery process with workflow control and review points.",
    processDescription: "We identify repeatable decisions, prepare data, build prompts and actions, then test the workflow against real business cases.",
    useCaseTitle: "AI automation for teams with repetitive decisions and messages.",
    useCaseDescription: "Useful when people are spending time reading, sorting, scoring, summarizing, replying, or updating records manually.",
    bestForNote: "Best when AI needs to support operations without losing human oversight.",
    problems: [
      { title: "Slow lead response", description: "AI can qualify, summarize, score, and draft a next action before the team opens the lead.", icon: Timer },
      { title: "Manual document review", description: "Extract summaries, fields, risks, and action items from uploaded files or messages.", icon: FileSearch },
      { title: "Support replies feel repetitive", description: "Draft contextual replies from templates, customer data, and knowledge sources.", icon: MessageCircle },
      { title: "CRM data is underused", description: "Turn activity history into next-best actions, priority signals, and manager insights.", icon: BarChart3 },
    ],
    deliverables: [
      { title: "AI lead scoring", description: "Rules and model prompts that classify urgency, fit, and follow-up priority.", icon: Activity },
      { title: "Reply drafting assistant", description: "Context-aware email, WhatsApp, or support response drafts with review control.", icon: MessageCircle },
      { title: "Document intelligence flow", description: "Summaries, extracted fields, and recommended actions from documents.", icon: FileCheck2 },
      { title: "Internal AI assistant", description: "A focused assistant for team FAQs, SOPs, CRM records, or operational data.", icon: Bot },
      { title: "Workflow agents", description: "Multi-step automations that read, decide, update, notify, and log outcomes.", icon: Workflow },
      { title: "Guardrails and review", description: "Human checkpoints, logs, fallback rules, and safer action boundaries.", icon: ShieldCheck },
    ],
    process: [
      { title: "Automation opportunity audit", description: "Find repetitive decisions with enough value and enough structure for AI help.", icon: Search },
      { title: "Data and prompt design", description: "Prepare context sources, prompt patterns, examples, and output rules.", icon: Braces },
      { title: "Workflow build", description: "Connect AI steps to forms, CRM, documents, messages, or dashboards.", icon: Workflow },
      { title: "Guardrail testing", description: "Test edge cases, review points, response quality, and fallback behavior.", icon: ShieldCheck },
      { title: "Rollout and tuning", description: "Launch carefully, measure usefulness, and improve prompts or actions over time.", icon: LineChart },
    ],
    useCases: [
      { title: "AI lead assistant", description: "Summarize enquiries, detect intent, score fit, and recommend follow-up actions.", icon: Bot },
      { title: "Support response assistant", description: "Draft replies from previous tickets, knowledge base content, and customer context.", icon: MessageCircle },
      { title: "Document processing", description: "Extract fields, summaries, and required next steps from forms, PDFs, or notes.", icon: FileSearch },
      { title: "CRM next-action intelligence", description: "Suggest which deals, customers, or tasks need attention first.", icon: Sparkles },
    ],
  },
  "workflow-automation": {
    problemTitle: "Remove manual handoffs that slow down daily work.",
    problemDescription: "We design trigger-condition-action workflows for routing, reminders, approvals, notifications, and status updates.",
    problemNote: "Built for reliable process movement across teams and tools.",
    deliverableTitle: "Automation flows that make operations feel connected.",
    deliverableDescription: "Each flow has a clear trigger, condition, action, owner, fallback, and reporting path.",
    deliverableNote: "Work moves forward without depending on memory.",
    processTitle: "A workflow automation path from process map to live rules.",
    processDescription: "We turn repeated manual steps into tested rules that update records, notify people, and keep managers informed.",
    useCaseTitle: "Automation for teams with repeated tasks and approvals.",
    useCaseDescription: "Useful when leads, tickets, tasks, approvals, or reminders need to move without manual checking.",
    bestForNote: "Best when the process is known but execution is too manual.",
    problems: [
      { title: "Tasks assigned by hand", description: "Rules can assign work by source, location, product, priority, or availability.", icon: Workflow },
      { title: "Approvals get delayed", description: "Approval requests, reminders, escalations, and status updates run automatically.", icon: FileCheck2 },
      { title: "Follow-ups are forgotten", description: "Automated reminders and notifications keep leads and customers from going cold.", icon: Bell },
      { title: "Managers cannot see flow health", description: "Dashboards and reports show stuck items, overdue work, and completion trends.", icon: BarChart3 },
    ],
    deliverables: [
      { title: "Trigger and condition map", description: "Clear logic for when workflows start, branch, pause, or escalate.", icon: Workflow },
      { title: "Task routing rules", description: "Automatic assignment based on ownership, source, priority, category, or capacity.", icon: UsersRound },
      { title: "Reminder system", description: "Time-based nudges for calls, renewals, approvals, support, and internal tasks.", icon: Bell },
      { title: "Approval flows", description: "Role-based approvals with notifications, status changes, and audit trails.", icon: FileCheck2 },
      { title: "Communication automation", description: "Email, WhatsApp, SMS, or internal alerts connected to workflow events.", icon: MessageCircle },
      { title: "Workflow reporting", description: "Visibility into stuck records, SLA risks, completed actions, and team throughput.", icon: BarChart3 },
    ],
    process: [
      { title: "Process capture", description: "Document the current manual flow, owners, exceptions, and handoff points.", icon: FileSearch },
      { title: "Rule design", description: "Define triggers, conditions, actions, delays, fallback paths, and audit needs.", icon: Workflow },
      { title: "Tool connection", description: "Connect CRM, forms, sheets, email, WhatsApp, or custom system events.", icon: PlugZap },
      { title: "Testing and exceptions", description: "Run realistic scenarios so loops, delays, and edge cases are handled safely.", icon: ShieldCheck },
      { title: "Launch and monitor", description: "Release automations, watch flow health, and refine based on actual usage.", icon: MonitorCheck },
    ],
    useCases: [
      { title: "Lead follow-up workflow", description: "Assign new leads, send acknowledgement, remind the owner, and escalate missed actions.", icon: Target },
      { title: "Approval workflow", description: "Move requests through role approvals with reminders and clear status history.", icon: FileCheck2 },
      { title: "Support escalation", description: "Route urgent tickets, notify managers, and track SLA-sensitive work.", icon: Bell },
      { title: "Onboarding automation", description: "Create tasks, send instructions, collect data, and update progress automatically.", icon: CheckCircle2 },
    ],
  },
  "api-development": {
    problemTitle: "Build APIs that are secure, documented, and ready to connect.",
    problemDescription: "We design API contracts, auth, webhooks, rate limits, data flows, and documentation before integrations become fragile.",
    problemNote: "Built for products, mobile apps, dashboards, partners, and third-party tools.",
    deliverableTitle: "A backend API layer your apps and integrations can trust.",
    deliverableDescription: "The API foundation covers data models, endpoints, authentication, validation, docs, monitoring, and integration behavior.",
    deliverableNote: "Built to be consumed cleanly by real frontends and systems.",
    processTitle: "An API delivery process from contract to production.",
    processDescription: "We plan endpoints, auth, data rules, performance, docs, testing, and deployment as a single backend product.",
    useCaseTitle: "API builds for connected apps, dashboards, and platforms.",
    useCaseDescription: "Useful when systems need reliable data exchange, secure access, documented endpoints, and webhook-driven actions.",
    bestForNote: "Best when the backend must support multiple clients or integrations.",
    problems: [
      { title: "Frontend waits on unclear data", description: "We define request and response contracts so web and mobile teams can build confidently.", icon: Braces },
      { title: "Auth is inconsistent", description: "JWT, OAuth, API keys, roles, and access rules are designed around real usage.", icon: KeyRound },
      { title: "Integrations break silently", description: "Webhooks, retries, logs, and status responses make external flows easier to debug.", icon: PlugZap },
      { title: "No usable documentation", description: "Clear endpoint docs, examples, and error responses reduce confusion after launch.", icon: FileCheck2 },
    ],
    deliverables: [
      { title: "API architecture", description: "Endpoint structure, data model, versioning approach, and integration boundaries.", icon: Network },
      { title: "Authentication layer", description: "JWT, OAuth, API keys, sessions, or role-based access as required.", icon: KeyRound },
      { title: "Webhook system", description: "Inbound and outbound event flows with retries, validation, and logging.", icon: PlugZap },
      { title: "Validation and rate limits", description: "Payload checks, permission checks, throttling, and safer error handling.", icon: ShieldCheck },
      { title: "API documentation", description: "Swagger-style references, examples, auth notes, and integration guidance.", icon: FileCheck2 },
      { title: "Monitoring and logs", description: "Visibility into request failures, latency, events, and integration health.", icon: MonitorCheck },
    ],
    process: [
      { title: "Contract planning", description: "Define endpoints, consumers, data shapes, auth flows, and integration goals.", icon: Braces },
      { title: "Backend architecture", description: "Set up data models, services, validation, permissions, and error patterns.", icon: ServerCog },
      { title: "Implementation", description: "Build REST or GraphQL APIs, webhooks, jobs, and integration adapters.", icon: Code2 },
      { title: "Docs and testing", description: "Create examples, test responses, secure flows, edge cases, and performance risks.", icon: FileCheck2 },
      { title: "Deploy and monitor", description: "Release the API with logs, environment configuration, and health checks.", icon: Rocket },
    ],
    useCases: [
      { title: "Mobile app backend", description: "Power app screens, auth, profiles, payments, uploads, and notifications.", icon: Smartphone },
      { title: "Partner integration API", description: "Expose secure endpoints for vendors, customers, or internal systems.", icon: Link2 },
      { title: "Webhook automation layer", description: "Trigger actions when payments, forms, CRM events, or status updates happen.", icon: Zap },
      { title: "Analytics data API", description: "Serve dashboards with reliable metrics, filters, and business reporting.", icon: BarChart3 },
    ],
  },
  "integration-services": {
    problemTitle: "Connect business tools so data stops being copied manually.",
    problemDescription: "We build reliable sync flows across CRMs, forms, payments, WhatsApp, sheets, email, ERPs, dashboards, and custom software.",
    problemNote: "Built for cleaner data movement and less manual entry.",
    deliverableTitle: "An integration hub that keeps daily operations in sync.",
    deliverableDescription: "Each connector is designed with triggers, field mapping, error handling, logs, ownership, and fallback behavior.",
    deliverableNote: "Your tools work together instead of becoming separate islands.",
    processTitle: "An integration delivery path from tool audit to reliable sync.",
    processDescription: "We identify source systems, map fields, define events, build connectors, test edge cases, and monitor sync health.",
    useCaseTitle: "Integrations for companies using many disconnected tools.",
    useCaseDescription: "Useful when customer data, payments, leads, messages, or reports need to flow between platforms without copy-paste.",
    bestForNote: "Best when your team spends too much time moving data between apps.",
    problems: [
      { title: "Duplicate manual data entry", description: "Sync leads, payments, customers, and status updates between systems automatically.", icon: Database },
      { title: "Tools do not share context", description: "Connect CRM, sheets, WhatsApp, email, forms, dashboards, and internal tools.", icon: Link2 },
      { title: "Errors are hard to trace", description: "Add logs, retries, alerts, and clear ownership for failed sync events.", icon: AlertTriangle },
      { title: "Reports are always outdated", description: "Move data into reporting views faster so managers see fresher numbers.", icon: BarChart3 },
    ],
    deliverables: [
      { title: "Connector map", description: "Source systems, destination systems, event triggers, and data ownership.", icon: Network },
      { title: "Field mapping and transforms", description: "Clean conversion rules for names, statuses, IDs, payment states, and records.", icon: Braces },
      { title: "Webhook and API connectors", description: "Custom integrations for tools that support APIs, webhooks, or automation platforms.", icon: PlugZap },
      { title: "Payment and CRM sync", description: "Connect payment gateways, lead sources, customer records, and follow-up tasks.", icon: CreditCard },
      { title: "Error logs and alerts", description: "Track failed syncs, missing fields, and exceptions before they become silent issues.", icon: Bell },
      { title: "Reporting-ready data flow", description: "Move clean data into dashboards, sheets, or analytics tools.", icon: BarChart3 },
    ],
    process: [
      { title: "Tool audit", description: "List systems, owners, current manual steps, and data quality issues.", icon: FileSearch },
      { title: "Flow and field mapping", description: "Define triggers, payloads, field transforms, dedupe rules, and source of truth.", icon: Waypoints },
      { title: "Connector build", description: "Implement API, webhook, sheet, CRM, payment, or automation platform connections.", icon: PlugZap },
      { title: "Exception testing", description: "Test missing data, duplicate records, delays, failed payments, and retry rules.", icon: ShieldCheck },
      { title: "Monitor and refine", description: "Launch with logging, alerts, and improvements based on live sync behavior.", icon: MonitorCheck },
    ],
    useCases: [
      { title: "WhatsApp to CRM", description: "Capture enquiries, create leads, assign owners, and log message context.", icon: MessageCircle },
      { title: "Payment to dashboard", description: "Sync payment status, customer plans, invoices, and revenue reports.", icon: CreditCard },
      { title: "Forms to operations", description: "Turn website forms into tasks, records, alerts, and follow-up sequences.", icon: FileCheck2 },
      { title: "ERP or sheet sync", description: "Keep operational records, inventory, or reporting sheets aligned with app data.", icon: Database },
    ],
  },
  "devops-deployment": {
    problemTitle: "Make deployment predictable instead of stressful.",
    problemDescription: "We set up CI/CD, environments, monitoring, logs, rollback paths, and release checks so production changes feel controlled.",
    problemNote: "Built for safer deploys, faster recovery, and better visibility.",
    deliverableTitle: "A release pipeline that supports production confidence.",
    deliverableDescription: "Your code gets a clearer path from repository to production with checks, environments, logs, and recovery procedures.",
    deliverableNote: "Deployments become a repeatable system, not a manual ritual.",
    processTitle: "A DevOps setup path from repo audit to monitored releases.",
    processDescription: "We review current deployment risks, configure automation, add observability, test rollback, and document release steps.",
    useCaseTitle: "DevOps support for teams shipping live products.",
    useCaseDescription: "Useful when deploys are manual, downtime is costly, logs are scattered, or production issues are hard to trace.",
    bestForNote: "Best when product releases need safer pipelines and clearer monitoring.",
    problems: [
      { title: "Manual deployment risk", description: "CI/CD reduces skipped steps, environment mistakes, and inconsistent release behavior.", icon: GitBranch },
      { title: "No rollback confidence", description: "Release strategy includes safer deployment patterns and recovery steps.", icon: Rocket },
      { title: "Logs are hard to read", description: "Centralized logs and monitoring make production issues easier to identify.", icon: FileSearch },
      { title: "Environment drift", description: "Variables, secrets, build steps, and deployment targets are documented and controlled.", icon: KeyRound },
    ],
    deliverables: [
      { title: "CI/CD pipeline", description: "Automated build, test, deploy, and notification steps using your repo workflow.", icon: Workflow },
      { title: "Environment configuration", description: "Development, staging, production variables, secrets, and deployment settings.", icon: KeyRound },
      { title: "Container or hosting setup", description: "Docker, Vercel, AWS, Render, or similar deployment foundations.", icon: Cloud },
      { title: "Monitoring and logs", description: "Visibility into uptime, errors, build failures, request behavior, and incidents.", icon: MonitorCheck },
      { title: "Rollback plan", description: "Safer recovery steps for failed releases or critical regressions.", icon: Activity },
      { title: "Release documentation", description: "Clear deployment notes, commands, responsibilities, and operational handoff.", icon: FileCheck2 },
    ],
    process: [
      { title: "Deployment audit", description: "Review repo, hosting, env vars, build steps, downtime risks, and manual release gaps.", icon: Search },
      { title: "Pipeline setup", description: "Configure CI/CD jobs for build, test, deployment, and notifications.", icon: GitBranch },
      { title: "Observability layer", description: "Add logs, uptime checks, error tracking, and deploy visibility.", icon: MonitorCheck },
      { title: "Rollback testing", description: "Validate recovery steps and document what to do when deploys misbehave.", icon: ShieldCheck },
      { title: "Handoff and support", description: "Train the team on release flow, monitoring, and ongoing improvement.", icon: CheckCircle2 },
    ],
    useCases: [
      { title: "SaaS release pipeline", description: "Automate product deploys with staging, production checks, and rollback readiness.", icon: Rocket },
      { title: "Website deployment cleanup", description: "Replace manual uploads with reliable hosting, previews, and versioned releases.", icon: Globe2 },
      { title: "API production workflow", description: "Deploy backend services with logs, health checks, and environment safety.", icon: ServerCog },
      { title: "Team release governance", description: "Give teams a documented, repeatable process for shipping changes.", icon: UsersRound },
    ],
  },
  "cloud-infrastructure": {
    problemTitle: "Set up cloud infrastructure that can grow without chaos.",
    problemDescription: "We plan hosting, databases, storage, backups, CDN, monitoring, and cost-aware architecture around the product's real needs.",
    problemNote: "Built for production hosting, scale, backups, and visibility.",
    deliverableTitle: "A cloud foundation for apps, databases, assets, and monitoring.",
    deliverableDescription: "Infrastructure decisions are made around uptime, performance, security, maintainability, and growth path.",
    deliverableNote: "Your product gets a clean production home.",
    processTitle: "A cloud setup process from architecture to monitored production.",
    processDescription: "We define workloads, choose services, configure environments, add backups, and prepare monitoring.",
    useCaseTitle: "Cloud infrastructure for growing products and business systems.",
    useCaseDescription: "Useful when hosting, databases, storage, scale, backups, and uptime need a more deliberate setup.",
    bestForNote: "Best when your product needs reliable cloud architecture and operational visibility.",
    problems: [
      { title: "Hosting choices feel random", description: "We match app type, traffic, team skill, budget, and release needs to the right setup.", icon: Cloud },
      { title: "Database risk is unclear", description: "Backups, access, performance, and growth needs are included in the plan.", icon: Database },
      { title: "No uptime visibility", description: "Monitoring, alerts, and health checks show whether the system is healthy.", icon: MonitorCheck },
      { title: "Assets load slowly", description: "CDN, storage, caching, and deployment settings improve user-facing performance.", icon: Gauge },
    ],
    deliverables: [
      { title: "Cloud architecture plan", description: "Hosting, database, storage, CDN, environments, and monitoring choices.", icon: Cloud },
      { title: "Database setup", description: "MongoDB Atlas, PostgreSQL, backups, indexes, roles, and connection settings.", icon: Database },
      { title: "Storage and CDN", description: "Asset delivery, file storage, caching, media handling, and performance tuning.", icon: Globe2 },
      { title: "Backup policy", description: "Backup frequency, retention, restoration expectations, and responsibility notes.", icon: FileCheck2 },
      { title: "Monitoring and alerts", description: "Uptime, errors, resource usage, and critical event notifications.", icon: MonitorCheck },
      { title: "Cost and scale review", description: "Practical recommendations for resource sizing and future growth.", icon: LineChart },
    ],
    process: [
      { title: "Workload review", description: "Understand app type, traffic, data size, security needs, and uptime expectations.", icon: Search },
      { title: "Architecture selection", description: "Choose hosting, database, storage, CDN, and deployment model.", icon: Cloud },
      { title: "Environment setup", description: "Configure projects, env vars, domains, certificates, databases, and access.", icon: ServerCog },
      { title: "Backup and monitoring", description: "Add health checks, alerts, logs, backups, and restoration notes.", icon: MonitorCheck },
      { title: "Production handoff", description: "Document architecture, costs, credentials flow, and maintenance routines.", icon: FileCheck2 },
    ],
    useCases: [
      { title: "Startup product hosting", description: "Set up a scalable foundation for MVPs, SaaS apps, and customer portals.", icon: Rocket },
      { title: "Database migration", description: "Move from local or fragile setups to managed databases with backups.", icon: Database },
      { title: "High-traffic website infrastructure", description: "Improve speed and stability with CDN, caching, and better hosting.", icon: Gauge },
      { title: "Business system cloud setup", description: "Host CRM, dashboards, APIs, storage, and reports in a cleaner architecture.", icon: LayoutDashboard },
    ],
  },
  "maintenance-support": {
    problemTitle: "Keep live products stable after launch.",
    problemDescription: "We handle fixes, updates, monitoring, performance review, security patches, backups, and monthly reporting.",
    problemNote: "Built for uptime, response, visibility, and continuous product health.",
    deliverableTitle: "A support system for products that cannot be left unattended.",
    deliverableDescription: "Support is structured around tickets, priorities, monitoring, fixes, updates, reports, and improvement suggestions.",
    deliverableNote: "Your product gets ongoing care instead of occasional emergency repairs.",
    processTitle: "A maintenance process for stable live operations.",
    processDescription: "We create a support rhythm for issue intake, triage, fixes, monitoring, reporting, and preventative checks.",
    useCaseTitle: "Maintenance support for websites, apps, SaaS, and CRM systems.",
    useCaseDescription: "Useful when live software needs regular care, bug fixes, performance checks, updates, and accountability.",
    bestForNote: "Best when downtime, bugs, or stale software would hurt operations.",
    problems: [
      { title: "Bugs stay unresolved", description: "A clear support queue gives issues priority, ownership, and resolution tracking.", icon: AlertTriangle },
      { title: "Updates get ignored", description: "Version updates, compatibility checks, and maintenance windows reduce long-term risk.", icon: GitBranch },
      { title: "No uptime monitoring", description: "Health checks and alerts help identify problems before users report them.", icon: MonitorCheck },
      { title: "Performance slowly degrades", description: "Regular reviews catch slow pages, heavy assets, errors, and workflow friction.", icon: Gauge },
    ],
    deliverables: [
      { title: "Support ticket flow", description: "Issue intake, priority levels, updates, and resolution notes.", icon: FileCheck2 },
      { title: "Bug fixes and improvements", description: "Focused fixes for UI, backend, forms, integrations, and content issues.", icon: Braces },
      { title: "Uptime and error monitoring", description: "Monitoring setup, alerts, error checks, and incident visibility.", icon: MonitorCheck },
      { title: "Security and version updates", description: "Dependency updates, patches, and compatibility checks.", icon: ShieldCheck },
      { title: "Backup checks", description: "Backup health review and restoration readiness notes where applicable.", icon: Cloud },
      { title: "Monthly health report", description: "Summary of issues, fixes, uptime, recommendations, and next improvements.", icon: BarChart3 },
    ],
    process: [
      { title: "Product health audit", description: "Review current risks, hosting, errors, speed, dependencies, and support needs.", icon: FileSearch },
      { title: "Support setup", description: "Define ticket flow, response expectations, priorities, and contact process.", icon: Bell },
      { title: "Monitoring and backups", description: "Add uptime checks, error visibility, and backup review routines.", icon: MonitorCheck },
      { title: "Fix and improve", description: "Resolve issues, patch problems, tune performance, and update versions.", icon: CheckCircle2 },
      { title: "Report and plan", description: "Share monthly notes and recommend practical improvements.", icon: LineChart },
    ],
    useCases: [
      { title: "Business website care", description: "Keep forms, content, speed, tracking, and pages working properly.", icon: Globe2 },
      { title: "SaaS maintenance", description: "Handle bugs, updates, user issues, monitoring, and release support.", icon: LayoutDashboard },
      { title: "CRM support", description: "Maintain workflows, permissions, dashboards, reports, and integrations.", icon: Workflow },
      { title: "Emergency issue response", description: "Investigate urgent production problems and restore critical flows.", icon: AlertTriangle },
    ],
  },
  "security-compliance": {
    problemTitle: "Strengthen product security before growth increases risk.",
    problemDescription: "We review access control, API protection, data handling, headers, audit logs, backups, and operational security basics.",
    problemNote: "Built for safer access, clearer accountability, and practical compliance readiness.",
    deliverableTitle: "A practical security layer for business software.",
    deliverableDescription: "Security improvements focus on roles, authentication, API controls, logs, data protection, policies, and safer defaults.",
    deliverableNote: "Designed for real products, not checkbox theater.",
    processTitle: "A security improvement process from review to hardening.",
    processDescription: "We identify risks, prioritize fixes, apply controls, test behavior, and document what changed.",
    useCaseTitle: "Security support for products handling customer or business data.",
    useCaseDescription: "Useful when access, APIs, logs, data protection, or compliance expectations need stronger structure.",
    bestForNote: "Best when customer data, role access, or API exposure creates business risk.",
    problems: [
      { title: "Access is too broad", description: "RBAC and permission checks reduce unnecessary access to sensitive screens and data.", icon: LockKeyhole },
      { title: "APIs are exposed", description: "Auth, validation, rate limits, headers, and logging make endpoints safer.", icon: ShieldCheck },
      { title: "No audit trail", description: "Important changes should leave a trace for accountability and investigation.", icon: FileSearch },
      { title: "Data handling is unclear", description: "Encryption, backups, retention, and access patterns become easier to reason about.", icon: Database },
    ],
    deliverables: [
      { title: "Security review", description: "Risk scan across auth, roles, APIs, headers, data, hosting, and dependencies.", icon: FileSearch },
      { title: "Role-based access controls", description: "Clear permissions for admins, managers, users, customers, and service roles.", icon: LockKeyhole },
      { title: "API protection", description: "Token checks, validation, rate limits, CORS, and safer error responses.", icon: ShieldCheck },
      { title: "Audit logs", description: "Track important data changes, logins, role updates, and sensitive actions.", icon: FileCheck2 },
      { title: "Secure configuration", description: "Headers, secrets, environment practices, backups, and deployment hygiene.", icon: KeyRound },
      { title: "Compliance readiness notes", description: "Practical documentation for controls, gaps, and next steps.", icon: CheckCircle2 },
    ],
    process: [
      { title: "Risk review", description: "Inspect current access, APIs, data exposure, hosting, dependencies, and workflows.", icon: Search },
      { title: "Control plan", description: "Prioritize fixes based on risk, business impact, and implementation effort.", icon: ShieldCheck },
      { title: "Hardening work", description: "Implement permissions, API controls, logs, headers, validation, and safer defaults.", icon: LockKeyhole },
      { title: "Testing and verification", description: "Validate user roles, auth flows, protected endpoints, and edge cases.", icon: CheckCircle2 },
      { title: "Documentation", description: "Summarize controls, responsibilities, and remaining improvement opportunities.", icon: FileCheck2 },
    ],
    useCases: [
      { title: "CRM access hardening", description: "Protect customer records, pipeline data, reports, and admin controls.", icon: UsersRound },
      { title: "API security review", description: "Lock down endpoints, tokens, rate limits, validation, and logs.", icon: Braces },
      { title: "Audit trail setup", description: "Track sensitive actions and changes for accountability.", icon: FileSearch },
      { title: "Compliance preparation", description: "Document controls and close obvious gaps before larger reviews.", icon: ShieldCheck },
    ],
  },
  "ui-ux-design": {
    problemTitle: "Turn confusing interfaces into clear, usable product experiences.",
    problemDescription: "We improve flows, hierarchy, component consistency, accessibility, mobile states, and conversion paths.",
    problemNote: "Built for clarity, trust, usability, and developer-ready handoff.",
    deliverableTitle: "A design system and screen set that teams can build from.",
    deliverableDescription: "Design work is shaped around user flows, reusable components, responsive states, prototypes, and practical handoff.",
    deliverableNote: "Polish with purpose, not decoration for its own sake.",
    processTitle: "A UI/UX process from product clarity to polished handoff.",
    processDescription: "We map user intent, wireframe flows, refine visuals, prototype interactions, and package build-ready design assets.",
    useCaseTitle: "Design support for products that need clarity and confidence.",
    useCaseDescription: "Useful when users feel lost, dashboards feel crowded, mobile screens are weak, or conversion flow is unclear.",
    bestForNote: "Best when better UX can improve adoption, trust, and conversion.",
    problems: [
      { title: "Users cannot find the next action", description: "We simplify information architecture, CTAs, hierarchy, and page flow.", icon: MousePointerClick },
      { title: "Screens feel inconsistent", description: "Reusable components, spacing, color roles, and states create a calmer product system.", icon: Component },
      { title: "Mobile UX is an afterthought", description: "Layouts, tap targets, forms, menus, and states are designed for real mobile usage.", icon: Smartphone },
      { title: "Handoff creates confusion", description: "Developer-ready specs, components, and responsive notes reduce build ambiguity.", icon: FileCheck2 },
    ],
    deliverables: [
      { title: "UX flow map", description: "Core journeys, user decisions, states, and information hierarchy.", icon: Workflow },
      { title: "Wireframes", description: "Low-fidelity layouts to solve structure before visual polish.", icon: Layers3 },
      { title: "High-fidelity UI screens", description: "Polished product, website, dashboard, or app screens with responsive care.", icon: Palette },
      { title: "Design system basics", description: "Typography, colors, components, buttons, forms, cards, and usage rules.", icon: Component },
      { title: "Interactive prototype", description: "Clickable flows to review behavior before development.", icon: MousePointerClick },
      { title: "Developer handoff", description: "Assets, specs, spacing, states, and implementation notes.", icon: FileCheck2 },
    ],
    process: [
      { title: "UX discovery", description: "Understand users, goals, friction points, business outcomes, and product constraints.", icon: Search },
      { title: "Flow and wireframe", description: "Shape navigation, hierarchy, key screens, and task completion paths.", icon: Layers3 },
      { title: "Visual design system", description: "Create polished UI language, components, states, and responsive patterns.", icon: Palette },
      { title: "Prototype and review", description: "Test flow logic, interactions, readability, and stakeholder feedback.", icon: MousePointerClick },
      { title: "Handoff package", description: "Prepare specs, assets, components, and dev notes for implementation.", icon: FileCheck2 },
    ],
    useCases: [
      { title: "SaaS dashboard redesign", description: "Reduce clutter and make metrics, actions, and workflows easier to scan.", icon: BarChart3 },
      { title: "Mobile app UX", description: "Design onboarding, navigation, task flows, and touch-friendly screens.", icon: Smartphone },
      { title: "Conversion page design", description: "Improve trust, offer clarity, section flow, and lead generation.", icon: Target },
      { title: "Design system foundation", description: "Create reusable UI patterns for a growing product team.", icon: Component },
    ],
  },
  "landing-pages-campaigns": {
    problemTitle: "Make campaign traffic land on pages built to convert.",
    problemDescription: "We build pages with offer clarity, proof, lead forms, tracking, fast loading, and follow-up handoff.",
    problemNote: "Built for ads, launches, funnels, and measurable lead capture.",
    deliverableTitle: "A landing page system for campaign performance.",
    deliverableDescription: "Each page is built around one offer, one audience, one conversion path, and the tracking needed to improve it.",
    deliverableNote: "Designed for conversions, not just impressions.",
    processTitle: "A campaign page process from offer to measurable launch.",
    processDescription: "We clarify the audience, shape the offer, build the page, wire tracking, test forms, and prepare follow-up.",
    useCaseTitle: "Landing pages for paid campaigns and focused offers.",
    useCaseDescription: "Useful when traffic is expensive and the page must convert quickly, clearly, and measurably.",
    bestForNote: "Best when campaigns need dedicated pages, forms, and conversion tracking.",
    problems: [
      { title: "Ad traffic lands on generic pages", description: "Dedicated pages match campaign intent and remove distracting navigation paths.", icon: Megaphone },
      { title: "Offer is not clear fast enough", description: "Hero, proof, benefits, objections, and CTA flow are structured for quick understanding.", icon: Target },
      { title: "Lead tracking is missing", description: "Events, pixels, UTM handling, and CRM capture make results easier to measure.", icon: Waypoints },
      { title: "Forms create friction", description: "Forms, validation, thank-you states, and follow-up flows are kept focused.", icon: FileCheck2 },
    ],
    deliverables: [
      { title: "Campaign landing page", description: "A focused page built around audience, offer, proof, and conversion action.", icon: Globe2 },
      { title: "Lead capture flow", description: "Forms, thank-you state, CRM handoff, email notification, and tracking events.", icon: FileCheck2 },
      { title: "Conversion section system", description: "Hero, benefits, proof, FAQ, objections, offer details, and CTA blocks.", icon: Target },
      { title: "Analytics and pixels", description: "Google Analytics, Meta Pixel, conversion events, and campaign tracking setup.", icon: BarChart3 },
      { title: "A/B testing readiness", description: "Variant-friendly structure for testing offers, headlines, CTAs, or sections.", icon: Activity },
      { title: "Follow-up automation", description: "Lead routing, email alerts, CRM capture, and post-submit actions.", icon: Mail },
    ],
    process: [
      { title: "Campaign goal clarity", description: "Define audience, offer, source, conversion event, and success metric.", icon: Target },
      { title: "Message and page plan", description: "Plan headline, proof, objections, CTA flow, and form strategy.", icon: Megaphone },
      { title: "Design and build", description: "Create a fast, responsive, campaign-specific landing page.", icon: Code2 },
      { title: "Tracking and QA", description: "Validate forms, pixels, analytics, events, responsiveness, and loading behavior.", icon: Waypoints },
      { title: "Launch and improve", description: "Review traffic behavior and refine sections, CTAs, or offer positioning.", icon: LineChart },
    ],
    useCases: [
      { title: "Google Ads landing page", description: "Match keyword intent with clear proof, fast load, and focused lead capture.", icon: Search },
      { title: "Meta campaign funnel", description: "Turn social ad clicks into enquiries with a visual, mobile-first offer page.", icon: Megaphone },
      { title: "Product launch page", description: "Present a new offer, collect leads, and measure launch interest.", icon: Rocket },
      { title: "Event or consultation funnel", description: "Capture bookings, confirm submissions, and route leads for follow-up.", icon: CalendarCheck },
    ],
  },
  "seo-analytics": {
    problemTitle: "Make search visibility and growth data easier to act on.",
    problemDescription: "We improve technical SEO, schema, indexing, tracking, dashboards, and conversion measurement.",
    problemNote: "Built for discoverability, analytics clarity, and better decisions.",
    deliverableTitle: "An SEO and analytics foundation for measurable growth.",
    deliverableDescription: "The setup connects technical search health with dashboards, tracking, reporting, and practical optimization priorities.",
    deliverableNote: "Growth becomes easier to inspect and improve.",
    processTitle: "An SEO and analytics process from audit to reporting.",
    processDescription: "We review technical issues, tracking gaps, content opportunities, schema, speed, and reporting needs.",
    useCaseTitle: "SEO and analytics for websites that need measurable growth.",
    useCaseDescription: "Useful when traffic, indexing, conversions, and reporting need better structure.",
    bestForNote: "Best when the team wants clearer growth signals instead of guesswork.",
    problems: [
      { title: "Pages are not indexed properly", description: "Technical checks find sitemap, robots, canonical, metadata, and crawl issues.", icon: Search },
      { title: "Analytics does not answer business questions", description: "Events and dashboards focus on enquiries, traffic sources, and conversion behavior.", icon: BarChart3 },
      { title: "Search snippets are weak", description: "Schema, titles, descriptions, and content structure improve how pages appear in search.", icon: Tags },
      { title: "Performance hurts rankings", description: "Speed, Core Web Vitals, and technical cleanup support better user experience.", icon: Gauge },
    ],
    deliverables: [
      { title: "Technical SEO audit", description: "Review indexing, metadata, headings, links, schema, speed, and crawl health.", icon: FileSearch },
      { title: "Schema and metadata setup", description: "Structured data, page titles, descriptions, OG tags, and canonical basics.", icon: Tags },
      { title: "Analytics event plan", description: "Track enquiries, CTA clicks, form submissions, lead sources, and campaign behavior.", icon: Waypoints },
      { title: "Search Console setup", description: "Sitemap submission, indexing checks, query review, and issue monitoring.", icon: Search },
      { title: "Reporting dashboard", description: "Traffic, source, conversion, ranking, and page performance views.", icon: BarChart3 },
      { title: "Optimization roadmap", description: "Prioritized technical, content, and conversion improvements.", icon: LineChart },
    ],
    process: [
      { title: "Search and tracking audit", description: "Find indexing, metadata, speed, schema, and analytics gaps.", icon: FileSearch },
      { title: "Measurement plan", description: "Define events, conversions, sources, dashboards, and reporting questions.", icon: Waypoints },
      { title: "Technical implementation", description: "Add metadata, schema, sitemap, robots, event tracking, and dashboard setup.", icon: Code2 },
      { title: "Validation", description: "Check Search Console, analytics events, page speed, and tracking accuracy.", icon: CheckCircle2 },
      { title: "Reporting rhythm", description: "Provide clear insights and next optimization priorities.", icon: BarChart3 },
    ],
    useCases: [
      { title: "Service website SEO", description: "Improve technical foundations for service pages, local pages, and lead content.", icon: Globe2 },
      { title: "Campaign analytics", description: "Track paid traffic, landing page events, forms, and conversion quality.", icon: Megaphone },
      { title: "Content performance dashboard", description: "Understand which pages bring traffic, engagement, and enquiries.", icon: BarChart3 },
      { title: "Technical SEO cleanup", description: "Fix crawl issues, metadata gaps, schema, speed, and indexing blockers.", icon: Search },
    ],
  },
  "brand-identity": {
    problemTitle: "Give the brand a system instead of scattered visuals.",
    problemDescription: "We create logo usage, colors, typography, templates, visual direction, and digital identity rules that stay consistent.",
    problemNote: "Built for credibility, recall, and practical reuse across channels.",
    deliverableTitle: "A brand identity kit your team can actually use.",
    deliverableDescription: "The identity system is designed for websites, social posts, decks, ads, documents, and product surfaces.",
    deliverableNote: "A cleaner visual language for every customer touchpoint.",
    processTitle: "A brand identity process from direction to reusable assets.",
    processDescription: "We define positioning cues, explore visual direction, refine identity elements, and package usable guidelines.",
    useCaseTitle: "Brand identity for businesses that need a more credible presence.",
    useCaseDescription: "Useful when the company is launching, repositioning, or trying to look more consistent across digital channels.",
    bestForNote: "Best when the business needs a recognizable, professional visual system.",
    problems: [
      { title: "Visuals feel inconsistent", description: "Colors, type, spacing, icon style, and templates become part of one reusable system.", icon: Palette },
      { title: "Logo usage is unclear", description: "Logo variants, spacing, backgrounds, and do-not-use examples reduce brand drift.", icon: PenTool },
      { title: "Marketing assets take too long", description: "Reusable templates speed up social posts, decks, ads, and website graphics.", icon: Boxes },
      { title: "Brand does not feel premium", description: "A clearer visual direction makes the business look more credible and intentional.", icon: Sparkles },
    ],
    deliverables: [
      { title: "Logo system", description: "Primary, secondary, icon, mono, and usage variations where needed.", icon: PenTool },
      { title: "Color and typography system", description: "Accessible color roles, type pairing, hierarchy, and usage guidance.", icon: TypeIcon },
      { title: "Brand guidelines", description: "Practical rules for visual consistency across website, decks, and social media.", icon: FileCheck2 },
      { title: "Social and content templates", description: "Reusable post, story, carousel, or campaign template directions.", icon: Megaphone },
      { title: "Icon and graphic style", description: "Simple visual elements that make brand assets feel connected.", icon: Component },
      { title: "Website identity direction", description: "Hero style, UI tone, section language, and digital brand application.", icon: Globe2 },
    ],
    process: [
      { title: "Brand discovery", description: "Understand audience, positioning, personality, competitors, and visual expectations.", icon: Search },
      { title: "Visual direction", description: "Explore color, typography, logo tone, composition, and digital feel.", icon: Palette },
      { title: "Identity refinement", description: "Refine logo, type, color, graphic rules, and reusable components.", icon: PenTool },
      { title: "Template creation", description: "Prepare practical assets for social, web, decks, and communication use.", icon: Boxes },
      { title: "Guidelines and handoff", description: "Package the system with usage notes and editable/source assets.", icon: FileCheck2 },
    ],
    useCases: [
      { title: "Startup brand launch", description: "Create a credible identity before website, pitch deck, and campaigns go live.", icon: Rocket },
      { title: "Service business refresh", description: "Modernize visuals so the company feels more trustworthy and premium.", icon: Building2 },
      { title: "Social media consistency", description: "Give teams templates and rules for clean, repeatable content.", icon: Megaphone },
      { title: "Website identity system", description: "Translate the brand into digital UI, sections, colors, and components.", icon: Globe2 },
    ],
  },
};

const fallbackIcons = [Sparkles, CheckCircle2, Workflow, Boxes, Target, Rocket];

function makeFallbackCards(items: string[], descriptions: string[]): ServiceDetailCard[] {
  return items.map((title, index) => ({
    title,
    description: descriptions[index % descriptions.length],
    icon: fallbackIcons[index % fallbackIcons.length],
  }));
}

export function getServicePageDetails(service: ServiceItem): ServicePageDetails {
  const detail = servicePageDetails[service.id];

  if (detail) {
    return detail;
  }

  return {
    problemTitle: `Solve the operational friction around ${service.title.toLowerCase()}.`,
    problemDescription: service.fullDescription,
    problemNote: "Mapped into a practical delivery plan with visible outcomes.",
    deliverableTitle: `A complete ${service.title.toLowerCase()} delivery scope.`,
    deliverableDescription: service.shortDescription,
    deliverableNote: "Built for launch, handoff, and long-term maintainability.",
    processTitle: "A structured delivery process from discovery to launch.",
    processDescription: "Each stage is planned around clarity, build quality, QA, rollout, and support.",
    useCaseTitle: "Real situations where this service fits.",
    useCaseDescription: service.bestFor,
    bestForNote: "Best when the project needs practical execution and clear ownership.",
    problems: makeFallbackCards(service.problems, [
      "We turn this blocker into a clear workflow, interface, or system improvement.",
      "The work is scoped around practical outcomes your team can use after launch.",
    ]),
    deliverables: makeFallbackCards(service.whatWeBuild, [
      "A launch-ready deliverable with clear ownership and practical handoff.",
      "A usable part of the service scope designed for day-to-day business value.",
    ]),
    process: makeFallbackCards(service.process, [
      "A focused stage with clear decisions, outputs, and review points.",
      "A structured step that keeps delivery visible and aligned.",
    ]),
    useCases: makeFallbackCards(service.useCases, [
      "A practical business situation where this service can create measurable value.",
      "A focused application for teams that need better systems and clearer execution.",
    ]),
  };
}
