import type { LucideIcon } from "lucide-react";
import {
  Activity,
  BarChart3,
  Bell,
  Bot,
  Boxes,
  Braces,
  Brush,
  ChartNoAxesCombined,
  Cloud,
  Code2,
  Component,
  CreditCard,
  Database,
  FileCheck2,
  FileSearch,
  Figma,
  GitBranch,
  Globe2,
  KeyRound,
  Layers3,
  LineChart,
  LockKeyhole,
  Mail,
  Map,
  MessageCircle,
  MonitorCheck,
  MousePointerClick,
  Palette,
  PenTool,
  PlugZap,
  Rocket,
  Search,
  ServerCog,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Tags,
  TestTube2,
  Type,
  Waypoints,
  Workflow,
  Zap,
} from "lucide-react";

export type ServiceToolStack = {
  eyebrow: string;
  title: string;
  description: string;
  tools: Array<{
    name: string;
    icon: LucideIcon;
  }>;
};

const defaultToolStack: ServiceToolStack = {
  eyebrow: "Delivery Stack",
  title: "Tools and systems we use to ship cleanly.",
  description: "A practical stack selected around your project scope, team workflow, launch timeline, and long-term maintainability.",
  tools: [
    { name: "Discovery", icon: Search },
    { name: "Architecture", icon: Boxes },
    { name: "Build", icon: Code2 },
    { name: "QA", icon: TestTube2 },
    { name: "Launch", icon: Rocket },
    { name: "Support", icon: MonitorCheck },
  ],
};

export const serviceToolStacks: Record<string, ServiceToolStack> = {
  "web-development": {
    eyebrow: "Tech Stack",
    title: "Modern frontend stack for fast, conversion-ready websites.",
    description: "Built with performance, responsive UI, SEO structure, animation quality, and production deployment in mind.",
    tools: [
      { name: "Next.js", icon: Code2 },
      { name: "React", icon: Component },
      { name: "TypeScript", icon: Braces },
      { name: "Tailwind CSS", icon: Palette },
      { name: "Node.js", icon: ServerCog },
      { name: "MongoDB", icon: Database },
      { name: "PostgreSQL", icon: Database },
      { name: "Vercel", icon: Cloud },
      { name: "Framer Motion", icon: Sparkles },
      { name: "SEO Schema", icon: Tags },
    ],
  },
  "saas-development": {
    eyebrow: "SaaS Stack",
    title: "Product stack for subscriptions, roles, dashboards, and scale.",
    description: "A SaaS foundation that handles product workflows, user access, revenue operations, and measurable growth.",
    tools: [
      { name: "Next.js", icon: Code2 },
      { name: "React", icon: Component },
      { name: "Node.js", icon: ServerCog },
      { name: "PostgreSQL", icon: Database },
      { name: "MongoDB", icon: Database },
      { name: "Stripe / Razorpay", icon: CreditCard },
      { name: "Auth.js / JWT", icon: KeyRound },
      { name: "Redis", icon: Database },
      { name: "AWS / Vercel", icon: Cloud },
      { name: "Analytics", icon: BarChart3 },
    ],
  },
  "mobile-app-development": {
    eyebrow: "Mobile Stack",
    title: "Mobile tools for smooth UX, secure APIs, and launch readiness.",
    description: "A practical app stack for cross-platform builds, native quality, notifications, payments, maps, and store release support.",
    tools: [
      { name: "Flutter", icon: Smartphone },
      { name: "React Native", icon: Component },
      { name: "Kotlin", icon: Code2 },
      { name: "Swift", icon: Code2 },
      { name: "Firebase", icon: Cloud },
      { name: "Node.js APIs", icon: ServerCog },
      { name: "Push Notifications", icon: Bell },
      { name: "Razorpay / Stripe", icon: CreditCard },
      { name: "Google Maps APIs", icon: Map },
      { name: "App Store / Play Store", icon: Rocket },
    ],
  },
  "custom-crm-systems": {
    eyebrow: "CRM Stack",
    title: "Owned CRM foundation for pipelines, dashboards, roles, and automation.",
    description: "A modular stack for custom CRM workflows, reporting, permissions, customer records, and business-specific automation.",
    tools: [
      { name: "Next.js", icon: Code2 },
      { name: "React", icon: Component },
      { name: "Node.js", icon: ServerCog },
      { name: "MongoDB", icon: Database },
      { name: "PostgreSQL", icon: Database },
      { name: "Role-Based Access", icon: LockKeyhole },
      { name: "Dashboards", icon: BarChart3 },
      { name: "Reports", icon: FileCheck2 },
      { name: "Workflow Automation", icon: Workflow },
      { name: "AI Insights", icon: Bot },
    ],
  },
  "ai-automation": {
    eyebrow: "AI Automation Stack",
    title: "AI tools for agents, retrieval, scoring, and workflow intelligence.",
    description: "A controlled AI layer that turns business data, documents, messages, and CRM events into useful actions.",
    tools: [
      { name: "OpenAI / LLMs", icon: Bot },
      { name: "LangChain", icon: Workflow },
      { name: "RAG", icon: FileSearch },
      { name: "Vector DB", icon: Database },
      { name: "Workflow Agents", icon: Sparkles },
      { name: "CRM AI Insights", icon: BarChart3 },
      { name: "Auto Replies", icon: MessageCircle },
      { name: "Document Intelligence", icon: FileCheck2 },
      { name: "Lead Scoring", icon: Activity },
      { name: "Analytics", icon: ChartNoAxesCombined },
    ],
  },
  "workflow-automation": {
    eyebrow: "Automation Stack",
    title: "Workflow tools for triggers, reminders, approvals, and reporting.",
    description: "A connected automation layer that moves work through the right sequence without manual handoffs.",
    tools: [
      { name: "n8n", icon: Workflow },
      { name: "Make", icon: Sparkles },
      { name: "Zapier", icon: Zap },
      { name: "Webhooks", icon: PlugZap },
      { name: "Cron Jobs", icon: Activity },
      { name: "Email Automation", icon: Mail },
      { name: "WhatsApp Automation", icon: MessageCircle },
      { name: "CRM Triggers", icon: Bell },
      { name: "Approval Flows", icon: FileCheck2 },
      { name: "Reporting", icon: BarChart3 },
    ],
  },
  "api-development": {
    eyebrow: "API Stack",
    title: "Backend tools for secure, documented, integration-ready APIs.",
    description: "A backend foundation that connects products, data, auth, webhooks, gateways, and third-party platforms cleanly.",
    tools: [
      { name: "REST APIs", icon: Braces },
      { name: "GraphQL", icon: Workflow },
      { name: "Webhooks", icon: PlugZap },
      { name: "JWT Auth", icon: KeyRound },
      { name: "OAuth", icon: LockKeyhole },
      { name: "Rate Limiting", icon: Activity },
      { name: "Swagger Docs", icon: FileCheck2 },
      { name: "API Gateway", icon: ServerCog },
      { name: "Node.js", icon: Code2 },
      { name: "PostgreSQL / MongoDB", icon: Database },
    ],
  },
  "integration-services": {
    eyebrow: "Integration Stack",
    title: "Connectors and platforms that keep business data in sync.",
    description: "A reliable integration hub for messaging, payments, CRMs, sheets, analytics, ERPs, and custom tools.",
    tools: [
      { name: "WhatsApp API", icon: MessageCircle },
      { name: "Google Sheets", icon: FileCheck2 },
      { name: "CRMs", icon: Boxes },
      { name: "Payment Gateways", icon: CreditCard },
      { name: "Email APIs", icon: Mail },
      { name: "Webhooks", icon: PlugZap },
      { name: "ERP Integrations", icon: ServerCog },
      { name: "Analytics Tools", icon: BarChart3 },
      { name: "Zapier / n8n", icon: Workflow },
      { name: "Custom Connectors", icon: Braces },
    ],
  },
  "devops-deployment": {
    eyebrow: "DevOps Tools",
    title: "Release tooling for safe deploys, rollback, logs, and monitoring.",
    description: "A release setup that makes production deployments predictable, observable, and easier to recover.",
    tools: [
      { name: "GitHub Actions", icon: GitBranch },
      { name: "Docker", icon: Boxes },
      { name: "Vercel", icon: Cloud },
      { name: "AWS", icon: Cloud },
      { name: "Render", icon: Cloud },
      { name: "CI/CD", icon: Workflow },
      { name: "Monitoring", icon: MonitorCheck },
      { name: "Rollbacks", icon: Activity },
      { name: "Logs", icon: FileCheck2 },
      { name: "Environment Management", icon: KeyRound },
    ],
  },
  "cloud-infrastructure": {
    eyebrow: "Cloud Tools",
    title: "Cloud infrastructure tools for hosting, storage, backups, and scale.",
    description: "A practical production setup for apps, databases, assets, backups, cost control, and monitoring.",
    tools: [
      { name: "AWS", icon: Cloud },
      { name: "Vercel", icon: Cloud },
      { name: "Render", icon: Cloud },
      { name: "Docker", icon: Boxes },
      { name: "MongoDB Atlas", icon: Database },
      { name: "PostgreSQL", icon: Database },
      { name: "CDN", icon: Globe2 },
      { name: "Storage", icon: ServerCog },
      { name: "Backups", icon: FileCheck2 },
      { name: "Monitoring", icon: MonitorCheck },
    ],
  },
  "maintenance-support": {
    eyebrow: "Support Stack",
    title: "Maintenance systems for uptime, fixes, updates, and monthly care.",
    description: "A support flow that protects live products after launch with visibility, response, and continuous improvement.",
    tools: [
      { name: "Uptime Monitoring", icon: MonitorCheck },
      { name: "Error Tracking", icon: Activity },
      { name: "Logs", icon: FileCheck2 },
      { name: "Bug Fixing", icon: Braces },
      { name: "Version Updates", icon: GitBranch },
      { name: "Security Patches", icon: ShieldCheck },
      { name: "Performance Review", icon: BarChart3 },
      { name: "Backup Checks", icon: Cloud },
      { name: "SLA Support", icon: Bell },
      { name: "Monthly Reports", icon: ChartNoAxesCombined },
    ],
  },
  "security-compliance": {
    eyebrow: "Security Stack",
    title: "Security controls for access, APIs, audits, and data protection.",
    description: "A practical security layer for growing products that need stronger control and clearer accountability.",
    tools: [
      { name: "RBAC", icon: LockKeyhole },
      { name: "JWT / OAuth", icon: KeyRound },
      { name: "API Protection", icon: ShieldCheck },
      { name: "Rate Limiting", icon: Activity },
      { name: "Audit Logs", icon: FileCheck2 },
      { name: "Data Encryption", icon: LockKeyhole },
      { name: "Secure Headers", icon: ShieldCheck },
      { name: "Backup Policy", icon: Cloud },
      { name: "Access Control", icon: KeyRound },
      { name: "Compliance Checks", icon: FileSearch },
    ],
  },
  "ui-ux-design": {
    eyebrow: "Design Tools",
    title: "Design tools for flows, prototypes, systems, and usability.",
    description: "A design workflow that turns unclear product ideas into polished, usable, developer-ready interfaces.",
    tools: [
      { name: "Figma", icon: Figma },
      { name: "Design Systems", icon: Component },
      { name: "Wireframes", icon: Layers3 },
      { name: "Prototypes", icon: MousePointerClick },
      { name: "User Flows", icon: Workflow },
      { name: "Mobile UI", icon: Smartphone },
      { name: "Dashboard UI", icon: BarChart3 },
      { name: "Accessibility", icon: ShieldCheck },
      { name: "Motion Design", icon: Sparkles },
      { name: "Usability Review", icon: Search },
    ],
  },
  "landing-pages-campaigns": {
    eyebrow: "Campaign Tools",
    title: "Growth tools for campaign launches, lead capture, and tracking.",
    description: "A conversion setup for paid campaigns, product launches, offer pages, lead forms, and follow-up flows.",
    tools: [
      { name: "Next.js", icon: Code2 },
      { name: "Framer Motion", icon: Sparkles },
      { name: "Lead Forms", icon: FileCheck2 },
      { name: "Analytics", icon: BarChart3 },
      { name: "A/B Testing", icon: TestTube2 },
      { name: "Meta Pixel", icon: Activity },
      { name: "Google Ads", icon: Search },
      { name: "Conversion Tracking", icon: Waypoints },
      { name: "CRM Capture", icon: Boxes },
      { name: "Email Follow-up", icon: Mail },
    ],
  },
  "seo-analytics": {
    eyebrow: "SEO & Analytics Tools",
    title: "Measurement tools for visibility, traffic, and conversion clarity.",
    description: "A growth measurement layer for search, technical SEO, schema, tracking, reporting, and optimization decisions.",
    tools: [
      { name: "Google Search Console", icon: Search },
      { name: "Google Analytics", icon: BarChart3 },
      { name: "Schema Markup", icon: Tags },
      { name: "Technical SEO", icon: FileSearch },
      { name: "Sitemap", icon: Globe2 },
      { name: "Robots", icon: Bot },
      { name: "Keyword Strategy", icon: FileSearch },
      { name: "Page Speed", icon: Activity },
      { name: "Conversion Tracking", icon: Waypoints },
      { name: "Reporting Dashboard", icon: ChartNoAxesCombined },
    ],
  },
  "brand-identity": {
    eyebrow: "Brand System",
    title: "Identity tools for colors, type, assets, and digital consistency.",
    description: "A practical visual system that gives your business a recognizable, credible, and reusable digital identity.",
    tools: [
      { name: "Logo System", icon: PenTool },
      { name: "Color Palette", icon: Palette },
      { name: "Typography", icon: Type },
      { name: "Brand Guidelines", icon: FileCheck2 },
      { name: "Social Templates", icon: Brush },
      { name: "Icon System", icon: Component },
      { name: "Pitch Deck Style", icon: Layers3 },
      { name: "Visual Direction", icon: Sparkles },
      { name: "Brand Assets", icon: Boxes },
      { name: "Website Identity", icon: Globe2 },
    ],
  },
};

export function getServiceToolStack(serviceId: string) {
  return serviceToolStacks[serviceId] ?? defaultToolStack;
}
