import {
  BadgeCheck,
  BarChart3,
  BriefcaseBusiness,
  Building2,
  CalendarCheck,
  Car,
  ClipboardCheck,
  ClipboardList,
  CreditCard,
  Factory,
  FileCheck2,
  FileText,
  GraduationCap,
  Handshake,
  HeartPulse,
  Landmark,
  LifeBuoy,
  Mail,
  MapPin,
  MessageCircle,
  PackageCheck,
  Phone,
  Plane,
  ReceiptText,
  Route,
  School,
  Settings2,
  ShieldCheck,
  ShoppingBag,
  Store,
  Tags,
  Truck,
  UserCheck,
  Users,
  WalletCards,
  Workflow,
  Wrench,
} from "lucide-react";
import type { IndustryCRMConfig, IndustryPricingPlan } from "./IndustryCRMTemplate";

const inr = "\u20b9";

function plans(
  focus: string,
  starter: string[],
  growth: string[],
  ai: string[],
  enterprise: string[]
): IndustryPricingPlan[] {
  return [
    {
      name: "Starter CRM",
      tag: "Lead management",
      desc: `For teams starting with ${focus} lead capture, customer records, follow-ups, and a basic manager dashboard.`,
      price: `${inr}99,999`,
      note: "Best for getting started quickly",
      features: starter,
    },
    {
      name: "Growth CRM",
      tag: "Workflow ready",
      desc: `For growing teams that need custom ${focus} fields, role permissions, automation, reports, and team dashboards.`,
      price: `${inr}1,99,999`,
      note: "For growing operations",
      popular: true,
      features: growth,
    },
    {
      name: "AI-Powered CRM",
      tag: "AI assistant",
      desc: `For teams that want AI lead scoring, smart suggestions, auto message drafts, daily planning, and report explanations for ${focus}.`,
      price: `${inr}4,99,999`,
      note: "Advanced AI capabilities included",
      features: ai,
    },
    {
      name: "Enterprise Custom CRM",
      tag: "Complex operations",
      desc: `For multi-branch or complex ${focus} workflows with integrations, advanced permissions, and scalable architecture.`,
      price: "Custom",
      note: "Tailored as per requirements",
      features: enterprise,
    },
  ];
}

const realEstateImages = [
  "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1554469384-e58fac16e23a?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=85",
];

export const realEstateConfig: IndustryCRMConfig = {
  badge: "Real Estate CRM",
  headline: ["Real Estate CRM", "Built to Close", "More Deals"],
  description:
    "Manage property inquiries, site visits, follow-ups, broker teams, inventory, customer documents, payment stages, and sales pipelines in one smart CRM.",
  heroImage: realEstateImages[0],
  heroAlt: "Modern real estate property and sales workspace",
  accent: "#0f9f91",
  accentDark: "#075f63",
  accentSoft: "#e1f7f5",
  stats: [
    { label: "New Leads", value: "1,248", delta: "14.2% vs yesterday" },
    { label: "Site Visits", value: "186", delta: "9.8% vs yesterday" },
    { label: "Active Deals", value: "74", delta: "11.4% this week" },
    { label: "Bookings", value: "32", delta: "7.6% this week" },
  ],
  nextCard: {
    label: "Next Site Visit",
    name: "Aarav Mehta",
    description: "3 BHK Premium Tower",
    detail: "11:30 AM - Sales Executive Riya",
    status: "Confirmed",
  },
  trustBadges: [
    { label: "Site Visits", sub: "Calendar booking", icon: CalendarCheck },
    { label: "Inventory", sub: "Unit availability", icon: Building2 },
    { label: "Brokers", sub: "Channel tracking", icon: Handshake },
    { label: "Payments", sub: "Milestone view", icon: CreditCard },
  ],
  whyTitle: "Why Real Estate Teams Choose HNX CRM Systems",
  whySubtitle: "Built for builders, brokers, channel partners, and property sales teams",
  whyCards: [
    { title: "Lead Source Clarity", text: "Track portal, ad, WhatsApp, call, referral, and walk-in inquiries.", icon: Users },
    { title: "Visit Discipline", text: "Schedule visits, assign executives, and reduce missed follow-ups.", icon: CalendarCheck },
    { title: "Inventory Control", text: "Connect inquiries with available units, price bands, and project stages.", icon: Building2 },
    { title: "Broker Visibility", text: "Manage partner leads, commissions, activities, and deal ownership.", icon: Handshake },
    { title: "Payment Tracking", text: "Monitor booking amount, agreement, loan, and possession milestones.", icon: WalletCards },
  ],
  specialtyTitle: "Built for Every Real Estate Sales Model",
  specialtyCards: [
    { title: "Builders & Developers", text: "Project inventory, site visits, booking stages, and buyer documents.", image: realEstateImages[1], icon: Building2 },
    { title: "Broker Teams", text: "Lead assignment, owner tracking, buyer follow-ups, and closure reports.", image: realEstateImages[2], icon: Users },
    { title: "Channel Partners", text: "Partner-wise leads, commissions, activity logs, and shared pipelines.", image: realEstateImages[3], icon: Handshake },
    { title: "Property Dealers", text: "Buyer preferences, listings, site visits, and negotiation history.", image: realEstateImages[4], icon: MapPin },
    { title: "Rental Agencies", text: "Tenant inquiries, owner follow-ups, visit slots, and document collection.", image: realEstateImages[0], icon: FileText },
  ],
  dashboard: {
    title: "All-in-One Real Estate Dashboard",
    dateLabel: "This Month",
    sidebar: ["Dashboard", "Leads", "Properties", "Site Visits", "Brokers", "Deals", "Documents", "Payments", "Reports", "Settings"],
    chartTitle: "Site Visit & Booking Trend",
    sourceTitle: "Top Lead Sources",
    sources: ["Property Portal 35%", "Meta Ads 24%", "Google Ads 18%", "Broker 15%", "Walk-in 8%"],
    rowsTitle: "Recent Property Leads",
    rows: [
      ["Aarav Mehta", "3 BHK Inquiry", "Today, 11:30 AM", "Visit Set"],
      ["Neha Kapoor", "Villa Buyer", "Today, 01:00 PM", "Follow-up"],
      ["Rohan Shah", "Plot Inquiry", "Tomorrow, 10:00 AM", "Qualified"],
      ["Isha Rao", "2 BHK Buyer", "Tomorrow, 12:30 PM", "Negotiation"],
    ],
    taskTitle: "Deal Tasks",
    tasks: [
      ["Share floor plan with Neha Kapoor", "Due in 25 mins"],
      ["Confirm broker commission for Rohan Shah", "Due today"],
      ["Collect PAN and address proof for booking", "Due tomorrow"],
    ],
  },
  journeyTitle: "Buyer Journey - Simplified & Automated",
  journeySubtitle: "From inquiry to booking, every buyer step stays visible",
  journey: [
    { title: "Lead Captured", text: "Capture leads from portals, ads, WhatsApp, calls, and walk-ins.", icon: Users },
    { title: "Requirement Mapped", text: "Record budget, location, property type, and urgency.", icon: ClipboardList },
    { title: "Site Visit Scheduled", text: "Assign sales executive and send reminders automatically.", icon: CalendarCheck },
    { title: "Deal Followed Up", text: "Track negotiation, documents, loan status, and payment stage.", icon: Workflow },
    { title: "Booking Closed", text: "Move the buyer to booking, agreement, and possession workflows.", icon: BadgeCheck },
  ],
  featureTitle: "Powerful Modules for",
  featureSubtitle: "Real Estate Sales",
  leftFeatures: ["Property lead pipeline", "Site visit scheduling", "Inventory and unit tracking", "Broker and partner management", "Buyer document checklist"],
  rightFeatures: ["Payment milestone tracking", "Loan follow-up workflow", "WhatsApp buyer reminders", "Project-wise sales reports", "Role-based team dashboards"],
  operationsTitle: "More Than Leads - Built for Real Estate Operations",
  operationsSubtitle:
    "HNX CRM Systems connects sales executives, brokers, managers, documents, inventory, visits, and payments so real estate teams can move faster without losing buyer context.",
  operations: [
    { title: "Lead Capture Engine", text: "Bring portal, ad, website, WhatsApp, and call leads into one qualified sales pipeline.", icon: Users },
    { title: "Visit Scheduler", text: "Plan site visits, assign team members, and keep buyers updated before the visit.", icon: CalendarCheck },
    { title: "Inventory Tracker", text: "Track towers, floors, units, availability, pricing, and buyer interest.", icon: Building2 },
    { title: "Broker Management", text: "Monitor broker leads, deal ownership, partner performance, and payouts.", icon: Handshake },
    { title: "Payment Milestones", text: "Follow booking amount, agreement, loan, installment, and possession stages.", icon: CreditCard },
    { title: "Document Collection", text: "Maintain buyer KYC, booking forms, agreements, and loan documents in one view.", icon: FileCheck2 },
  ],
  pricingIntro:
    "Real estate CRM pricing depends on your projects, inventory fields, broker rules, site visit workflow, payment stages, reports, integrations, and AI requirements.",
  pricingPlans: plans(
    "real estate",
    ["Property leads", "Site visit tasks", "Basic project dashboard", "Simple user roles"],
    ["Inventory fields", "Broker dashboard", "Payment milestones", "Advanced reports", "Automation rules"],
    ["AI lead scoring", "Smart buyer follow-ups", "Auto message drafts", "Daily sales planning", "Report explanations"],
    ["Multi-project control", "Portal integrations", "Advanced permissions", "Custom booking workflows"]
  ),
  integrations: [
    { name: "WhatsApp", sub: "Buyer updates", icon: MessageCircle },
    { name: "Email", sub: "Brochures", icon: Mail },
    { name: "Telephony", sub: "Call logs", icon: Phone },
    { name: "Sheets", sub: "Imports", icon: FileText },
    { name: "Meta Ads", sub: "Lead forms", icon: Users },
    { name: "Google Ads", sub: "Campaigns", icon: BarChart3 },
    { name: "Payments", sub: "Gateway", icon: CreditCard },
    { name: "Maps", sub: "Locations", icon: MapPin },
    { name: "Portals", sub: "Property leads", icon: Building2 },
  ],
};

const educationImages = [
  "https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=900&q=85",
];

export const educationConfig: IndustryCRMConfig = {
  badge: "Education CRM",
  headline: ["Education CRM", "Built for Admissions,", "Students & Growth"],
  description:
    "Manage student inquiries, admissions pipelines, counselors, batches, demo classes, fee follow-ups, parent communication, and academic workflows.",
  heroImage: educationImages[0],
  heroAlt: "Students and education team planning admissions",
  accent: "#145cb7",
  accentDark: "#0f3474",
  accentSoft: "#eaf3ff",
  stats: [
    { label: "New Enquiries", value: "842", delta: "18.4% this week" },
    { label: "Demo Classes", value: "126", delta: "10.6% vs yesterday" },
    { label: "Admissions", value: "74", delta: "8.9% this month" },
    { label: "Fee Follow-ups", value: "212", delta: "12.1% pending" },
  ],
  nextCard: {
    label: "Next Demo Class",
    name: "Ananya Sharma",
    description: "Grade 11 Science",
    detail: "05:00 PM - Counselor Priya",
    status: "Scheduled",
  },
  trustBadges: [
    { label: "Admissions", sub: "Pipeline view", icon: GraduationCap },
    { label: "Counselors", sub: "Task routing", icon: UserCheck },
    { label: "Batches", sub: "Course mapping", icon: School },
    { label: "Fees", sub: "Reminder flow", icon: CreditCard },
  ],
  whyTitle: "Why Education Teams Choose HNX CRM Systems",
  whySubtitle: "Built for schools, coaching institutes, edtech teams, colleges, and training centers",
  whyCards: [
    { title: "Admission Clarity", text: "Track every enquiry from first call to final admission.", icon: GraduationCap },
    { title: "Counselor Control", text: "Assign leads, tasks, demos, and follow-ups to the right counselor.", icon: UserCheck },
    { title: "Batch Planning", text: "Map students to courses, batches, demo slots, and learning tracks.", icon: School },
    { title: "Parent Communication", text: "Send updates, reminders, and fee follow-ups across channels.", icon: MessageCircle },
    { title: "Growth Reports", text: "See source quality, counselor performance, and admission conversion.", icon: BarChart3 },
  ],
  specialtyTitle: "Built for Every Education Growth Model",
  specialtyCards: [
    { title: "Schools", text: "Admissions, parent records, fee follow-ups, and counselor tasks.", image: educationImages[1], icon: School },
    { title: "Coaching Institutes", text: "Demo classes, batches, courses, and enquiry conversion tracking.", image: educationImages[2], icon: GraduationCap },
    { title: "Edtech Teams", text: "Lead source tracking, trial classes, onboarding, and subscription follow-ups.", image: educationImages[3], icon: Workflow },
    { title: "Colleges", text: "Application status, documents, counselors, and department-wise reports.", image: educationImages[4], icon: FileCheck2 },
    { title: "Training Centers", text: "Course enquiries, placement follow-ups, batches, and certificate workflows.", image: educationImages[0], icon: BadgeCheck },
  ],
  dashboard: {
    title: "All-in-One Education Dashboard",
    dateLabel: "Admission Season",
    sidebar: ["Dashboard", "Enquiries", "Admissions", "Counselors", "Batches", "Demo Classes", "Fees", "Parents", "Reports", "Settings"],
    chartTitle: "Demo Class & Admission Trend",
    sourceTitle: "Top Enquiry Sources",
    sources: ["Website 32%", "Walk-in 21%", "Meta Ads 18%", "Referral 17%", "Forms 12%"],
    rowsTitle: "Recent Student Enquiries",
    rows: [
      ["Ananya Sharma", "Grade 11 Science", "Today, 05:00 PM", "Demo Set"],
      ["Kabir Joshi", "JEE Foundation", "Today, 06:30 PM", "Counseling"],
      ["Meera Nair", "MBA Prep", "Tomorrow, 10:30 AM", "Documents"],
      ["Ritvik Rao", "Coding Course", "Tomorrow, 01:00 PM", "Follow-up"],
    ],
    taskTitle: "Counselor Tasks",
    tasks: [
      ["Send demo class link to Ananya", "Due in 20 mins"],
      ["Follow up fee plan with Kabir parent", "Due today"],
      ["Collect Meera documents", "Due tomorrow"],
    ],
  },
  journeyTitle: "Admission Journey - Simplified & Automated",
  journeySubtitle: "From enquiry to enrolled student, every step is tracked",
  journey: [
    { title: "Enquiry Captured", text: "Capture leads from forms, ads, calls, WhatsApp, and walk-ins.", icon: Users },
    { title: "Counselor Assigned", text: "Assign counselor by course, location, source, or workload.", icon: UserCheck },
    { title: "Demo Scheduled", text: "Book demo classes and send reminders to students and parents.", icon: CalendarCheck },
    { title: "Admission Followed", text: "Track documents, fees, batch allocation, and parent communication.", icon: Workflow },
    { title: "Student Enrolled", text: "Move students into batch, academic, and retention workflows.", icon: GraduationCap },
  ],
  featureTitle: "Powerful Modules for",
  featureSubtitle: "Education Admissions",
  leftFeatures: ["Admission lead pipeline", "Counselor task dashboard", "Demo class scheduling", "Student and parent records", "Batch and course assignment"],
  rightFeatures: ["Fee reminder automation", "Document checklist", "Placement follow-ups", "Parent communication logs", "Role-based counselor views"],
  operationsTitle: "More Than Enquiries - Built for Admissions & Student Operations",
  operationsSubtitle:
    "HNX CRM Systems helps education teams manage lead conversion, counselor routines, demo classes, fee follow-ups, parent updates, and student records from one operating system.",
  operations: [
    { title: "Admission Pipeline", text: "Track enquiries from new lead to counseling, demo, documents, fees, and admission.", icon: GraduationCap },
    { title: "Counselor Tasks", text: "Give counselors a daily view of calls, follow-ups, demos, and parent updates.", icon: UserCheck },
    { title: "Batch Assignment", text: "Map students to courses, batches, trainers, timings, and learning stages.", icon: School },
    { title: "Fee Automation", text: "Send fee reminders, track pending amounts, and alert counselors before due dates.", icon: CreditCard },
    { title: "Parent Records", text: "Keep student, parent, communication, document, and preference history together.", icon: Users },
    { title: "Placement Follow-ups", text: "Manage training completion, interview tasks, certificates, and placement updates.", icon: BadgeCheck },
  ],
  pricingIntro:
    "Education CRM pricing is scoped around admission pipelines, counselor roles, student records, fee reminders, batch flows, reports, integrations, and AI requirements.",
  pricingPlans: plans(
    "education",
    ["Admission enquiries", "Counselor tasks", "Basic dashboard", "Student records"],
    ["Custom admission stages", "Batch fields", "Fee reminders", "Counselor permissions", "Advanced reports"],
    ["AI enquiry scoring", "Smart counselor suggestions", "Auto parent messages", "Daily admission planning", "Report explanations"],
    ["Multi-branch admissions", "LMS integrations", "Advanced permissions", "Custom academic workflows"]
  ),
  integrations: [
    { name: "WhatsApp", sub: "Parent updates", icon: MessageCircle },
    { name: "Email", sub: "Campaigns", icon: Mail },
    { name: "SMS", sub: "Reminders", icon: MessageCircle },
    { name: "Payments", sub: "Fees", icon: CreditCard },
    { name: "LMS", sub: "Learning", icon: School },
    { name: "Calendar", sub: "Demo slots", icon: CalendarCheck },
    { name: "Forms", sub: "Enquiries", icon: FileText },
    { name: "Telephony", sub: "Call logs", icon: Phone },
    { name: "Reports", sub: "Admissions", icon: BarChart3 },
  ],
};

const manufacturingImages = [
  "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1565043666747-69f6646db940?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1513828583688-c52646db42da?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1581093588401-fbb62a02f120?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1565793298595-6a879b1d9492?auto=format&fit=crop&w=900&q=85",
];

export const manufacturingConfig: IndustryCRMConfig = {
  badge: "Manufacturing CRM",
  headline: ["Manufacturing CRM", "Built for B2B Sales", "& Operations"],
  description:
    "Manage dealers, distributors, RFQs, quotations, orders, production follow-ups, dispatch status, service requests, and sales team activities.",
  heroImage: manufacturingImages[0],
  heroAlt: "Manufacturing operations and industrial sales team",
  accent: "#475569",
  accentDark: "#1f2937",
  accentSoft: "#eef2f7",
  stats: [
    { label: "New RFQs", value: "436", delta: "11.8% this week" },
    { label: "Quotations", value: "128", delta: "9.1% vs yesterday" },
    { label: "Active Orders", value: "72", delta: "6.4% this month" },
    { label: "Dispatches", value: "58", delta: "13.2% this week" },
  ],
  nextCard: {
    label: "Next Order Review",
    name: "Northline Components",
    description: "Bulk quotation approval",
    detail: "03:00 PM - Sales Manager Kavita",
    status: "Priority",
  },
  trustBadges: [
    { label: "RFQs", sub: "B2B pipeline", icon: ClipboardList },
    { label: "Quotes", sub: "Approval flow", icon: ReceiptText },
    { label: "Orders", sub: "Production link", icon: Factory },
    { label: "Dispatch", sub: "Logistics view", icon: Truck },
  ],
  whyTitle: "Why Manufacturing Teams Choose HNX CRM Systems",
  whySubtitle: "Built for factories, distributors, suppliers, and industrial sales teams",
  whyCards: [
    { title: "RFQ Control", text: "Capture requirements, quantities, specs, and urgency from every buyer.", icon: ClipboardList },
    { title: "Quotation Discipline", text: "Route quotes for approval and track version-wise negotiation.", icon: ReceiptText },
    { title: "Dealer Visibility", text: "Manage dealers, distributors, territories, targets, and credit notes.", icon: Handshake },
    { title: "Order Coordination", text: "Track order status from confirmation to production and dispatch.", icon: PackageCheck },
    { title: "Service Follow-ups", text: "Manage installation, complaints, warranty, and after-sales requests.", icon: Wrench },
  ],
  specialtyTitle: "Built for Every Manufacturing Sales Model",
  specialtyCards: [
    { title: "Factories", text: "RFQs, quotes, production follow-ups, dispatches, and dealer sales.", image: manufacturingImages[1], icon: Factory },
    { title: "Distributors", text: "Dealer pipelines, order tracking, payment follow-ups, and stock requests.", image: manufacturingImages[2], icon: Truck },
    { title: "Industrial Sales", text: "Sales visits, quotations, negotiations, and key account management.", image: manufacturingImages[3], icon: BriefcaseBusiness },
    { title: "Suppliers", text: "Buyer requirements, rate approvals, repeat orders, and dispatch updates.", image: manufacturingImages[4], icon: PackageCheck },
    { title: "After-Sales Teams", text: "Service requests, warranty cases, installation visits, and escalations.", image: manufacturingImages[0], icon: Wrench },
  ],
  dashboard: {
    title: "All-in-One Manufacturing Dashboard",
    dateLabel: "Current Production Cycle",
    sidebar: ["Dashboard", "RFQs", "Quotations", "Dealers", "Orders", "Production", "Dispatch", "Service", "Reports", "Settings"],
    chartTitle: "Quotation & Order Trend",
    sourceTitle: "Top RFQ Sources",
    sources: ["Dealer 34%", "Website 23%", "Sales Visit 19%", "Referral 14%", "Repeat Buyer 10%"],
    rowsTitle: "Recent RFQs & Orders",
    rows: [
      ["Northline Components", "Motor Parts RFQ", "Today, 03:00 PM", "Quote Review"],
      ["Apex Distributors", "Bulk Order", "Today, 04:30 PM", "Production"],
      ["Metro Fabricators", "Custom Specs", "Tomorrow, 11:00 AM", "Approved"],
      ["Shakti Traders", "Repeat Order", "Tomorrow, 02:00 PM", "Dispatch"],
    ],
    taskTitle: "Operations Tasks",
    tasks: [
      ["Approve revised quotation for Northline", "Due in 1 hour"],
      ["Share dispatch status with Shakti Traders", "Due today"],
      ["Schedule service visit for Apex Distributors", "Due tomorrow"],
    ],
  },
  journeyTitle: "Manufacturing Sales Journey - Simplified & Automated",
  journeySubtitle: "From RFQ to dispatch and service, every stage stays connected",
  journey: [
    { title: "RFQ Received", text: "Capture buyer specs, quantity, expected delivery, and attachments.", icon: ClipboardList },
    { title: "Quote Prepared", text: "Create quotation tasks and route for price or margin approval.", icon: ReceiptText },
    { title: "Order Confirmed", text: "Track PO, advance payment, production status, and commitments.", icon: PackageCheck },
    { title: "Dispatch Updated", text: "Coordinate dispatch, logistics, delivery proof, and customer updates.", icon: Truck },
    { title: "Service Managed", text: "Handle installation, warranty, complaints, and repeat order follow-ups.", icon: Wrench },
  ],
  featureTitle: "Powerful Modules for",
  featureSubtitle: "B2B Manufacturing",
  leftFeatures: ["RFQ management", "Quotation approval workflows", "Dealer and distributor records", "Order and production tracking", "Sales team visit logs"],
  rightFeatures: ["Dispatch coordination", "After-sales service tickets", "Payment and credit follow-ups", "ERP and inventory integrations", "Role-based operations dashboards"],
  operationsTitle: "More Than Quotations - Built for B2B Operations",
  operationsSubtitle:
    "HNX CRM Systems gives manufacturing teams one place for RFQs, quotes, production updates, dispatches, dealer activity, service requests, and sales reporting.",
  operations: [
    { title: "RFQ Management", text: "Capture technical details, quantities, attachments, and buyer requirements.", icon: ClipboardList },
    { title: "Quotation Approvals", text: "Control pricing, discounts, revisions, approvals, and quote history.", icon: ReceiptText },
    { title: "Dealer Management", text: "Track territories, distributor orders, targets, credits, and partner follow-ups.", icon: Handshake },
    { title: "Order Tracking", text: "Move orders through PO, advance, production, QC, dispatch, and delivery stages.", icon: PackageCheck },
    { title: "Dispatch Coordination", text: "Share shipment status, logistics details, delivery proof, and pending actions.", icon: Truck },
    { title: "Service Requests", text: "Manage complaints, installation, warranty cases, and after-sales visits.", icon: Wrench },
  ],
  pricingIntro:
    "Manufacturing CRM pricing depends on RFQ fields, quotation approvals, dealer workflows, order tracking, ERP or inventory integrations, dashboards, and AI requirements.",
  pricingPlans: plans(
    "manufacturing",
    ["RFQ records", "Quotation tasks", "Basic order dashboard", "Dealer records"],
    ["Quote approvals", "Order stages", "Dealer permissions", "Dispatch reports", "Workflow automation"],
    ["AI RFQ scoring", "Smart quote suggestions", "Auto follow-up drafts", "Sales visit planning", "Report explanations"],
    ["ERP integrations", "Production workflows", "Advanced permissions", "Multi-unit dashboards"]
  ),
  integrations: [
    { name: "ERP", sub: "Operations", icon: Factory },
    { name: "WhatsApp", sub: "Updates", icon: MessageCircle },
    { name: "Email", sub: "Quotes", icon: Mail },
    { name: "Telephony", sub: "Call logs", icon: Phone },
    { name: "Inventory", sub: "Stock", icon: PackageCheck },
    { name: "Accounting", sub: "Invoices", icon: ReceiptText },
    { name: "Payments", sub: "Gateway", icon: CreditCard },
    { name: "Logistics", sub: "Dispatch", icon: Truck },
    { name: "Reports", sub: "KPIs", icon: BarChart3 },
  ],
};

const retailImages = [
  "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1481437156560-3205f6a55735?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?auto=format&fit=crop&w=900&q=85",
];

export const retailConfig: IndustryCRMConfig = {
  badge: "Retail CRM",
  headline: ["Retail CRM", "Built to Increase", "Repeat Customers"],
  description:
    "Manage customers, loyalty, offers, purchase history, abandoned inquiries, support tickets, campaigns, and store performance across every channel.",
  heroImage: retailImages[0],
  heroAlt: "Retail store team managing customer relationships",
  accent: "#db2777",
  accentDark: "#9d174d",
  accentSoft: "#fce7f3",
  stats: [
    { label: "Customers", value: "18.4k", delta: "12.2% this month" },
    { label: "Repeat Buyers", value: "3,218", delta: "8.5% this week" },
    { label: "Campaigns", value: "42", delta: "6 live today" },
    { label: "Store Revenue", value: "24.8L", delta: "9.7% this month" },
  ],
  nextCard: {
    label: "Next Customer Campaign",
    name: "VIP Reactivation",
    description: "Inactive customers 90+ days",
    detail: "06:00 PM - WhatsApp offer",
    status: "Ready",
  },
  trustBadges: [
    { label: "Customers", sub: "Unified view", icon: Users },
    { label: "Loyalty", sub: "Points & rewards", icon: Tags },
    { label: "Campaigns", sub: "Offer engine", icon: ShoppingBag },
    { label: "Stores", sub: "Location reports", icon: Store },
  ],
  whyTitle: "Why Retail Teams Choose HNX CRM Systems",
  whySubtitle: "Built for retail stores, D2C brands, multi-location shops, and ecommerce sellers",
  whyCards: [
    { title: "Customer Memory", text: "Know purchase history, preferences, support cases, and lifetime value.", icon: Users },
    { title: "Repeat Sales", text: "Build reactivation, upsell, birthday, and seasonal campaigns.", icon: Tags },
    { title: "Loyalty Control", text: "Manage points, tiers, rewards, and offer eligibility.", icon: WalletCards },
    { title: "Store Visibility", text: "Compare store-wise customers, revenue, campaigns, and service quality.", icon: Store },
    { title: "Support Follow-ups", text: "Track complaints, returns, exchanges, and customer satisfaction.", icon: LifeBuoy },
  ],
  specialtyTitle: "Built for Every Retail Growth Model",
  specialtyCards: [
    { title: "Retail Stores", text: "Customer history, offers, support, loyalty, and purchase follow-ups.", image: retailImages[1], icon: Store },
    { title: "D2C Brands", text: "Segments, campaigns, abandoned inquiries, and repeat purchase flows.", image: retailImages[2], icon: ShoppingBag },
    { title: "Multi-Location Shops", text: "Store-wise reports, shared customer records, and staff dashboards.", image: retailImages[3], icon: MapPin },
    { title: "Ecommerce Sellers", text: "Order follow-ups, returns, support tickets, and reactivation campaigns.", image: retailImages[4], icon: PackageCheck },
    { title: "Loyalty Programs", text: "Points, tiers, rewards, offer rules, and repeat buyer tracking.", image: retailImages[0], icon: Tags },
  ],
  dashboard: {
    title: "All-in-One Retail Dashboard",
    dateLabel: "Current Month",
    sidebar: ["Dashboard", "Customers", "Orders", "Loyalty", "Campaigns", "Support", "Stores", "Offers", "Reports", "Settings"],
    chartTitle: "Repeat Buyer & Campaign Trend",
    sourceTitle: "Top Customer Sources",
    sources: ["POS 38%", "Online Store 24%", "WhatsApp 16%", "Marketplace 13%", "Referral 9%"],
    rowsTitle: "Recent Customers",
    rows: [
      ["Riya Shah", "Repeat buyer", "Today, 02:15 PM", "Offer Sent"],
      ["Kunal Mehta", "Return request", "Today, 03:30 PM", "Support"],
      ["Aisha Khan", "VIP segment", "Tomorrow, 11:00 AM", "Loyalty"],
      ["Dev Patel", "Abandoned inquiry", "Tomorrow, 01:00 PM", "Follow-up"],
    ],
    taskTitle: "Retail Tasks",
    tasks: [
      ["Send VIP offer to Aisha Khan", "Due in 30 mins"],
      ["Resolve return request for Kunal", "Due today"],
      ["Launch weekend reactivation campaign", "Due tomorrow"],
    ],
  },
  journeyTitle: "Customer Journey - Simplified & Automated",
  journeySubtitle: "From first purchase to loyal repeat customer, every touchpoint is tracked",
  journey: [
    { title: "Customer Captured", text: "Create records from POS, online store, WhatsApp, forms, and walk-ins.", icon: Users },
    { title: "Segment Built", text: "Group customers by value, product interest, location, and recency.", icon: Tags },
    { title: "Campaign Sent", text: "Send offers, loyalty updates, reminders, and reactivation messages.", icon: MessageCircle },
    { title: "Support Managed", text: "Track complaints, returns, feedback, and service follow-ups.", icon: LifeBuoy },
    { title: "Repeat Purchase", text: "Improve retention with automated campaigns and loyalty workflows.", icon: ShoppingBag },
  ],
  featureTitle: "Powerful Modules for",
  featureSubtitle: "Retail Growth",
  leftFeatures: ["Customer database", "Purchase history", "Loyalty program", "Offer campaigns", "Feedback and support"],
  rightFeatures: ["Multi-store customer view", "WhatsApp reactivation", "Customer segmentation", "POS and ecommerce sync", "Store performance reports"],
  operationsTitle: "More Than Campaigns - Built for Retail Operations",
  operationsSubtitle:
    "HNX CRM Systems helps retail teams connect customer records, loyalty, campaigns, support, purchases, and store performance so every visit can become a repeat sale.",
  operations: [
    { title: "Customer Database", text: "Keep purchase history, preferences, loyalty, and communication in one record.", icon: Users },
    { title: "Loyalty Program", text: "Track points, tiers, benefits, rewards, and redemption activity.", icon: Tags },
    { title: "Offer Campaigns", text: "Run segmented campaigns for festivals, birthdays, product drops, and inactive buyers.", icon: ShoppingBag },
    { title: "Support Tickets", text: "Manage returns, complaints, exchanges, feedback, and store escalations.", icon: LifeBuoy },
    { title: "Multi-Store View", text: "Understand customer behavior, revenue, and campaigns across locations.", icon: Store },
    { title: "Reactivation Flows", text: "Bring inactive customers back with WhatsApp, SMS, email, and offer automation.", icon: MessageCircle },
  ],
  pricingIntro:
    "Retail CRM pricing is scoped around loyalty, customer segmentation, campaigns, purchase history, omnichannel integrations, support workflows, and AI requirements.",
  pricingPlans: plans(
    "retail",
    ["Customer records", "Basic campaign tasks", "Purchase history", "Simple dashboard"],
    ["Loyalty fields", "Customer segments", "Offer automation", "Support workflows", "Store reports"],
    ["AI customer scoring", "Smart campaign ideas", "Auto message drafts", "Repeat purchase suggestions", "Report explanations"],
    ["POS integrations", "Ecommerce sync", "Multi-store permissions", "Advanced loyalty workflows"]
  ),
  integrations: [
    { name: "POS", sub: "Store billing", icon: Store },
    { name: "Shopify", sub: "Orders", icon: ShoppingBag },
    { name: "WooCommerce", sub: "Online store", icon: PackageCheck },
    { name: "WhatsApp", sub: "Campaigns", icon: MessageCircle },
    { name: "Email", sub: "Offers", icon: Mail },
    { name: "SMS", sub: "Alerts", icon: MessageCircle },
    { name: "Payments", sub: "Gateway", icon: CreditCard },
    { name: "Loyalty", sub: "Rewards", icon: Tags },
    { name: "Analytics", sub: "Reports", icon: BarChart3 },
  ],
};

const financeImages = [
  "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1554224154-26032ffc0d07?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1559526324-593bc073d938?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=900&q=85",
];

export const financeConfig: IndustryCRMConfig = {
  badge: "Finance CRM",
  headline: ["Finance CRM", "Built for Leads,", "Documents & Approvals"],
  description:
    "Manage loan leads, KYC documents, eligibility stages, advisor tasks, client follow-ups, approval pipelines, and compliance-ready records.",
  heroImage: financeImages[0],
  heroAlt: "Finance advisor reviewing documents and approvals",
  accent: "#0f766e",
  accentDark: "#064e3b",
  accentSoft: "#dff7ef",
  stats: [
    { label: "Loan Leads", value: "624", delta: "15.2% this week" },
    { label: "Docs Pending", value: "148", delta: "9.4% pending" },
    { label: "Approved Cases", value: "87", delta: "6.8% this month" },
    { label: "Follow-ups", value: "236", delta: "12.6% due today" },
  ],
  nextCard: {
    label: "Next Approval Follow-up",
    name: "Sanjay Verma",
    description: "Home loan eligibility",
    detail: "04:15 PM - Advisor Nikhil",
    status: "In Review",
  },
  trustBadges: [
    { label: "Loan Leads", sub: "Stage tracking", icon: Landmark },
    { label: "KYC", sub: "Document list", icon: FileCheck2 },
    { label: "Approvals", sub: "Pipeline view", icon: BadgeCheck },
    { label: "Advisors", sub: "Daily tasks", icon: UserCheck },
  ],
  whyTitle: "Why Finance Teams Choose HNX CRM Systems",
  whySubtitle: "Built for loan agencies, financial consultants, NBFC workflows, advisors, and finance service firms",
  whyCards: [
    { title: "Document Discipline", text: "Track KYC, bank statements, income proof, and pending documents.", icon: FileCheck2 },
    { title: "Approval Visibility", text: "Move cases through eligibility, submission, verification, and sanction.", icon: BadgeCheck },
    { title: "Advisor Productivity", text: "Give advisors a clear task list for follow-ups, calls, and submissions.", icon: UserCheck },
    { title: "Compliance Records", text: "Maintain communication history, documents, owners, and case status.", icon: ShieldCheck },
    { title: "Client Follow-ups", text: "Automate reminders for missing documents, renewals, and payment stages.", icon: MessageCircle },
  ],
  specialtyTitle: "Built for Every Finance Sales Workflow",
  specialtyCards: [
    { title: "Loan Agencies", text: "Loan leads, eligibility stages, document checklists, and approval follow-ups.", image: financeImages[1], icon: Landmark },
    { title: "Financial Consultants", text: "Client records, advisory tasks, products, and communication logs.", image: financeImages[2], icon: BriefcaseBusiness },
    { title: "NBFC Workflows", text: "Application movement, verification stages, branches, and approval reports.", image: financeImages[3], icon: BadgeCheck },
    { title: "Investment Advisors", text: "Client goals, follow-ups, renewal reminders, and document records.", image: financeImages[4], icon: BarChart3 },
    { title: "Accounting Firms", text: "Client service requests, documents, compliance tasks, and invoices.", image: financeImages[0], icon: ReceiptText },
  ],
  dashboard: {
    title: "All-in-One Finance Dashboard",
    dateLabel: "Current Approval Cycle",
    sidebar: ["Dashboard", "Leads", "Applications", "Documents", "KYC", "Advisors", "Approvals", "Renewals", "Reports", "Settings"],
    chartTitle: "Application & Approval Trend",
    sourceTitle: "Top Lead Sources",
    sources: ["Referral 31%", "Website 24%", "Telephony 17%", "Ads 16%", "Partner 12%"],
    rowsTitle: "Recent Finance Cases",
    rows: [
      ["Sanjay Verma", "Home loan", "Today, 04:15 PM", "In Review"],
      ["Priya Nair", "Business loan", "Today, 05:00 PM", "Docs Pending"],
      ["Mohit Sethi", "Personal loan", "Tomorrow, 11:00 AM", "Submitted"],
      ["Anita Rao", "Investment plan", "Tomorrow, 03:30 PM", "Follow-up"],
    ],
    taskTitle: "Advisor Tasks",
    tasks: [
      ["Collect bank statement from Priya", "Due in 45 mins"],
      ["Call Sanjay about eligibility result", "Due today"],
      ["Share investment summary with Anita", "Due tomorrow"],
    ],
  },
  journeyTitle: "Finance Case Journey - Simplified & Automated",
  journeySubtitle: "From lead to approval, every document and follow-up is visible",
  journey: [
    { title: "Lead Captured", text: "Capture loan, investment, or service enquiries from every channel.", icon: Users },
    { title: "Eligibility Checked", text: "Record income, product fit, risk notes, and advisor recommendations.", icon: ClipboardCheck },
    { title: "Documents Collected", text: "Track KYC, financial documents, signatures, and missing items.", icon: FileCheck2 },
    { title: "Approval Followed", text: "Move cases through verification, submission, sanction, and disbursal.", icon: Workflow },
    { title: "Client Retained", text: "Schedule renewals, advisory reviews, and future cross-sell tasks.", icon: BadgeCheck },
  ],
  featureTitle: "Powerful Modules for",
  featureSubtitle: "Finance Workflows",
  leftFeatures: ["Loan application pipeline", "Document checklist", "KYC status tracking", "Advisor task management", "Client communication logs"],
  rightFeatures: ["Approval stages", "Renewal reminders", "Compliance-ready records", "Payment follow-ups", "Role-based advisor dashboards"],
  operationsTitle: "More Than Applications - Built for Finance Operations",
  operationsSubtitle:
    "HNX CRM Systems helps finance teams control leads, documents, KYC status, approval stages, advisor tasks, client communication, and compliance-friendly case records.",
  operations: [
    { title: "Loan Pipeline", text: "Track products, eligibility, stages, owners, and follow-up deadlines.", icon: Landmark },
    { title: "Document Checklist", text: "Manage KYC, income proof, bank statements, forms, and missing documents.", icon: FileCheck2 },
    { title: "Advisor Dashboard", text: "Plan advisor calls, document follow-ups, client meetings, and submissions.", icon: UserCheck },
    { title: "Approval Stages", text: "Move applications through verification, bank submission, approval, and disbursal.", icon: BadgeCheck },
    { title: "Communication Logs", text: "Maintain call, email, WhatsApp, and internal note history for each case.", icon: MessageCircle },
    { title: "Renewal Reminders", text: "Create reminders for policy, loan, investment, and compliance renewals.", icon: CalendarCheck },
  ],
  pricingIntro:
    "Finance CRM pricing is scoped around compliance workflows, document tracking, approval stages, advisor dashboards, integrations, reports, and AI requirements.",
  pricingPlans: plans(
    "finance",
    ["Loan lead records", "Basic document checklist", "Advisor tasks", "Simple dashboard"],
    ["Custom approval stages", "KYC tracking", "Advisor permissions", "Renewal reminders", "Advanced reports"],
    ["AI eligibility scoring", "Smart document suggestions", "Auto message drafts", "Advisor day planning", "Report explanations"],
    ["Banking API workflows", "Advanced compliance roles", "Document storage integrations", "Multi-branch dashboards"]
  ),
  integrations: [
    { name: "WhatsApp", sub: "Docs follow-up", icon: MessageCircle },
    { name: "Email", sub: "Statements", icon: Mail },
    { name: "SMS", sub: "Reminders", icon: MessageCircle },
    { name: "Telephony", sub: "Call logs", icon: Phone },
    { name: "Payments", sub: "Gateway", icon: CreditCard },
    { name: "Documents", sub: "Storage", icon: FileText },
    { name: "Accounting", sub: "Books", icon: ReceiptText },
    { name: "Banking", sub: "APIs", icon: Landmark },
    { name: "Reports", sub: "Compliance", icon: BarChart3 },
  ],
};

const insuranceImages = [
  "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1554224154-22dec7ec8818?auto=format&fit=crop&w=900&q=85",
];

export const insuranceConfig: IndustryCRMConfig = {
  badge: "Insurance CRM",
  headline: ["Insurance CRM", "Built for Policies,", "Renewals & Claims"],
  description:
    "Manage leads, policies, renewals, premium reminders, claims support, agent performance, and customer communication from one CRM.",
  heroImage: insuranceImages[0],
  heroAlt: "Insurance advisor managing policy documents and client renewals",
  accent: "#2563eb",
  accentDark: "#1e3a8a",
  accentSoft: "#eaf1ff",
  stats: [
    { label: "New Leads", value: "512", delta: "13.5% this week" },
    { label: "Active Policies", value: "4,820", delta: "7.8% this month" },
    { label: "Renewals Due", value: "186", delta: "24 due today" },
    { label: "Claims", value: "43", delta: "9.2% resolved" },
  ],
  nextCard: {
    label: "Next Renewal",
    name: "Rakesh Gupta",
    description: "Health policy renewal",
    detail: "12:45 PM - Agent Meera",
    status: "Due",
  },
  trustBadges: [
    { label: "Policies", sub: "Customer history", icon: ShieldCheck },
    { label: "Renewals", sub: "Auto reminders", icon: CalendarCheck },
    { label: "Claims", sub: "Document tracking", icon: FileCheck2 },
    { label: "Agents", sub: "Performance view", icon: UserCheck },
  ],
  whyTitle: "Why Insurance Teams Choose HNX CRM Systems",
  whySubtitle: "Built for insurance brokers, agencies, policy sellers, and claim support teams",
  whyCards: [
    { title: "Renewal Control", text: "Never miss policy renewal dates, premium reminders, or follow-ups.", icon: CalendarCheck },
    { title: "Policy History", text: "Keep customer policies, family members, premiums, and documents together.", icon: ShieldCheck },
    { title: "Claim Visibility", text: "Track claim documents, stages, status, and support owner.", icon: FileCheck2 },
    { title: "Agent Performance", text: "Monitor leads, renewals, premium follow-ups, and conversions by agent.", icon: UserCheck },
    { title: "Cross-Sell Campaigns", text: "Identify health, motor, life, and business policy opportunities.", icon: Tags },
  ],
  specialtyTitle: "Built for Every Insurance Workflow",
  specialtyCards: [
    { title: "Insurance Brokers", text: "Policy leads, comparisons, premium follow-ups, and customer records.", image: insuranceImages[1], icon: ShieldCheck },
    { title: "Policy Agencies", text: "Agent tasks, renewals, claim support, and sales reports.", image: insuranceImages[2], icon: UserCheck },
    { title: "Claims Teams", text: "Claim documents, status, escalations, and customer communication.", image: insuranceImages[3], icon: FileCheck2 },
    { title: "Motor Insurance", text: "Vehicle policies, renewal reminders, finance handoffs, and documents.", image: insuranceImages[4], icon: Car },
    { title: "Health & Life", text: "Family records, premiums, renewals, riders, and cross-sell campaigns.", image: insuranceImages[0], icon: HeartPulse },
  ],
  dashboard: {
    title: "All-in-One Insurance Dashboard",
    dateLabel: "Renewal Window",
    sidebar: ["Dashboard", "Leads", "Policies", "Customers", "Renewals", "Claims", "Agents", "Premiums", "Reports", "Settings"],
    chartTitle: "Renewal & Claim Trend",
    sourceTitle: "Top Policy Sources",
    sources: ["Referral 33%", "Renewal 24%", "Agent 18%", "Website 14%", "Campaign 11%"],
    rowsTitle: "Recent Policy Activity",
    rows: [
      ["Rakesh Gupta", "Health renewal", "Today, 12:45 PM", "Due"],
      ["Nisha Jain", "Motor policy", "Today, 04:00 PM", "Quote Sent"],
      ["Manav Suri", "Claim support", "Tomorrow, 10:00 AM", "Docs Pending"],
      ["Pooja Rao", "Life policy", "Tomorrow, 02:30 PM", "Follow-up"],
    ],
    taskTitle: "Agent Tasks",
    tasks: [
      ["Send premium reminder to Rakesh", "Due in 30 mins"],
      ["Collect claim documents from Manav", "Due today"],
      ["Share motor quote with Nisha", "Due tomorrow"],
    ],
  },
  journeyTitle: "Policy Journey - Simplified & Automated",
  journeySubtitle: "From lead to renewal and claims, every policy step stays active",
  journey: [
    { title: "Lead Captured", text: "Capture insurance enquiries from agents, campaigns, referrals, and calls.", icon: Users },
    { title: "Policy Suggested", text: "Record needs, policy type, premium range, and customer profile.", icon: ShieldCheck },
    { title: "Documents Collected", text: "Track KYC, policy forms, vehicle details, and claim files.", icon: FileCheck2 },
    { title: "Renewal Automated", text: "Create reminders for premiums, renewals, and agent follow-ups.", icon: CalendarCheck },
    { title: "Customer Retained", text: "Support claims, cross-sell policies, and maintain long-term history.", icon: BadgeCheck },
  ],
  featureTitle: "Powerful Modules for",
  featureSubtitle: "Insurance Teams",
  leftFeatures: ["Policy lead pipeline", "Renewal reminders", "Claim document tracking", "Agent task management", "Premium follow-ups"],
  rightFeatures: ["Customer policy history", "Cross-sell campaigns", "Document upload workflow", "Agent performance reports", "Role-based dashboards"],
  operationsTitle: "More Than Policy Records - Built for Renewals & Claims",
  operationsSubtitle:
    "HNX CRM Systems helps insurance teams manage policies, renewals, premiums, claims, agent activity, customer communication, and cross-sell opportunities.",
  operations: [
    { title: "Policy Pipeline", text: "Track lead, quote, proposal, documents, premium, and policy issue stages.", icon: ShieldCheck },
    { title: "Renewal Automation", text: "Send reminders before renewal windows and keep agents accountable.", icon: CalendarCheck },
    { title: "Claim Tracking", text: "Manage claim documents, stages, escalations, and customer updates.", icon: FileCheck2 },
    { title: "Agent Tasks", text: "Assign calls, premium follow-ups, renewal tasks, and cross-sell actions.", icon: UserCheck },
    { title: "Premium Follow-ups", text: "Track payment status, due dates, receipts, and customer reminders.", icon: CreditCard },
    { title: "Cross-Sell Campaigns", text: "Identify customers for health, life, motor, business, or family policies.", icon: Tags },
  ],
  pricingIntro:
    "Insurance CRM pricing is scoped around policy modules, renewal automation, claims tracking, agent dashboards, integrations, reports, and AI requirements.",
  pricingPlans: plans(
    "insurance",
    ["Policy lead records", "Renewal tasks", "Customer history", "Basic dashboard"],
    ["Policy module", "Renewal automation", "Claim tracking", "Agent permissions", "Advanced reports"],
    ["AI policy suggestions", "Smart renewal prompts", "Auto message drafts", "Agent day planning", "Report explanations"],
    ["Insurance API workflows", "Advanced claim rules", "Multi-agent permissions", "Custom policy dashboards"]
  ),
  integrations: [
    { name: "WhatsApp", sub: "Renewals", icon: MessageCircle },
    { name: "Email", sub: "Policies", icon: Mail },
    { name: "SMS", sub: "Premium alerts", icon: MessageCircle },
    { name: "Telephony", sub: "Call logs", icon: Phone },
    { name: "Payments", sub: "Premiums", icon: CreditCard },
    { name: "Documents", sub: "Uploads", icon: FileText },
    { name: "Insurance APIs", sub: "Policy data", icon: ShieldCheck },
    { name: "Calendar", sub: "Renewals", icon: CalendarCheck },
    { name: "Reports", sub: "Agents", icon: BarChart3 },
  ],
};

const travelImages = [
  "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1488085061387-422e29b40080?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1499678329028-101435549a4e?auto=format&fit=crop&w=900&q=85",
];

export const travelConfig: IndustryCRMConfig = {
  badge: "Travel CRM",
  headline: ["Travel CRM", "Built for Packages,", "Bookings & Follow-ups"],
  description:
    "Manage travel inquiries, itineraries, package quotes, visa documents, booking stages, payment follow-ups, and customer communication.",
  heroImage: travelImages[0],
  heroAlt: "Travel planning and package booking workspace",
  accent: "#0891b2",
  accentDark: "#155e75",
  accentSoft: "#e0f7fb",
  stats: [
    { label: "New Enquiries", value: "734", delta: "16.7% this week" },
    { label: "Quotes Sent", value: "214", delta: "12.4% vs yesterday" },
    { label: "Active Trips", value: "96", delta: "8.1% this month" },
    { label: "Payments Due", value: "58", delta: "18 due today" },
  ],
  nextCard: {
    label: "Next Package Follow-up",
    name: "Maldives Couple Trip",
    description: "Itinerary approval pending",
    detail: "07:00 PM - Travel Advisor Tara",
    status: "Hot",
  },
  trustBadges: [
    { label: "Packages", sub: "Quote builder", icon: Plane },
    { label: "Itinerary", sub: "Day-wise plan", icon: Route },
    { label: "Visa Docs", sub: "Checklist", icon: FileCheck2 },
    { label: "Payments", sub: "Due tracking", icon: CreditCard },
  ],
  whyTitle: "Why Travel Teams Choose HNX CRM Systems",
  whySubtitle: "Built for travel agencies, tour operators, visa consultants, and package sellers",
  whyCards: [
    { title: "Quote Speed", text: "Build package quotes, compare options, and track customer response.", icon: Plane },
    { title: "Itinerary Control", text: "Maintain day-wise plans, hotel details, transfers, and inclusions.", icon: Route },
    { title: "Visa Discipline", text: "Track document checklists, appointment dates, and application status.", icon: FileCheck2 },
    { title: "Payment Visibility", text: "Follow advance, balance, due dates, and vendor payment tasks.", icon: CreditCard },
    { title: "Post-Trip Retention", text: "Collect feedback, reviews, referrals, and repeat trip opportunities.", icon: BadgeCheck },
  ],
  specialtyTitle: "Built for Every Travel Sales Model",
  specialtyCards: [
    { title: "Travel Agencies", text: "Inquiries, package quotes, bookings, payments, and customer follow-ups.", image: travelImages[1], icon: Plane },
    { title: "Tour Operators", text: "Group trips, itinerary planning, vendors, seats, and trip status.", image: travelImages[2], icon: Route },
    { title: "Visa Consultants", text: "Visa checklists, appointment dates, documents, and status updates.", image: travelImages[3], icon: FileCheck2 },
    { title: "Hotel Sellers", text: "Hotel enquiries, room options, quotations, and payment follow-ups.", image: travelImages[4], icon: Building2 },
    { title: "Package Teams", text: "Custom packages, inclusions, approvals, and customer reminders.", image: travelImages[0], icon: ClipboardCheck },
  ],
  dashboard: {
    title: "All-in-One Travel Dashboard",
    dateLabel: "Current Travel Window",
    sidebar: ["Dashboard", "Enquiries", "Packages", "Quotes", "Itineraries", "Visa", "Bookings", "Payments", "Reports", "Settings"],
    chartTitle: "Quote & Booking Trend",
    sourceTitle: "Top Enquiry Sources",
    sources: ["Website 30%", "WhatsApp 22%", "Referral 18%", "Ads 17%", "Walk-in 13%"],
    rowsTitle: "Recent Travel Enquiries",
    rows: [
      ["Maldives Couple Trip", "Honeymoon package", "Today, 07:00 PM", "Quote Sent"],
      ["Rohit Group", "Dubai group tour", "Today, 08:30 PM", "Payment Due"],
      ["Anika Jain", "Schengen visa", "Tomorrow, 11:30 AM", "Docs Pending"],
      ["Corporate Team", "Goa offsite", "Tomorrow, 04:00 PM", "Itinerary"],
    ],
    taskTitle: "Travel Tasks",
    tasks: [
      ["Send revised Maldives itinerary", "Due in 20 mins"],
      ["Collect Schengen documents from Anika", "Due today"],
      ["Confirm hotel hold for Dubai group", "Due tomorrow"],
    ],
  },
  journeyTitle: "Travel Booking Journey - Simplified & Automated",
  journeySubtitle: "From inquiry to post-trip feedback, every trip stage is managed",
  journey: [
    { title: "Inquiry Captured", text: "Capture travel leads from website, WhatsApp, calls, ads, and referrals.", icon: Users },
    { title: "Package Quoted", text: "Create options for dates, hotels, flights, inclusions, and pricing.", icon: Plane },
    { title: "Documents Collected", text: "Track visa, passport, ID, consent, and booking documents.", icon: FileCheck2 },
    { title: "Booking Followed", text: "Manage booking stages, payments, vendors, and customer reminders.", icon: Workflow },
    { title: "Feedback Collected", text: "Send post-trip feedback, review requests, and repeat travel campaigns.", icon: BadgeCheck },
  ],
  featureTitle: "Powerful Modules for",
  featureSubtitle: "Travel Teams",
  leftFeatures: ["Travel lead pipeline", "Package quotation builder", "Itinerary management", "Visa document checklist", "Booking and payment stages"],
  rightFeatures: ["Customer reminders", "Post-trip feedback", "Vendor follow-ups", "Calendar and maps", "Role-based advisor dashboards"],
  operationsTitle: "More Than Bookings - Built for Travel Operations",
  operationsSubtitle:
    "HNX CRM Systems helps travel teams manage package quotes, itineraries, visa documents, payment stages, vendors, reminders, and feedback from one dashboard.",
  operations: [
    { title: "Lead Pipeline", text: "Track destination, dates, passengers, budget, urgency, and sales owner.", icon: Users },
    { title: "Package Quotes", text: "Build options for hotels, flights, transfers, inclusions, and pricing.", icon: Plane },
    { title: "Itinerary Management", text: "Maintain day-wise plans, activities, vendors, and customer approvals.", icon: Route },
    { title: "Visa Checklist", text: "Track passport, photos, forms, appointments, and embassy status.", icon: FileCheck2 },
    { title: "Payment Stages", text: "Follow advance, balance, vendor payments, receipts, and due dates.", icon: CreditCard },
    { title: "Post-Trip Feedback", text: "Collect reviews, referrals, repeat trips, and customer satisfaction notes.", icon: BadgeCheck },
  ],
  pricingIntro:
    "Travel CRM pricing is scoped around package quotation, itinerary modules, visa documents, payment stages, booking integrations, reports, and AI requirements.",
  pricingPlans: plans(
    "travel",
    ["Travel enquiries", "Basic quote tasks", "Customer records", "Simple dashboard"],
    ["Package quotation builder", "Itinerary fields", "Visa checklist", "Payment reminders", "Advanced reports"],
    ["AI trip suggestions", "Smart quote follow-ups", "Auto message drafts", "Advisor day planning", "Report explanations"],
    ["Booking API workflows", "Vendor modules", "Advanced permissions", "Custom package dashboards"]
  ),
  integrations: [
    { name: "WhatsApp", sub: "Trip updates", icon: MessageCircle },
    { name: "Email", sub: "Itineraries", icon: Mail },
    { name: "SMS", sub: "Reminders", icon: MessageCircle },
    { name: "Payments", sub: "Gateway", icon: CreditCard },
    { name: "Calendar", sub: "Travel dates", icon: CalendarCheck },
    { name: "Maps", sub: "Locations", icon: MapPin },
    { name: "Documents", sub: "Visa files", icon: FileText },
    { name: "Booking APIs", sub: "Flights/hotels", icon: Plane },
    { name: "Reports", sub: "Sales", icon: BarChart3 },
  ],
};

const automobileImages = [
  "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=900&q=85",
];

export const automobileConfig: IndustryCRMConfig = {
  badge: "Automobile CRM",
  headline: ["Automobile CRM", "Built for Sales,", "Service & Follow-ups"],
  description:
    "Manage vehicle inquiries, test drives, bookings, service reminders, customer records, finance follow-ups, and showroom performance.",
  heroImage: automobileImages[0],
  heroAlt: "Automobile showroom and sales CRM workflow",
  accent: "#ea580c",
  accentDark: "#9a3412",
  accentSoft: "#fff0e6",
  stats: [
    { label: "New Leads", value: "684", delta: "14.8% this week" },
    { label: "Test Drives", value: "152", delta: "11.2% vs yesterday" },
    { label: "Bookings", value: "46", delta: "7.5% this month" },
    { label: "Service Due", value: "219", delta: "32 due today" },
  ],
  nextCard: {
    label: "Next Test Drive",
    name: "Vikram Singh",
    description: "SUV automatic variant",
    detail: "01:30 PM - Executive Arjun",
    status: "Confirmed",
  },
  trustBadges: [
    { label: "Test Drives", sub: "Slot booking", icon: Car },
    { label: "Bookings", sub: "Delivery stage", icon: BadgeCheck },
    { label: "Service", sub: "Due reminders", icon: Wrench },
    { label: "Finance", sub: "Loan follow-up", icon: CreditCard },
  ],
  whyTitle: "Why Automobile Teams Choose HNX CRM Systems",
  whySubtitle: "Built for car dealers, bike dealers, service centers, spare parts sellers, and showrooms",
  whyCards: [
    { title: "Lead Discipline", text: "Track vehicle interest, source, variant, budget, and purchase timeline.", icon: Users },
    { title: "Test Drive Control", text: "Schedule slots, assign executives, and send reminders automatically.", icon: Car },
    { title: "Booking Visibility", text: "Track booking, finance, insurance, accessories, delivery, and documents.", icon: BadgeCheck },
    { title: "Service Retention", text: "Automate service reminders, feedback, and repeat workshop visits.", icon: Wrench },
    { title: "Showroom Reports", text: "Measure executive performance, lead sources, bookings, and deliveries.", icon: BarChart3 },
  ],
  specialtyTitle: "Built for Every Automobile Sales & Service Model",
  specialtyCards: [
    { title: "Car Dealers", text: "Vehicle inquiries, test drives, bookings, finance, and delivery stages.", image: automobileImages[1], icon: Car },
    { title: "Bike Dealers", text: "Walk-ins, lead source tracking, variant interest, and finance follow-ups.", image: automobileImages[2], icon: Route },
    { title: "Service Centers", text: "Service reminders, job cards, feedback, complaints, and customer history.", image: automobileImages[3], icon: Wrench },
    { title: "Spare Parts Sellers", text: "Customer enquiries, parts requests, inventory follow-ups, and orders.", image: automobileImages[4], icon: PackageCheck },
    { title: "Auto Showrooms", text: "Executive tasks, test drive calendar, showroom reports, and campaigns.", image: automobileImages[0], icon: Store },
  ],
  dashboard: {
    title: "All-in-One Automobile Dashboard",
    dateLabel: "Current Sales Month",
    sidebar: ["Dashboard", "Leads", "Vehicles", "Test Drives", "Bookings", "Finance", "Service", "Delivery", "Reports", "Settings"],
    chartTitle: "Test Drive & Booking Trend",
    sourceTitle: "Top Lead Sources",
    sources: ["Walk-in 29%", "Website 23%", "Meta Ads 19%", "Referral 15%", "Telephony 14%"],
    rowsTitle: "Recent Vehicle Leads",
    rows: [
      ["Vikram Singh", "SUV automatic", "Today, 01:30 PM", "Test Drive"],
      ["Kriti Sharma", "Hatchback enquiry", "Today, 04:00 PM", "Quote Sent"],
      ["Rahul Mehra", "Service due", "Tomorrow, 10:00 AM", "Reminder"],
      ["Anil Kapoor", "Sedan booking", "Tomorrow, 02:30 PM", "Finance"],
    ],
    taskTitle: "Showroom Tasks",
    tasks: [
      ["Confirm SUV test drive slot for Vikram", "Due in 25 mins"],
      ["Send finance checklist to Anil", "Due today"],
      ["Call Rahul for service appointment", "Due tomorrow"],
    ],
  },
  journeyTitle: "Vehicle Customer Journey - Simplified & Automated",
  journeySubtitle: "From enquiry to delivery and service, every customer action is visible",
  journey: [
    { title: "Lead Captured", text: "Capture vehicle enquiries from walk-ins, ads, website, calls, and referrals.", icon: Users },
    { title: "Test Drive Set", text: "Schedule test drives, assign executives, and send customer reminders.", icon: Car },
    { title: "Booking Tracked", text: "Manage booking amount, documents, finance, insurance, and accessories.", icon: BadgeCheck },
    { title: "Delivery Completed", text: "Track delivery dates, PDI, handover tasks, and customer updates.", icon: Truck },
    { title: "Service Retained", text: "Automate service reminders, feedback, and repeat visit campaigns.", icon: Wrench },
  ],
  featureTitle: "Powerful Modules for",
  featureSubtitle: "Automobile Showrooms",
  leftFeatures: ["Vehicle inquiry pipeline", "Test drive scheduling", "Booking and delivery tracking", "Service reminder automation", "Customer vehicle history"],
  rightFeatures: ["Finance and insurance follow-up", "Sales executive tasks", "Accessory tracking", "Showroom performance reports", "Role-based sales dashboards"],
  operationsTitle: "More Than Leads - Built for Sales & Service",
  operationsSubtitle:
    "HNX CRM Systems helps automobile teams manage leads, test drives, bookings, delivery, service reminders, finance follow-ups, and showroom performance from one place.",
  operations: [
    { title: "Vehicle Pipeline", text: "Track model, variant, budget, exchange interest, lead source, and stage.", icon: Car },
    { title: "Test Drive Scheduling", text: "Book slots, assign executives, manage vehicle availability, and reminders.", icon: CalendarCheck },
    { title: "Booking Tracking", text: "Follow booking, payment, finance, insurance, accessories, and delivery tasks.", icon: BadgeCheck },
    { title: "Service Reminders", text: "Automate periodic service alerts, workshop appointments, and feedback.", icon: Wrench },
    { title: "Vehicle History", text: "Keep customer, vehicle, service, insurance, and finance history together.", icon: FileText },
    { title: "Executive Tasks", text: "Give each sales executive a daily view of calls, visits, and follow-ups.", icon: UserCheck },
  ],
  pricingIntro:
    "Automobile CRM pricing is scoped around showroom workflows, service reminders, test drive scheduling, booking stages, integrations, dashboards, and AI requirements.",
  pricingPlans: plans(
    "automobile",
    ["Vehicle leads", "Test drive tasks", "Customer records", "Basic dashboard"],
    ["Test drive workflows", "Booking stages", "Service reminders", "Sales permissions", "Advanced reports"],
    ["AI lead scoring", "Smart vehicle suggestions", "Auto message drafts", "Executive day planning", "Report explanations"],
    ["Dealer tool integrations", "Custom service workflows", "Advanced roles", "Multi-showroom dashboards"]
  ),
  integrations: [
    { name: "WhatsApp", sub: "Customer updates", icon: MessageCircle },
    { name: "Email", sub: "Quotes", icon: Mail },
    { name: "SMS", sub: "Service alerts", icon: MessageCircle },
    { name: "Telephony", sub: "Call logs", icon: Phone },
    { name: "Payments", sub: "Booking", icon: CreditCard },
    { name: "Dealer Tools", sub: "DMS", icon: Car },
    { name: "Calendar", sub: "Test drives", icon: CalendarCheck },
    { name: "Finance", sub: "Loans", icon: Landmark },
    { name: "Reports", sub: "Showroom", icon: BarChart3 },
  ],
};

const serviceImages = [
  "https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=900&q=85",
  "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=900&q=85",
];

export const serviceBusinessConfig: IndustryCRMConfig = {
  badge: "Service Business CRM",
  headline: ["Service Business CRM", "Built to Manage Leads,", "Tasks & Clients"],
  description:
    "Manage service inquiries, quotes, tickets, tasks, staff schedules, client follow-ups, invoices, payment reminders, and project status.",
  heroImage: serviceImages[0],
  heroAlt: "Service business team managing clients and tasks",
  accent: "#7c3aed",
  accentDark: "#4c1d95",
  accentSoft: "#f2eafe",
  stats: [
    { label: "New Leads", value: "458", delta: "12.8% this week" },
    { label: "Open Tickets", value: "126", delta: "18 urgent" },
    { label: "Active Jobs", value: "84", delta: "9.5% this month" },
    { label: "Completed Tasks", value: "312", delta: "16.1% this week" },
  ],
  nextCard: {
    label: "Next Client Task",
    name: "Acme Office Setup",
    description: "Quote approval pending",
    detail: "02:45 PM - Manager Aditi",
    status: "Due",
  },
  trustBadges: [
    { label: "Leads", sub: "Inquiry pipeline", icon: Users },
    { label: "Tickets", sub: "Service queue", icon: LifeBuoy },
    { label: "Tasks", sub: "Staff schedule", icon: ClipboardCheck },
    { label: "Invoices", sub: "Payment follow-up", icon: ReceiptText },
  ],
  whyTitle: "Why Service Businesses Choose HNX CRM Systems",
  whySubtitle: "Built for agencies, IT companies, consultants, repair teams, maintenance teams, and local service providers",
  whyCards: [
    { title: "Lead Clarity", text: "Capture service enquiries, requirements, budgets, and expected timelines.", icon: Users },
    { title: "Quote Tracking", text: "Track estimates, revisions, approvals, and client decisions.", icon: ReceiptText },
    { title: "Task Ownership", text: "Assign work to staff, monitor deadlines, and reduce missed updates.", icon: ClipboardCheck },
    { title: "Ticket Control", text: "Manage service requests, escalations, status, and customer communication.", icon: LifeBuoy },
    { title: "Payment Follow-ups", text: "Track invoices, dues, receipts, and reminders for every client.", icon: CreditCard },
  ],
  specialtyTitle: "Built for Every Service Business Model",
  specialtyCards: [
    { title: "Agencies", text: "Leads, proposals, approvals, client follow-ups, and delivery tasks.", image: serviceImages[1], icon: BriefcaseBusiness },
    { title: "IT Companies", text: "Demo requests, tickets, projects, onboarding, and account management.", image: serviceImages[2], icon: Settings2 },
    { title: "Consultants", text: "Client enquiries, meetings, documents, quotes, and advisory follow-ups.", image: serviceImages[3], icon: UserCheck },
    { title: "Repair Businesses", text: "Service tickets, technician tasks, job status, and payment reminders.", image: serviceImages[4], icon: Wrench },
    { title: "Maintenance Teams", text: "Recurring jobs, staff schedules, tickets, visits, and client communication.", image: serviceImages[0], icon: CalendarCheck },
  ],
  dashboard: {
    title: "All-in-One Service Business Dashboard",
    dateLabel: "Current Work Week",
    sidebar: ["Dashboard", "Leads", "Quotes", "Tickets", "Tasks", "Clients", "Schedules", "Invoices", "Reports", "Settings"],
    chartTitle: "Jobs & Task Completion Trend",
    sourceTitle: "Top Inquiry Sources",
    sources: ["Website 28%", "WhatsApp 24%", "Referral 20%", "Calls 17%", "Walk-in 11%"],
    rowsTitle: "Recent Service Requests",
    rows: [
      ["Acme Office Setup", "IT service quote", "Today, 02:45 PM", "Quote Review"],
      ["Nora Cafe", "Maintenance ticket", "Today, 04:15 PM", "Assigned"],
      ["Bright Ads", "Agency retainer", "Tomorrow, 10:30 AM", "Follow-up"],
      ["HomeFix Client", "Repair job", "Tomorrow, 01:00 PM", "Scheduled"],
    ],
    taskTitle: "Service Tasks",
    tasks: [
      ["Send revised quote to Acme", "Due in 40 mins"],
      ["Assign technician for Nora Cafe", "Due today"],
      ["Follow up invoice with Bright Ads", "Due tomorrow"],
    ],
  },
  journeyTitle: "Service Journey - Simplified & Automated",
  journeySubtitle: "From inquiry to completed job and payment, every action is tracked",
  journey: [
    { title: "Inquiry Captured", text: "Capture service leads from forms, calls, WhatsApp, referrals, and walk-ins.", icon: Users },
    { title: "Quote Sent", text: "Prepare quotations, approvals, revisions, and client follow-ups.", icon: ReceiptText },
    { title: "Task Assigned", text: "Assign staff, schedule work, and track due dates or site visits.", icon: ClipboardCheck },
    { title: "Ticket Completed", text: "Manage service status, customer updates, proof of work, and feedback.", icon: LifeBuoy },
    { title: "Payment Followed", text: "Track invoices, dues, receipts, and recurring service reminders.", icon: CreditCard },
  ],
  featureTitle: "Powerful Modules for",
  featureSubtitle: "Service Businesses",
  leftFeatures: ["Lead and inquiry management", "Quotation tracking", "Task assignment", "Service tickets", "Client communication"],
  rightFeatures: ["Staff scheduling", "Invoice and payment follow-up", "Client dashboards", "Recurring service reminders", "Role-based team reports"],
  operationsTitle: "More Than Tasks - Built for Client Service Operations",
  operationsSubtitle:
    "HNX CRM Systems helps service teams manage inquiries, quotes, tickets, tasks, staff schedules, client updates, invoices, and project status without scattered spreadsheets.",
  operations: [
    { title: "Inquiry Management", text: "Capture service type, requirement, urgency, location, budget, and owner.", icon: Users },
    { title: "Quotation Tracking", text: "Manage estimates, approvals, revisions, and client decisions.", icon: ReceiptText },
    { title: "Task Assignment", text: "Assign work to staff, monitor status, and keep deadlines visible.", icon: ClipboardCheck },
    { title: "Service Tickets", text: "Track complaints, service requests, escalations, and resolution history.", icon: LifeBuoy },
    { title: "Staff Scheduling", text: "Plan technician visits, consultant calls, delivery tasks, and recurring jobs.", icon: CalendarCheck },
    { title: "Invoice Follow-ups", text: "Track invoices, payment status, receipts, and overdue reminders.", icon: CreditCard },
  ],
  pricingIntro:
    "Service business CRM pricing is scoped around task workflows, ticketing, quotations, client dashboards, scheduling, integrations, reports, and AI requirements.",
  pricingPlans: plans(
    "service business",
    ["Service enquiries", "Quote tasks", "Client records", "Basic dashboard"],
    ["Ticketing workflows", "Task permissions", "Staff scheduling", "Invoice follow-ups", "Advanced reports"],
    ["AI lead scoring", "Smart task suggestions", "Auto message drafts", "Daily work planning", "Report explanations"],
    ["Project tool integrations", "Custom ticket rules", "Advanced roles", "Client portal dashboards"]
  ),
  integrations: [
    { name: "WhatsApp", sub: "Client updates", icon: MessageCircle },
    { name: "Email", sub: "Quotes", icon: Mail },
    { name: "SMS", sub: "Reminders", icon: MessageCircle },
    { name: "Telephony", sub: "Call logs", icon: Phone },
    { name: "Payments", sub: "Gateway", icon: CreditCard },
    { name: "Calendar", sub: "Schedules", icon: CalendarCheck },
    { name: "Accounting", sub: "Invoices", icon: ReceiptText },
    { name: "Projects", sub: "Tasks", icon: Workflow },
    { name: "Reports", sub: "Service KPIs", icon: BarChart3 },
  ],
};
